### ISSUE TITLE
Need access to policy inside getHumanReadableError helper

### ISSUE THREAD

**Issue by sndurkin** [decred/politeiagui#100]
We need access to the policy object fetched from `/api/v1/policy` within `getHumanReadableError()` inside `src/helpers.js`.

**Comment by fernandoabolafio** [comment]
Im working on it

**Comment by fernandoabolafio** [comment]
@sndurkin  As we discussed on slack I guess we can close this issue. The policy won't be added within the `getHumandReadableError()`. We can provide better error messages doing policy validations whereas it is need. Take a look on my PR:
https://github.com/decred/politeiagui/pull/113
