### ISSUE TITLE
Add proposal summary field

### ISSUE THREAD

**Issue by camus-code** [decred/politeiagui#1000]
Copying this issue here as I think it can be solved in the GUI alone:
https://github.com/decred/politeia/issues/569 

Add a length-restricted summary field to proposals. This will require changes to our index.MD file and its related functions so that the field can be handled properly. 

It will also require changes on the submit proposal page so there is another form for inputting the summary. The proposal detail page will also need to have a new, separate section for displaying this summary.

**Comment by xaur** [comment]
How or where will this field be stored and loaded?

**Comment by camus-code** [comment]
I thought this field could be included in the index.md (https://github.com/decred/politeiagui/blob/103c34b3ebc60c358a3c1772d9adcbf21d064fd2/src/helpers.js#L29)

Still working on the specifics but I think it another field can just be added to this payload.

**Comment by xaur** [comment]
That's generally embedding metadata in the document. One of the approaches is Jekyll's [front matter](https://jekyllrb.com/docs/front-matter/) which puts a blurb of YAML at the top of the document.

**Comment by xaur** [comment]
At first I thought having a separate field in the data structure would be better because it removes the (error-prone) need to parse the .md file.

But that field is part of proposal and needs to be versioned. When it is encoded in the .md itself, versioning is solved automatically.

**Comment by camus-code** [comment]
Good point about the issue of versioning. Hadn't even thought about that potential problem. I figured it would just be simpler to include this content the same way we handle the rest of the proposal content.

I should have a PR up tonight / tomorrow morning. All i have left is to format the submit proposal view to include another form for the summary, along with tweaking the proposal detail view to include the summary

**Comment by xaur** [comment]
What do you think about [front matter](https://jekyllrb.com/docs/front-matter/)-style YAML metadata on top of the .md file?

**Comment by camus-code** [comment]
Jekyll does seem interesting but I'm not exactly sure what the benefits are of using this versus how we already process the other proposal fields

**Comment by xaur** [comment]
Sorry I just realized today that my suggestion of embedded YAML is silly without looking into how Pi already stores and versions metadata, which I guess it does already.

**Comment by camus-code** [comment]
No worries at all! I just wasn't sure if I was missing something about Jekyll. nevertheless I appreciate the suggestion 😄
