### ISSUE TITLE
Do not create a new Identity when there isn't one

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#1001]
The current implementation automatically creates a new Identity when it fails to find the user key pair. 
From @lukebp words:
> that's somewhat confusing.  [...] it would be better to instead show some kind of error message like "No identity found.  Please see 'Manage Identity' to import your previous identity or to create a new one."  Then only generate a new identity if the "Create New Identity" button is selected

**Comment by thi4go** [comment]
Working on this!
