### ISSUE TITLE
Indentation issue with comments up/down buttons

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#1011]
The comments indentation around up/down votes need to be polished. It's currently hard to identify what is the comment level. 
The comment body should be entirely aligned at the right side of the up/down buttons.
![screen shot 2019-02-06 at 15 49 46](https://user-images.githubusercontent.com/14864439/52362144-06f01800-2a27-11e9-9227-95968e47bdd6.png)

**Comment by camus-code** [comment]
Working on this one
