### ISSUE TITLE
Improving naming of state-tags: "Pre-voting" and "Active Voting"

### ISSUE THREAD

**Issue by linnutee** [decred/politeiagui#1013]
Referring to this issue opened for Decrediton https://github.com/decred/decrediton/issues/2015
Fair point on consistency. 

I've introduced the term "Under Discussion" instead of "Pre-voting" in Decrediton previously, since pre-voting doesn't communicate this phase very easily nor accurately (e.g. is there's some sort of before-hand voting happening).

Decrediton lists currently the following: `Under Discussion`, `Under Vote`, `Finished Voting`, `Abandoned`. 

Bringing up the issue here, as perhaps the terms could be further ironed out altogether, and then updated in both Pi and Decrediton consistently. The main problem I see with Decrediton tags is the use of double "under". Ideally each state tag should be as simple adjective as possible as when they're all looked at together that also helps to understand each individual one. 

Some thoughts:
1) Pre-Voting → "New Proposals", "Proposals" "In Discussion" "New Submissions" "Submissions" etc
2) Active Voting → "Voting"
3) Approved
4) Rejected
5) Abandoned

**Comment by marcopeereboom** [comment]
There is a duplicate issue where people want decrediton and pi to be consistent. I completely agree that we need to be consistent. Whatever we decide for names must change for both. So once we agree on the naming convention implement both decrediton and pigui.
