### ISSUE TITLE
"Read more" button for comments no longer works

### ISSUE THREAD

**Issue by camus-code** [decred/politeiagui#1015]
The function [here](https://github.com/decred/politeiagui/blob/2a5878bb8152f22ed99d4504ebffd830b7c5ab9f/src/components/snew/ThingComment.js#L25) is longer functional. 

Not sure if this is still a desired feature, but this code should either be updated or removed.

**Comment by camus-code** [comment]
If so, it should probably be included in the discussion for the redesign

https://github.com/decred/dcrdesign/issues/77

**Comment by fernandoabolafio** [comment]
Let's hold this until we apply the new design and then we reevaluate it.

**Comment by fernandoabolafio** [comment]
In the redesign, we don't have collapsed comments so this isn't an issue right now. Feel free to repone it if it becomes an issue in the future.
