### ISSUE TITLE
Markdown full page preview

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#1017]
Dustin is currently writing a marketing proposal and ran into the issue of not being able to preview what his markdown tables would look like in the normal, full page proposal details view.

Is there a reason that the current markdown editor is setup the way it is and do you think it would be beneficial to have a full page preview instead?  Maybe a preview tab like Github has.

**Comment by victorgcramos** [comment]
Added the **tab** preview style to the SubmitPage component. I think this might help to see how the proposal will look like on the ProposalDetail page.

**Comment by fernandoabolafio** [comment]
@RichardRed0x @degeri I tagged you as you have written proposals for Politeia so I would be nice to know about your experience and get more feedback before we get the code in.
Do you prefer the current layout (proposal|preview) or do you think would be better to switch show one at a time (same as comments for instance)?

**Comment by degeri** [comment]
One issue with the current layout I faced was that if the page content gets very long the browser reaction times (to user input) slows down . Having it one at a time might help fix that.

**Comment by RichardRed0x** [comment]
I have not encountered any issues with the current layout, it worked as expected for me. Tabs to switch between edit and preview mode would be good too though, maybe even better.

**Comment by xaur** [comment]
We already have preview tab for comments which is very convenient.
