### ISSUE TITLE
standardize [politeia-public proposals] with [decrediton-governance]

### ISSUE THREAD

**Issue by ghost** [decred/politeiagui#1025]
For Decrediton / macOS / 1.4.0 / SPV mode 
- “Under Discussion” (currently 4 proposals)
- “Under Vote” (currently 3 proposals)
- “Finished voting” (currently 8 proposals)
- “Abandoned” (currently 5 proposals)

For Politeia / Public Proposals
- “all proposals” (currently 18 proposals)
- “pre-voting" (currently 4 proposals)
- “active voting” (currently 3 proposals)
- “approved” (currently 5 proposals)
- “rejected” (currently 6 proposals)
- “abandoned” (currently 5 proposals)

Note:
-  Similar issue opened in decrediton repository. https://github.com/decred/decrediton/issues/2047
- Include "abandoned" proposals in the "all proposals" total count. "all proposals" is currently 18. If you include (pre-voting, active voting, approved, rejected, abandoned) it equals 23.

**Comment by marcopeereboom** [comment]
I agree with this. @camus-code can you run with this?

**Comment by marcopeereboom** [comment]
Dup #1013
