### ISSUE TITLE
Wrong rendering with loading buttons

### ISSUE THREAD

**Issue by thi4go** [decred/politeiagui#1027]
Buttons that have a loading state are not being rendered correctly once they are loading. The text that is associated with that button gets pushed down by the loading icon, and gets rendered on the bottom of the button.

This can be resolved by setting the `text` property conditionally; if the button is loading, no text gets rendered, if not, render text.

`text={isApiRequestingUpdateUserKey ? "" : "Create new identity"}`

**Comment by camus-code** [comment]
@thi4go this issue can be closed. I didn't properly reference it in the PR which closed it so it did not automatically close.

**Comment by thi4go** [comment]
Nice @camus-code, closing the issue.
