### ISSUE TITLE
Yellow text on white background hard to read 

### ISSUE THREAD

**Issue by s-ben** [decred/politeiagui#1029]
Loving the aesthetic improvements lately, but this yellow text on white background is killing me. Change to another color?

![image](https://user-images.githubusercontent.com/1634777/53472313-296cc400-3a1c-11e9-830b-a56a996767ed.png)

**Comment by dornelasN** [comment]
Hi @s-ben, I tried two different colors that are not as bright as the yellow used on this warning text. Can you check below if any of them look good?

The old one in my computer:
![image](https://user-images.githubusercontent.com/9327569/56531439-6e980880-652a-11e9-8caf-b55cf0569f59.png)

Option 1, still a little bright:
![image](https://user-images.githubusercontent.com/9327569/56531481-7e175180-652a-11e9-924f-19b9f0649c02.png)

Option 2:
![image](https://user-images.githubusercontent.com/9327569/56531513-8f605e00-652a-11e9-8b3a-8b9ff1b2061d.png)

**Comment by s-ben** [comment]
Hi @dornelasN, both look more readable to me, but wondering if we can do better aesthetically? Perhaps just switch to orange? Perhaps sample the color from our current UI so we can maintain consistency. Thoughts?

![image](https://user-images.githubusercontent.com/1634777/56534838-4f3fb200-650f-11e9-9f14-124cadd0aec7.png)

**Comment by dornelasN** [comment]
I see, I was trying to keep the "yellow" look on it. But I believe it makes sense to change to orange if there are more components using the color like the "Yes" side of the bar and the number of votes like you showed. I'm new to the project and I still don't know yet what is being used and what might look better. I'll check it out the orange colors that are being used!

**Comment by s-ben** [comment]
Yeah there's really no hard template to follow on Politieia yet, afaik. Feel free to experiment with what looks best. There is this kit the design team put out for the project generally. If you can adhere to that, it would make design happy:)
https://decred.org/brand/

**Comment by fernandoabolafio** [comment]
I wouldn't spend too many thoughts on it since we will go through the redesign anyway. Also, the orange in the progress bar has a different meaning than the "Waiting for admin approval". I would just go with a darker yellow to improve the contrast now. Btw, option 1 looks good to me.
