### ISSUE TITLE
Do not destroy user state when session expires

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#1031]
I was reading unread comments when the session died, and after the redirect I lost all unread state. The real fix for the problem is #1021, but perhaps no disrupting auto redirect is a good idea too.

**Comment by xaur** [comment]
I was writing a reply when the session expired. It changed view without asking and destroyed the comment I was writing. Ok in reality I was warned with a banner that I got 1 minute left and saved the comment, but if I had a large wall of text in text area and went to bathroom it would be gone.

This is ridiculous, session expiration should not destroy state!

**Comment by fernandoabolafio** [comment]
@xaur we don't plan to address this for the old version of politeiagui. This has been addressed in the redesigned gui and comments are persisted as long you don't close the browser tab. Feel free to re-open it in the future if you think it is still an issue.
