### ISSUE TITLE
Proposal can't be submitted after local validation fails

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#1038]
Every time a client-side validation fails, the "Submit" (or "Update") button gets disabled irreversibly, making necessary to refresh the page. 
Steps to reproduce:

- Go to the proposal submission page
- In the proposal body, add an invalid link: (click me)[google.com]
- Submit the proposal

Result: you should see an error alerting for the invalid link, and the "Submit" button will be disabled. Even after correcting the link, the button is still inaccessible.

**Comment by victorgcramos** [comment]
I can handle that!

**Comment by victorgcramos** [comment]
Hi @fernandoabolafio I couldn't replicate this error. Here is what happens when I try to do what you told.

![proposal-submit-after-validation-fails](http://g.recordit.co/cY30rJXWpY.gif)

**Comment by fernandoabolafio** [comment]
You're correct @victorgcramos. The button gets reactivated after editing the body content.
