### ISSUE TITLE
Notifications for all comments of the proposal

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#1040]
Currently people get notifications only for replies to their comments. There's no way to subscribe to all comments on a given proposal (similar to github issue).

Part of #728

**Comment by xaur** [comment]
Part of #728

**Comment by fernandoabolafio** [comment]
@xaur this issue requires backend work first. Is there any issue created for this?

**Comment by xaur** [comment]
@fernandoabolafio there are some issues with "notification" in politeia repo, but I'm not sure which one would cover this feature. I just figured this will definitely require UI changes so opened it in politeiagui.

**Comment by fernandoabolafio** [comment]
@xaur I did a quick rundown through the politeia issues and doesn't seem to be an issue for that. Can you write one up? Without having this firstly validated and implemented in the backend, there is nothing to be done in the GUI.

**Comment by lukebp** [comment]
This has been added to the politeia feature request thread (decred/politeia#1502).
