### ISSUE TITLE
Incorrect proposal title insertion

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#1041]
The proposal title is being inserted into the proposal markdown file incorrectly.  It's missing a new line character, which causes the rendered markdown to be formatted incorrectly.

Example: https://github.com/decred-proposals/mainnet/blob/master/0aaab331075d08cb03333d5a1bef04b99a708dcbfebc8f8c94040ceb1676e684/1/payload/index.md

**Comment by xaur** [comment]
Rendering is only part of the problem. I'm more concerned by elegance and future proofness.

"We need to insert the title into the markdown somehow..." -> "Just stuff it in at the beginning delimited with a single \n" is a hacky approach. I wonder how it sneaked in. If these documents are now signed, it's challenging to migrate them.

#1010 and [politeia#690](https://github.com/decred/politeia/pull/690) try to take it even further: "We need to insert the summary field into the markdown somewhere..." -> "Just stuff it in at the **end** delimited with a single **\r**". What could go wrong? I'm surprised such ideas are approved and make it so far into implementation. Or, I'm crazy. Please tell me if so.

This is a confusing and error prone way to insert metadata into payload.

**Comment by lukebp** [comment]
>  If these documents are now signed, it's challenging to migrate them.

Why?

> This is a confusing and error prone way to insert metadata into payload.

I don't understand.  The title is not metadata.  The title is part of the proposal file.  It is the payload.  An example of proposal metadata would be the signature. If we were trying to insert metadata like the signature into the payload I could see your point because that would make no sense.

**Comment by lukebp** [comment]
To put it another way that may make more sense, user input is not metadata.  When the user submits a proposal they sign a merkle root of the files.  By doing so they are attesting to the validity of those files.  All of the user input must be in those files in order for there to be cryptographic proof of the user's submission.

**Comment by xaur** [comment]
> > If these documents are now signed, it's challenging to migrate them.
> 
> Why?

I think if you have files formatted as `title\nbody`, and that `title\nbody` is covered by signature, to change it to e.g. `title\n\nbody` it needs to be re-signed. Right?

> user input is not metadata

Nice way to look at it. I didn't think about title as metadata until the talk about summary field started. Then I started calling metadata anything that is not proposal body: title, summary field and the possible (but unlikely) human identifier. Perhaps we can call it user-generated metadata and system-generated metadata.

Regardless of terminology, I still think it's a hacky way to insert fields into the document.

**Comment by xaur** [comment]
Related question is why title is stored both inside the document and one of the metadata files ([example](https://github.com/decred-proposals/mainnet/blob/master/0aaab331075d08cb03333d5a1bef04b99a708dcbfebc8f8c94040ceb1676e684/1/00.metadata.txt))?

**Comment by s-ben** [comment]
Per the comment I just left on https://github.com/decred/politeia/issues/718 , it seems like putting "metadata" (title, summary, etc.) into the markdown seems like a good idea. It's confusing because in most other contexts (e.g. publishing a static website) the title, summary, etc. are generally metadata. Usually yaml metadata.

**Comment by lukebp** [comment]
> Related question is why title is stored both inside the document and one of the metadata files 

It's included in the payload because it needs to be signed by the user.  It's included in the metadata file so that we don't have to fetch the full payload in order to display the proposals list view. 

> It's confusing because in most other contexts (e.g. publishing a static website) the title, summary, etc. are generally metadata. Usually yaml metadata.

That's true.  Whether we call it metadata or not is really just semantics at this point.  The reason we're different is because of our requirement that all user data be cryptographiclly verifiable.  The small bit of redundancy that this causes is not a big deal.

**Comment by xaur** [comment]
> It's included in the payload because it needs to be signed by the user. It's included in the metadata file so that we don't have to fetch the full payload in order to display the proposals list view.

Thanks for clarifying, I've been wondering for a long time.

So the copy of the title string included in the metadata is soft of cache that is committed to Git. Is it still relevant with the cache layer? (concerned about cache invalidation obviously).

**Comment by camus-code** [comment]
Working on this one!

**Comment by camus-code** [comment]
Hmmm so I could be mistaken @lukebp but I believe this may be a backend issue. I'm still trying to pin down where exactly things are going wrong, but from what I can tell it's arriving from the GUI with the newline character inserted.

For example, without the newline character, wouldn't the function here fail to properly return the proposal name? https://github.com/decred/politeia/blob/d1ec6ce2a5ab291545ef08cb2b6a38bea41fb147/util/proposal.go#L22-L38

**Comment by lukebp** [comment]
@camus-code if it is a backend issue, can you track it down and fix it?

**Comment by camus-code** [comment]
Yeah definitely @lukebp . Just wanted to let you know in case we wanted to close this issue and make a new one on the backend

**Comment by lukebp** [comment]
Once you verify that it is indeed a backend issue you can close this one and open a politeia issue.
