### ISSUE TITLE
External link warning modal issues

### ISSUE THREAD

**Issue by degeri** [decred/politeiagui#1047]
1.
One of the issues highlighted in https://github.com/decred/politeiagui/issues/960 is back. The modal should close if the back button is pressed. 

2.

I also found that if the URL of the website contains a hash "#" (fragment identifier) then anything after that is not shown in the warning. This needs to be fixed since in many websites the content is dynamically loaded based on the fragment identifier. 

![image](https://user-images.githubusercontent.com/41839293/54706091-1d2fde80-4b64-11e9-9bf9-f498a964ea26.png)

**Comment by camus-code** [comment]
Working on it
