### ISSUE TITLE
Have different layout to testnet and mainnet

### ISSUE THREAD

**Issue by vctt94** [decred/politeiagui#1049]
On decrediton, we have a different color layout for testnet and mainnet. So it is easier to know when we are in each one. 

Right now on politeia, the layout looks the same for https://proposals.decred.org/ and https://test-proposals.decred.org/ The only difference is the URL (and proposals, but if you look fast enough they will look the same)

Would be good having some more visual indicator that we are on testnet.

**Comment by linnutee** [comment]
re: @MariaPleshkova 
Wouldn't go as far as changing the entire layout but only changing the header color and possibly including a derivate testnet version of the logo should be enough. E.g. decrediton.

**Comment by fernandoabolafio** [comment]
As @linnutee observed, changing the header is enough. Thus, this issue is better described at https://github.com/decred/politeiagui/issues/1072. Closing it.
