### ISSUE TITLE
Remove insight verification when dcrdata verification fails

### ISSUE THREAD

**Issue by vctt94** [decred/politeiagui#1050]
When verifying some transaction at gui, when dcrdata fails, the gui try with insight, which is generating the following error: 

![image](https://user-images.githubusercontent.com/15069783/54774207-f87e4a00-4be9-11e9-8df3-9d6a676bb84b.png)

We should remove the verification against insight, as it is deprecated

**Comment by camus-code** [comment]
Working on this
