### ISSUE TITLE
Cache more site data in local storage

### ISSUE THREAD

**Issue by camus-code** [decred/politeiagui#1053]
As of now, we only store draft proposals and the API "me" response in local storage. We could be caching a lot more content to prevent unnecessary fetching.

Data which could be cached includes:
-Approved proposals
-Rejected proposals
-Abandoned proposals
-User proposals
-Sidebar Markdown
-API Policy

**Comment by camus-code** [comment]
Working on this as well

**Comment by fernandoabolafio** [comment]
I have a few suggestions for this:
- For caching the entire response, such as for API Policy, consider using service workers. 
- One way for caching view parts such as Sidebar Markdown and API Policy is by using code splitting for the specific parts you want to be cached. It may be worth to check how service workers would play with it too.
- About proposals caching, as far as I know, the vetted endpoint return all the public proposals despite their vote status, so if the frontend caching only helps if its possible to fetch proposals by their vote status.

**Comment by camus-code** [comment]
Thanks for all the suggestions @fernandoabolafio ! I was initially trying to just use the browser's local storage but after doing some more reading I think service workers would be the correct choice for this type of caching.

As for code splitting, I'll have to do some more research into how this would work with our current setup as I've only done this when using React + Webpack. On a side note, I'm also going to look into using React.Suspense to better optimize our view components. (Although that is probably worthy of its own issue)

Lastly, the vetted endpoint is indeed a roadblock for proposal caching. I'm not too sure where he is in the process, but I know @lukebp was working to clean up this route along with the vote statuses route

**Comment by camus-code** [comment]
@fernandoabolafio Thinking about closing this issue in favor of making a more specific one for https://github.com/decred/politeia/issues/796

Once we get that resolved, I think we can look back into using service workers && local storage to further optimize the site

**Comment by fernandoabolafio** [comment]
I agree @camus-code.
