### ISSUE TITLE
Login page rendering elements out of place

### ISSUE THREAD

**Issue by s-ben** [decred/politeiagui#1055]
I was logged out automatically by timeout. Then was sent to the login page, where the visual elements weren't rendering correctly (On Brave v0.58.21). For instance, the login auto-fill was off to the side:

![image](https://user-images.githubusercontent.com/1634777/55254468-2597b180-5215-11e9-8a66-5fc8faddabc3.png)

Also (couldn't catch this with screenshot), the login screen was blinking blank and filled in for a few seconds. It appeared to settle after a few seconds into the correct position..

**Comment by fernandoabolafio** [comment]
Should be fixed in the newly released version.
