### ISSUE TITLE
Basic "pay invoice" by Admin

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#1058]
For MVP we should have a basic "pay" invoices functionality for admins.  This should at least allow the admin to enter a txid of the payment transaction.  More to come on this in the future.

**Comment by alexlyp** [comment]
Yah this should be one of the last pieces we should worry about for MVP.  We'll have more discussion about what this "pay" functionality will entail once @behindtext gives us his thoughts on it.

**Comment by alexlyp** [comment]
This is roughly spec'ed out in #1078

**Comment by fernandoabolafio** [comment]
closed on #1099
