### ISSUE TITLE
User invoice overview

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#1059]
Landing page for Users.  Maybe showing total amounts, total invoices per status, etc.

**Comment by alexlyp** [comment]
Yah I was thinking roughly a list of user invoices and some stats about recent invoices.  Maybe totals of unpaid/paid invoices? Thoughts @behindtext?  

This page isn't super important for MVP as long as we can at least display the results of a userinvoices call or something.

**Comment by fernandoabolafio** [comment]
@alexlyp I thought about something like this for the first version:

![Screen Shot 2019-04-10 at 13 58 43](https://user-images.githubusercontent.com/14864439/55876821-d51b3f00-5b98-11e9-9d97-30d33f7b3a39.png)

This can be easily accomplished with our current setup. What do you think?

**Comment by alexlyp** [comment]
Yah I think that looks really good for a starting point!
