### ISSUE TITLE
add paywall component

### ISSUE THREAD

**Issue by jolan** [decred/politeiagui#106]
Need to port the bootstrap+jquery widget from dcrpayments.

**Comment by vctt94** [comment]
This is the paywall workflow @marcopeereboom listed on slack. 

1) Sign up 
2) Get email + Click Link
3) Make payment (with dcrpayments?)
4) Wait and get access (A callback from dcrpayments?)

 @jolan  I am not familiar with this bootstrap+jquery widget you mentioned, but I believe we are going to use it for payments right?

Also @fernandoabolafio is interested in helping on this issue

**Comment by jolan** [comment]
For reference, this is what the testnetstore widget looks like:

![Image of testnetstore](https://i.imgur.com/wUzkR2u.png)

Basically you will need to poll the block explorers for transactions to the user's paywall address:

https://github.com/decred/dcrpayments/blob/master/php-exampletestnetstore/index.php#L450-L538

Then once we have 2+ confirmations, we will want to post the tx to politeiawww so it can verify it (still waiting for the paywall backend to get merged at the moment but it'll be ready soon).

We probably want the user landing page first https://github.com/decred/politeia/issues/59

That would allow the user to verify their email as "step 1" and then once that is done, "step 2" would be the paywall/this component.

Re the bootstrap+jquery widget, no we don't want to use it.  We want it ported to the politeiagui code/style.

**Comment by jolan** [comment]
It would be convenient to add a 'pay with testnet faucet' button to the widget on testnet:

https://github.com/jolan/politeia/blob/d84b85b07740885b9f1ad3fdd49124f8ecb1dafc/util/paywall.go#L69-L130
