### ISSUE TITLE
Feature toggling

### ISSUE THREAD

**Issue by jholdstock** [decred/politeiagui#1067]
`politeiagui` has recently been modified so it can serve as the front end for both the Treasury Proposal system (pi) **and** the Contractor Management System (cms). The implementation has resulted in undesirable code patterns emerging:

- **Duplicated code/files** - where we previously had [user.js](https://github.com/tiagoalvesdulce/politeiagui/blob/84bd23d9c4e58f3e49cd513a62d5c6e916184db9/src/connectors/user.js), we now also have [userCMS.js](https://github.com/tiagoalvesdulce/politeiagui/blob/84bd23d9c4e58f3e49cd513a62d5c6e916184db9/src/connectors/userCMS.js). The new file only contains minor differences. Also see [userInvoices.js](https://github.com/tiagoalvesdulce/politeiagui/blob/84bd23d9c4e58f3e49cd513a62d5c6e916184db9/src/connectors/userInvoices.js) vs [userProposals.js](https://github.com/tiagoalvesdulce/politeiagui/blob/84bd23d9c4e58f3e49cd513a62d5c6e916184db9/src/connectors/userProposals.js)
- **isCMS** - a single boolean `isCMS` is used throughout the code to disable certain features, or to switch between different behaviors.

This pattern is not sustainable in the long term and it is a serious hindrance in making `politeagui` a product which can be reused for many purposes. I propose the following to solve this problem.
- Add an external config file
	- Perhaps reading `~/.politeiagui/politeiagui.conf` using a lib such as https://github.com/steveukx/properties?
- Remove instances of `isCMS`, and replace them with "feature toggles" which are picked up from the config file. Here are some of the toggles we will need:
    - Enable paywall
    - Enable admin invite
    - Enable email verification
    - Enable public registration
    - Enable comment voting
    - Enable PoS ticket voting
    - Document format (Proposal or Invoice)
    - Enable proposal credits

If this change is implemented correctly the `politeiagui` code should at no point be aware if it is being used for Pi or CMS, it should only be aware of which features are enabled/disabled. This implies that the flag `isCMS` and any files/variables names which contain `CMS` should be removed.

**Comment by fernandoabolafio** [comment]
I have some thoughts to drop about it. 

1. Just to confirm we are not overthinking this. Does it make sense to enable functionalities in an isolated way while the politeiawww doesn't have the same level of customization? Right now politeiawww has a pretty clear border between the Invoices and the Proposals system.

2. If we are going to have this level of customization on politeiagui what I suggest is to use a [dotenv](https://github.com/motdotla/dotenv) to load the configuration and then we pass the configuration into a Config Provider using the [context API](https://reactjs.org/docs/context.html) which will validate the config as props and make this config values available deep into the component tree. 

Something like this: 

**.env file:**
```dosini
ENABLE_PAYWALL=TRUE
RECORD_TYPE=invoice
...
```

**ConfigProvider.js**
```jsx
const ConfigProvider = ({ enablePaywall, recordType }) => (
...
)

ConfigProvider.propTypes = {
  enablePaywall: propTypes.bool
  recordType: propTypes.oneOf(["invoice", "proposal"])
  ...
}
```

**App.js** (Entry point of the app)

```jsx
require('dotenv').config()
const App = () => (
  <ConfigProvider
   enablePaywall={process.env.ENABLE_PAYWALL}
   recordType={process.env.RECORD_TYPE}
  >
  ...
  </ConfigProvider>
)
```

**Comment by lukebp** [comment]
This is being addressed by the addition of politeiagui plugins (#2498).  Similar to the backend, base functionality will include basic record functionality.  Application specific functionality will be added via composable plugins.
