### ISSUE TITLE
String configuration

### ISSUE THREAD

**Issue by jholdstock** [decred/politeiagui#1068]
`politeiagui` has recently been modified so it can serve as the front end for both the Treasury Proposal system (pi) **and** the Contractor Management System (cms). As a result, many of the strings appearing in the CMS are incorrectly referencing Proposals instead of Invoices, and the string Politeia still appears. In the few places where this has been fixed, a boolean variable `isCMS` is used to switch one hard-coded string for another.

https://github.com/decred/politeiagui/blob/74db2ba9c109eda41dab09ab25a316f7ffa9b1c9/src/components/snew/UserInfo.js#L65

To support the goal of making `politeagui` a product which can be reused for many purposes, it should be possible to configure the strings on the site using config files and without making code changes.

**Comment by lukebp** [comment]
This is being addressed by the addition of politeiagui plugins (#2498).  Similar to the backend, base functionality will include basic record functionality.  Application specific functionality will be added via composable plugins.
