### ISSUE TITLE
Clearer error message on "change username"

### ISSUE THREAD

**Issue by degeri** [decred/politeiagui#1069]
In the "change username"  if a wrong password is given the error is "The provided email address or password was invalid." this should instead be "The provided password was invalid."

At this point the user is already logged in and knows the email ID. There is no need for ambiguity here. 

I guess this also requires changes to politeia.

**Comment by s-ben** [comment]
Working on this.

**Comment by s-ben** [comment]
Nm. Thought this was just a copy change, or simple code change, but don't know enough JS to implement this. Still open.

**Comment by victorgcramos** [comment]
I can take a look at this!

**Comment by fernandoabolafio** [comment]
closed on https://github.com/decred/politeiagui/pull/1158
