### ISSUE TITLE
Markdown editor acts weird on Galaxy Note 8

### ISSUE THREAD

**Issue by sndurkin** [decred/politeiagui#107]
A user reported in Slack that the markdown editor doubles certain words while typing.

Device: Galaxy Note 8
Browser: Chrome, Firefox

Using Chrome:

> If I type "decred.o" and then "r", I get "decred.odecred.or"

> "google.c" &"o" gives me google.cgoogle.co

Firefox seems to be worse:

> Any time I hit space, comma, or period, the entire word just disappears!

The issue is reproducible using the base `headzoo/react-markmirror` component, but it's not as bad with the `JedWatson/react-md-editor` component. For `JedWatson/react-md-editor`:

> it seems to delete periods the first time i type them. So "decred." becomes just "decred", but if I type the "." again it stays.

**Comment by fernandoabolafio** [comment]
We need to test it again with the new markdown editor.

**Comment by sndurkin** [comment]
The user retested and reported that the new editor is working fine.
