### ISSUE TITLE
Specify the units required for each invoice form field

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#1073]
It is not clear in the invoice form what is the unit format of each quantitative field. Here is a list of the fields where we should add some help text:
 - Contractor rate: USD cents
 - Expense: USD cents
 - Labor: number of minutes

**Comment by alexlyp** [comment]
Ya I was thinking we would allow entry in dollars/hours and then convert before submitting.  It's definitely an odd situation to make sure people are entering in the proper information.

**Comment by fernandoabolafio** [comment]
hmm yeah, using dollars/hours and convert before submit is a good option too. Should we go that way then?

**Comment by alexlyp** [comment]
Yah I think as long as we establish the pattern now it should be fine.
