### ISSUE TITLE
[cms] Signup/next should be avoided

### ISSUE THREAD

**Issue by alexlyp** [decred/politeiagui#1080]
The success page for signup (signup/next) doesn't need to be shown since the information isn't accurate.  Probably a success modal with a short message should show up.

**Comment by camus-code** [comment]
Do we want to just show different text on the signup/next screen for CMS? Or would you like to avoid showing this route in favor of a modal popup? @alexlyp

**Comment by alexlyp** [comment]
Hrm well I guess we could just change the text on the signup/next screen for now.   Definitely would be the least invasive.  

So maybe add something like:

"Congratulations, you have fully registered for the Contractor Manangement System!
You may now login in.  Please refer to <link to upcoming instructions md> for instructions on how to appropriately create and submit invoices."

**Comment by camus-code** [comment]
Ok cool. Just didn't want to make the signup flow too different from piwww.

Working on this

**Comment by alexlyp** [comment]
hrm ya those errors will be different.  we'll have to review which errors need to be added.  But verifyNewUser end point is no longer used

**Comment by camus-code** [comment]
I thought as much but just making sure. Putting this on the back burner until we decide which errors we want to use in place of these.

As for the `verifyNewUser` endpoint, is this route the comparable one for cms? https://github.com/decred/politeia/blob/8008bc31bc8b01e6a90ab35982a4ea53c107510c/politeiawww/api/cms/v1/v1.go#L14

**Comment by alexlyp** [comment]
well there isn't really a replacement for verifyNewUser, but register is verifying the provided token.

**Comment by alexlyp** [comment]
Well after thinking about it more, `invite` is essentially a replacement for `newUser` and `register` is replacing `verifyNewUser`

**Comment by alexlyp** [comment]
@camus-code any update on this one?

**Comment by camus-code** [comment]
sorry for the delay @alexlyp, had computer issues the past week and ended up having to restore over the weekend. I lost my local dev environment and so I'm rewriting the code I had for this. Should have the PR up a little later today.
