### ISSUE TITLE
Invoices tab counting must be updated accordingly to date filter

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#1090]
The invoices counting are not being updated when the invoice list is filtered by month & year.
See screenshot below:
![Screen Shot 2019-04-15 at 12 30 18](https://user-images.githubusercontent.com/14864439/56125974-6106df80-5f7a-11e9-8e30-1bd446b33b7a.png)

**Comment by thi4go** [comment]
Working on this
