### ISSUE TITLE
Date filter should be reseted by default if no params in query string

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#1091]
Steps to reproduce: 
- Go to admin invoices list
- Set a dater filter (ex: 04/2019). The query params are updated accordingly.
- Go to another route (ex: home) 
- Go back to admin invoices list, the query string is blank (as expected) and the date filter is still showing the old filter (04/2019)

The date filter must be reset to its default state every time the query parameters don't exist or are blank.

**Comment by camus-code** [comment]
Working on this!
