### ISSUE TITLE
Lazy load proposals using inventory route

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#1107]
Since https://github.com/decred/politeia/pull/809 we can now fetch the token for all public proposals already categorized into pre-voting, active, finished and abandoned.  
With that, the public proposals loading must be lazy loaded as the user scroll through the list or switch tabs.

**Comment by marcopeereboom** [comment]
![image](https://user-images.githubusercontent.com/4366787/56524824-b493a300-650f-11e9-9508-58603f0193f6.png)

While implementing this we need to shuffle the order of these tabs. Let's go with:
Active voting, Pre voting, Approved, Rejected, Abandoned, All

**Comment by fernandoabolafio** [comment]
The token inventory route returns the following structure: 

```go
type TokenInventoryReply struct {
	Pre       []string `json:"pre"`       // Tokens of records that are pre-vote
	Active    []string `json:"active"`    // Tokens of records with an active voting period
	Finished  []string `json:"finished"`  // Tokens of records with a finished voting period
	Abandoned []string `json:"abandoned"` // Tokens of records that have been abandoned
}
```
So, if we want to follow that without any more hackings, we need to have "approved" and "rejected" as part of the same "Finished" list. Also, as @lukebp has pointed out, we just have the concept of "approved/rejected" now because we are only using binary "yes or no" options for voting. Soon we will have multiple choice votings so this categorization will no longer make sense.

**Comment by marcopeereboom** [comment]
And by soon you mean whenever someone writes that code :)

The code required to add multiple choice in this API is trivial so we'll cross that bridge when we get there.

@lukebp can you split finished in approved/rejected?
