### ISSUE TITLE
Proposal detail page crashing after refresh

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#1108]
- Go to a proposals detail page such as https://test-proposals.decred.org/proposals/369a21b8ee55c683baf26763c2cbe0a5b7c677ec5ceefa19a90596e5ae9829f0.
- Hit refresh: the page stays blank.

Note: I am not able to reproduce this locally.

**Comment by fernandoabolafio** [comment]
I suspect this is due to CSP blocking the content. I tested the latest version of politeiagui in another server and it doesn't present the same error. 
The last update of CSP was done here: https://github.com/decred/politeiagui/pull/935.

**Comment by dajohi** [comment]
this is nginx issue.  fixed by serving locally, for now.
