### ISSUE TITLE
proposals: ERROR: you must be logged in to perform this action.

### ISSUE THREAD

**Issue by dajohi** [decred/politeiagui#1112]
https://test-proposals.decred.org/proposals/5768ce88ee3e2bb77f08f887d43f71771f422df0deaef23a7b729c7dcb60a0b3 shows
```ERROR: You must be logged in to perform this action. main.ca876c91.chunk.js:1:248904```

**Comment by camus-code** [comment]
Working on this one. Tests should've caught this error but I'm pretty sure we were testing a non-existent route here: 

https://github.com/decred/politeiagui/blob/cd6f067368d0d3b1634c05d5f4f93be6d6c8e11e/src/actions/tests/api.test.js#L511
