### ISSUE TITLE
Fix Permalink for Censored Comments

### ISSUE THREAD

**Issue by camus-code** [decred/politeiagui#1113]
https://test-proposals.decred.org/proposals/8bba1af73b211b9319348fea7434e80d6a895ba9fa5d19410fbbe1d1ae06c15e/comments/1

The permalink button is showing up to the left of "[Censored by Moderators]" instead of below the text.

I'm not too sure if we want to keep the permalink option for censored comments but the styling should be fixed at the very least.

**Comment by victorgcramos** [comment]
This seems to be a UI fix. Check that out: https://github.com/decred/snew-classic-ui/pull/29

**Comment by fernandoabolafio** [comment]
@victorgcramos your PR on snew is in, you will need to open a PR in politeiagui to sync the latest commit of snew which will effectively bring the update to politeiagui.

**Comment by fernandoabolafio** [comment]
Changes in https://github.com/decred/snew-classic-ui/pull/29 from Snew were synced into Politeiagui on a different PR. Hence, this can be closed.
