### ISSUE TITLE
Update test for 'on fetch liked comments action'

### ISSUE THREAD

**Issue by camus-code** [decred/politeiagui#1115]
https://github.com/decred/politeiagui/blob/cd6f067368d0d3b1634c05d5f4f93be6d6c8e11e/src/actions/tests/api.test.js#L511

This code is currently testing a non-existent route. This should be updated to the correct `commentslikes` route

We should also consider extending test coverage to more prominently warn for unmatched routes such as this one

**Comment by camus-code** [comment]
@fernandoabolafio looks like the reason why the above test did not fail was because our test coverage only warns for unmatched routes instead of failing. 

Should we change the coverage so that unmatched routes cause tests to fail? Or should we leave as-is and simply update this incorrect route?

**Comment by fernandoabolafio** [comment]
@camus-code Yes, I think the test should fail in case the route doesn't match. Iirc, we have some tests which we actually use  "unmatched" routes as a fallback, in that case the warning would be enough. So maybe what we want is a way to say when we want the test to fail if the route doesn't match.
