### ISSUE TITLE
 File name determines image display size [2]

### ISSUE THREAD

**Issue by degeri** [decred/politeiagui#1119]
https://github.com/decred/politeiagui/issues/898 is back. 

Look at the images under:
https://test-proposals.decred.org/proposals/a507d3f10c74bc673ebbffebbf8519dffac50d94251ff4733a120aec570c5c75

Both images are the exact same files but one is having file name as "largefilename111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111.png"
another is having filename "smlcircle.png" this is making one look bigger then other. So how much space an image will take up depends on the length of the file name.

![Selection_028](https://user-images.githubusercontent.com/41839293/56458967-feaf4400-63aa-11e9-8306-2653f0853f41.png)
![Selection_029](https://user-images.githubusercontent.com/41839293/56458968-00790780-63ab-11e9-8512-2ae685f1149c.png)

**Comment by marcopeereboom** [comment]
Wow, great find. I'd love to see what on earth is causing this.

**Comment by victorgcramos** [comment]
I can take this!
