### ISSUE TITLE
Proposal info inconsistencies

### ISSUE THREAD

**Issue by jzbz** [decred/politeiagui#1130]
If I click on a link to a proposal say from https://proposals.decred.org/?tab=active%20voting I will see information on the new page about how long the vote has until completion.
If I visit the proposal link directly this info will be missing (see screenshots below).

![image](https://user-images.githubusercontent.com/4731927/56633764-7d1b1880-662d-11e9-9926-9b5df4ff1e60.png)
![image](https://user-images.githubusercontent.com/4731927/56633732-65dc2b00-662d-11e9-8f2f-26c990b37bad.png)

Refreshing the page after visiting the proposal from the active voting link causes the vote duration info to disappear.

Also if visited from the link the title of the page will not be correct until a refresh is performed.

**Comment by camus-code** [comment]
Picking this one up
