### ISSUE TITLE
Truncate calc for quorum and pass requirements

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#1142]
The gui currently rounds the result for the quorum and pass requirements.  The results should not be rounded, they should be truncated.

Example:
eligible tickets = 40969
quorum = 0.2 * 40969 = 8193.8

The gui currently rounds this to 8194.  It should be truncated to 8193 votes.

**Comment by fernandoabolafio** [comment]
closed on https://github.com/decred/politeiagui/pull/1143
