### ISSUE TITLE
Responsive GUI

### ISSUE THREAD

**Issue by peterzen** [decred/politeiagui#1147]
The current UI is difficult to read on mobile devices, the user needs to zoom and pan on the screen in order to be able to read the proposals.  It would be useful to implement a responsive layout to make the content easier to read.

![Screenshot_Chrome_20190430-211642](https://user-images.githubusercontent.com/5878500/56987383-92dc9080-6b8d-11e9-9e1c-6784b2dfaa13.png)

**Comment by fernandoabolafio** [comment]
@peterzen we have a new design of pi coming out in the next few months which will make pi much more responsive. You can track the status of it here: https://github.com/decred/dcrdesign/issues/77.
