### ISSUE TITLE
need to display error context on password errors

### ISSUE THREAD

**Issue by jolan** [decred/politeiagui#115]
Currently there is no indication to the user what is actually wrong with the password.

**Comment by thi4go** [comment]
Looking into it !

**Comment by sndurkin** [comment]
@thi4go, for this issue we just have to check whether the UI is validating that the password is at least 8 characters, and informing the user if it isn't. It should be pulling the number from `passwordminchars` from [the `/v1/policy` call](https://github.com/decred/politeia/blob/master/politeiawww/api/v1/api.md#policy).

Note that this validation should happen both for registering a new user and for changing the password (on the user profile page).

**Comment by thi4go** [comment]
Thank you for the guidelines @sndurkin ! Finishing this issue
