### ISSUE TITLE
Missing ui feedback for faucet

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#1150]
The payments done using faucet are not providing any UI feedback. Would be ideal to provide feedback with the link to access the transaction details in testnet.dcrdata.org.

**Comment by amassarwi** [comment]
This seem to be fixed, right ?
![image](https://user-images.githubusercontent.com/10324528/63614872-56252100-c5e4-11e9-80e9-17628fea8be5.png)

**Comment by fernandoabolafio** [comment]
@amassarwi the screenshot you posted is from the faucet website. This issue refers to some actions inside the politeiagui where you're able to pay using faucet while running on testnet mode. 
Anyway, this issue has been handled in the redesign already so I am closing it.
