### ISSUE TITLE
[cms] Preload invoice information

### ISSUE THREAD

**Issue by alexlyp** [decred/politeiagui#1153]
From @matheusd on matrix:

> Going through the menu link "Submit New Invoice" should ideally pre-load the data for billing the last month. It would be helpful to also be able to pre-specify the name, location, etc

We could probably fetch the most recent invoice and then populate the corresponding fields.  Not sure if we would need an extra endpoint to accomplish this, maybe we could sort the already returned user invoices.

**Comment by thi4go** [comment]
I'd like to work on this

**Comment by alexlyp** [comment]
I'd hold off on this in lieu of the upcoming changes/additions of user information piwww.  We should then just be able to request the user information directly to be put in there.

**Comment by xaur** [comment]
As a more general form of this feature, consider "Copy from" feature that allows to initialize the invoice form from an arbitrary past invoice.
