### ISSUE TITLE
[cms] Add way to import csv into line items

### ISSUE THREAD

**Issue by matheusd** [decred/politeiagui#1157]
I already have software that I use to track billing and generate invoices. Ideally, the invoice UI could offer a way to import a csv with the line item data so that I don't have to manually enter it.

**Comment by fernandoabolafio** [comment]
@matheusd while I think this wanted feature to have. For now, the datasheet component allows you to copy/paste the entire data from your external invoice if it's already formatted in the proper format.

**Comment by matheusd** [comment]
Ah, didn't realize it allowed that, thanks!

**Comment by tiagoalvesdulce** [comment]
I'm closing this issue because csv pasting works fine for our needs.
