### ISSUE TITLE
[cms] Home message doesn't update after invoice submission 

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#1162]
The message "ℹ︎You have not yet submitted your invoice for this month." appears when you have not submitted an invoice for the current month, however, this needs to be switched to the previous month since invoices cannot be submitted for the current month.

**Edit:** All messages from the index page needs to be reviewed considering what's mentioned above.

**Comment by degeri** [comment]
Also be aware of the same issues with years.
Example: For 01/2020 we have to check if a submission was made on 12/[2020-1]2019
