### ISSUE TITLE
[cms] UI suggestion : larger description box, multiline for description and ability to save draft

### ISSUE THREAD

**Issue by Guang168** [decred/politeiagui#1173]
1. larger box for description
2. allow entering multiline for description
3. ability to save draft and submit later - i have this error and not able to submit and need to reenter everything when i refresh / logout.

**Comment by camus-code** [comment]
Working on this one

**Comment by xaur** [comment]
+100 for the draft feature. I lost entered data several times due to UI crash. Even without bugs, authoring an invoice could span several sessions.

Draft feature deserves its own issue btw.
