### ISSUE TITLE
Loading text on proposal list view

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#1179]
See image.

<img width="1289" alt="Screen Shot 2019-05-09 at 12 36 31 PM" src="https://user-images.githubusercontent.com/9039877/57470694-71e40180-7257-11e9-9d48-7782a20bcf3f.png">

**Comment by camus-code** [comment]
working on this

**Comment by camus-code** [comment]
@lukebp how does this look for the loading screen? It just uses "Public Proposals" + the proposal tabs as the fallback UI until the count and proposals have loaded.

Also, you can see in this gif that the login form on the sidebar flashes even though I'm already signed in. Should I file a separate issue for that?

![May-09-2019 12-27-11](https://user-images.githubusercontent.com/42082827/57473793-46ace280-7256-11e9-9976-71b0025799ac.gif)

**Comment by lukebp** [comment]
I like that.  @fernandoabolafio thoughts?
