### ISSUE TITLE
Blocks left metric missing

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#1187]
The number of blocks left before the end of the proposal vote is not showing up on test-proposals.

<img width="1169" alt="Screen Shot 2019-05-13 at 9 02 02 AM" src="https://user-images.githubusercontent.com/9039877/57623588-07380c00-755e-11e9-95f6-78c3248c920f.png">

**Comment by lukebp** [comment]
This bug is still present on the production site.

**Comment by camus-code** [comment]
hey @lukebp, I went to work on this one but perhaps I'm missing something? It's showing up fine on my local environment. I'm also seeing the block height metric on the production site as well (screenshot below). 

<img width="1276" alt="Screen Shot 2019-05-28 at 4 36 04 PM" src="https://user-images.githubusercontent.com/42082827/58514792-820d4380-8168-11e9-9496-ddc3946d8c93.png">

**Comment by lukebp** [comment]
You're right.  My "Privacy Badger" extension was blocking the request to dcrdata.  That seems odd though for a simple api request and it just started happening with this most recent update.  Did anything recently change with the dcrdata best block request?

**Comment by camus-code** [comment]
Hm that is very strange. I'm going through commit history now but I don't remember anything that would've introduced this bug -- Going to keep looking though.

I think the suggestion of supplying the block height info directly from the backend would probably be better in the long-run though, since I'm sure you aren't the only one who will run into an issue like this

**Comment by lukebp** [comment]
Looks like the best way to handle this is to have the best block returned in the politeia api response so that the gui doesn't have to fetch it from dcrdata.  I'll open a backend issue and then when the backend work is done we'll open a new frontend issue to remove the dcrdata calls.

This issue can be closed.

**Comment by camus-code** [comment]
Okay cool sounds good. I'd close the issue but those powers have not yet been delegated to me lol
