### ISSUE TITLE
[cms] Odd unicode characters being inserted

### ISSUE THREAD

**Issue by alexlyp** [decred/politeiagui#1190]
A user on macOS has reported that line item descriptions were complaining of being malformed:

![image](https://user-images.githubusercontent.com/4388501/57645951-79741500-758d-11e9-96d2-4335d3baa900.png)

Is whole the text that was copied, but when seeing it in it's raw form:

`1	Design	visual comms	saender,Â dcr journal renders for april, may`

`1	Design	dcrweb	30000fps,Â dcrweb new header renders`

Some how this rogue `Â` is being added.

**Comment by fernandoabolafio** [comment]
I did some investigation on it and found this which looks related to this problem:

```
A problem you will inevitably face is when a user takes advantage of another application to create some text which gets pasted into your HTML form and submitted. Microsoft Word, for example, uses Unicode internally and converts characters like quotes and dashes into “smart quotes” and em- and en-dashes automatically. These are typographically correct, but the symbols lie outside the ASCII character set so when copied and pasted, the text is sent as UTF-8 and you end up with multibyte characters all over the place. If you store this text and later send it back to a browser without informing it that you are sending UTF-8, extra characters will appear.
```

However, I couldn't yet reproduce it. What editor software the text was originally copied from?

**Comment by camus-code** [comment]
Have tried to reproduce this one a few times as well and still no luck. Do you remember what user it was / what text editor they were using @alexlyp ?
