### ISSUE TITLE
[cms] /user/resend error

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#1197]
When my verification token expired, I pressed the resend button and got this:

> The server encountered an unexpected error, please contact Politeia administrators and include the following error code: <unix timestamp>

It could be a more user friendly message explaining what went wrong.

**Comment by alexlyp** [comment]
Not sure there should be a resend button shown to the end user.  That is why you are getting an error (it's an admin path in Politeia)

**Comment by xaur** [comment]
Oh that makes sense. I saw it somehow on Apr 13 when I was registering.

**Comment by xaur** [comment]
Related: when I load the login page there is a quick flash of the "Resend verification email" button. Might be the same bug as #1200 

![cms-resend-button-2](https://user-images.githubusercontent.com/24484727/57731162-9726a480-7689-11e9-9607-67d8542662b0.png)

and then it changes to

![cms-resend-button-3](https://user-images.githubusercontent.com/24484727/57731171-9beb5880-7689-11e9-98d8-9b70cc065dc7.png)

**Comment by camus-code** [comment]
Good catch on this one. As for the related issue you brought up, it was indeed related to #1200. As we talked about earlier, this will be fully resolved once #1234 is deployed
