### ISSUE TITLE
[cms] No prompt to backup identity

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#1198]
IIRC when I first logged in there was no huge red alarm telling me to backup my identity.

**Comment by fernandoabolafio** [comment]
@xaur the prompt will only appear if you have an invalid identity. If the identity saved in your browser is valid, the prompt should not appear as expected.

**Comment by xaur** [comment]
Yes I get a red prompt for invalid identity as expected. What I refer to in this issue is there is I didn't notice a warning to _backup_ a valid identity. I remember there was such a thing in Politeia.

**Comment by fernandoabolafio** [comment]
No, we never had a "huge red alarm" to alert about key backup. I will close this issue but feel free to validate if others also think the "key backup warning" is something wanted. If it is, I would suggest you reach the redesign [master issue](https://github.com/decred/dcrdesign/issues/77) and request to include it in the new design resources.
