### ISSUE TITLE
[cms] Import identity: rename submit button

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#1199]
"SUBMIT IDENTITY" is misleading as it suggests that private key is sent to server.

**Comment by s-ben** [comment]
Is this issue still in play? Thinking about tweeting it out on the [Good First Issue](https://twitter.com/dcrgoodfirst) acct.

**Comment by CodingApps** [comment]
Hi, I'd like to assist with the button. What do you want it renamed to? Also, which directory is file in?

**Comment by xaur** [comment]
I would call it "Import" and make it clear in the UI that it is stored in browser's local storage and is not sent to the server. Can't help with file location sorry.

**Comment by CodingApps** [comment]
Hi @xaur  , could you send me an invite token to codingkit@gmail.com so I can look at the CMS button UI ?

**Comment by xaur** [comment]
@CodingApps sorry I don't have such powers. I guess maintainers of this repo could send you an invite to a test instance. Otherwise you can spin up your own.
