### ISSUE TITLE
[cms] Quick flash of Politeia UI before redirect to login

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#1200]
When I open https://cms.decred.org/ I see a brief flash of Politeia UI before being redirected to the login page. Looks similar to bug #837.

![cms-pi-flash-1](https://user-images.githubusercontent.com/24484727/57730905-04860580-7689-11e9-8782-bcd717e8cfdf.png)

![cms-pi-flash-2](https://user-images.githubusercontent.com/24484727/57730918-094ab980-7689-11e9-8182-ef338581e8f1.png)

![cms-pi-flash-3](https://user-images.githubusercontent.com/24484727/57730925-0c45aa00-7689-11e9-9ef1-3560b4b19845.png)

**Comment by camus-code** [comment]
@xaur good catch. I wasn't aware of this issue being opened when I pushed #1234, but that PR addresses this issue as well. I pinged Fernando so that he can take a look as well.

**Comment by xaur** [comment]
Just tested, still seeing a flash of the right sidebar.

**Comment by camus-code** [comment]
Hmm did you test the actual pull request or on cms.decred.org? Because it hasn't been pushed to production yet.

Trying to recreate the flashing of the sidebar on my end and I'm not seeing anything

![page-reload](https://user-images.githubusercontent.com/42082827/58513550-52107100-8165-11e9-8d9d-086753c563b7.gif)

**Comment by xaur** [comment]
I tested cms.decred.org, don't have the setup to test locally. Will wait for deployment then, thanks.

**Comment by camus-code** [comment]
Ah okay no worries, just wanted to make sure. Well yeah this issue will be resolved once #1234 is deployed.

**Comment by camus-code** [comment]
@xaur you can close out this issue. It's been resolved
