### ISSUE TITLE
[cms] Duplicate account properties

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#1201]
"Verified email" and "Locked" are shown twice in Account/General.

![cms-duplicate-account-properties](https://user-images.githubusercontent.com/24484727/57730997-3ac38500-7689-11e9-815b-926173f9f2d7.png)

**Comment by camus-code** [comment]
Fixing this one up now. I'm only seeing a duplicate property for "Locked" @xaur, could you double check that "Verified Email" is indeed duplicated whenever you get a chance?

**Comment by xaur** [comment]
@camus-code first "Verified email" gone, only one now. "Locked" is still duplicated.

**Comment by camus-code** [comment]
Ok thanks for checking @xaur
