### ISSUE TITLE
[cms] Submit Invoice UI suggestions

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#1202]
* name/location/... field labels are too small, make them same size and font like other text
* remove italics from field descriptions (they are already bold)
* rename "Add/Remove Row" to "Add/Remove Item" for terminology consistency with "line item"
* make "Add Row" same green color as "Attach a file" button (green is often used to signal "add")
* add instructions how to obtain proposal token
* explain which characters are allowed and not allwed in fields
* make Location field optional
* show uneditable column that computes USD value for line items
* show Total USD value
* show "4 - April" or "(4) April" instead of just "4" for month
* Description cell is too small for "thorough description", which implies multiline text
* add note that line items can be copied and pasted from LibreOffice, given enough rows in the invoice
* vertically align cell text to Top

**Comment by amassarwi** [comment]
@xaur I believe all were addressed in the redesign work, found tiny one that we still could add:

> rename "Add/Remove Row" to "Add/Remove Item" for terminology consistency with "line item"
