### ISSUE TITLE
[cms] Logout error You must be logged in to perform this action

### ISSUE THREAD

**Issue by raedah** [decred/politeiagui#1204]
I am unable to logout, because I am not logged in. Unfortunately, I cant login either, because I cant logout.

**Comment by raedah** [comment]
It seems likely the cause of only parts of the system seeing me as not logged in may be due to having created a new identity key after my first one was lost from the browser cache. The problem may be caused by my account using a second identity key.

I am also seeing 
"Failed to fetch exchange rate
Error: You must be logged in to perform this action."

**Comment by fernandoabolafio** [comment]
@raedah thanks for reporting that. We will investigate it and provide a fix as soon as possible. In the meanwhile, you can try clearing your browser cache data (local storage + cookies). Just be aware that **if you clear all your browser data and you don't have a backup of your identity** you will need to generate a new once you log in. 
If you don't have a backup and neither want to generate a new identity, is preferable to clear **only your local storage and the cookies**. The identity lives in the IndexedDB, so if you don't clear it, your identity is safe.
