### ISSUE TITLE
[cms] Prevent non-cms requests

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#1210]
While running politeiagui in the CMS mode a few requests from the proposal's site are being triggered:

- user invoices page:
    - `proposals?userid=invoices` 
    - `proposals/votestatus`
- invoice detail page:
    - `commentslikes` 
- user detail (account) page:
   - `proposals?userid=dd288a5d-2d89-4804-ae03-776eabbbc216`

**Comment by camus-code** [comment]
Working on this one. I think it's related to #1217 as well
