### ISSUE TITLE
[cms] Add line item subtotal column

### ISSUE THREAD

**Issue by alexlyp** [decred/politeiagui#1213]
There should be an additional column added to line items that shows the subtotal of that line.

For labor line items it should use the contractor rate multiplied by the hours in the cell to the left.

For expense/misc it should simply be the expenses value copied there.

Then at the bottom the sum of the subtotals should be shown next to the other 2 column totals currently shown.

**Comment by alexlyp** [comment]
Ideally this subtotals cell (and total) should autopopulate for the user upon labor or expense cell entry.

**Comment by thi4go** [comment]
Working on this! :+1:
