### ISSUE TITLE
[cms] Requested page not found error flashing

### ISSUE THREAD

**Issue by alexlyp** [decred/politeiagui#1217]
Sometimes when an admin clicks on an invoice to view its details (final URL being cms.decred.org/invoices/<token>), an error modal flashes and then goes away once the invoice information displays.

The error message appears to be something about "requested page does not exist"

**Comment by alexlyp** [comment]
I've successfully been able to reproduce this issue (though not on simple link clicking).

If you go to any /invoices/<token> page then hard reload, you'll see in the piwww logs that it first requests proposals/<token>

This would explain the error being flashed.  But no clue why it would try that endpoint first, maybe something in a connector that is fetching the proposal info before it "knows" that it is in CMS mode?

**Comment by camus-code** [comment]
Working on #1210 which should solve this one as well. You're right about the delay of it "knowing" whenever it is in CMS mode.

https://github.com/decred/politeiagui/blob/bb6ec9baf93b9051c3871659194ecf020788bdf4/src/selectors/api.js#L694

You can check here for yourself but `mode(state)` is being called before while the apiInitResponse is still being fetched

**Comment by fernandoabolafio** [comment]
closed on #1234
