### ISSUE TITLE
Proposal quorum tooltip

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#1225]
Not sure what this tooltip is suppose to be showing, but its definitely not correct.

<img width="579" alt="Screen Shot 2019-05-22 at 4 29 06 PM" src="https://user-images.githubusercontent.com/9039877/58206566-e59df980-7cae-11e9-90e9-aad1656d9d19.png">

**Comment by victorgcramos** [comment]
Hey @lukebp! I guess this means the voting percentage necessary to reach the minimum quorum. This is valid to display, as long as we explain what does it mean.

A better wording should fix the problem, in my opinion. I was thinking of something like:
> 1.37% of 20% necessary to reach the minimum quorum

What do you think? @fernandoabolafio @thi4go @camus-code
