### ISSUE TITLE
[cms] Signup error with blank error

### ISSUE THREAD

**Issue by alexlyp** [decred/politeiagui#1227]
A user reported seeing a Signup Error but with no error body upon attempt to complete the CMS registration form.  Attempts to replicate this issue have proven unfruitful and an admin was able to successfully register their account locally.  

This was reported on Mac + Chrome.

**Comment by camus-code** [comment]
Have you been able to reproduce this one @alexlyp ? I've tried quite a few times on my Mac + Chrome (plus a lot of other browsers), but I still can't replicate a blank signup error.
