### ISSUE TITLE
Proposal details page inefficiencies

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#1230]
I'm seeing some inefficiencies on the proposal details page that could be improved.

1. There are duplicate policy requests.
2. The policy, vote status, and comments requests only get sent after the proposal details request has returned (and it looks like its also waiting for some post processing to be completed as well).  Is there a reason for this?  You could cut the total load time in half if you fired off these requests concurrently.

<img width="1033" alt="Screen Shot 2019-05-24 at 4 07 19 PM" src="https://user-images.githubusercontent.com/9039877/58354139-8838b280-7e3e-11e9-99ae-314a2d5dbf5a.png">

**Comment by fernandoabolafio** [comment]
The proposal vote status needs to be fetched after the proposal detail because if the proposal is not public the API will return an error response. 
Policy and comments can be fetched concurrently I believe.

**Comment by lukebp** [comment]
What about fetching the proposal details and vote results at the same time, then just discarding the vote results error if it turns out that the proposal is not public?

**Comment by fernandoabolafio** [comment]
Yeah, that should work but we need to make sure the error we got is specifically about fetching the vote status for a public proposal, any other error must be shown.

**Comment by camus-code** [comment]
I'll pick this one up

**Comment by fernandoabolafio** [comment]
Addressed on politeiagui redesign. Feel free to re-open it if you find something is missing.
