### ISSUE TITLE
Allow draft submission with incomplete fields

### ISSUE THREAD

**Issue by camus-code** [decred/politeiagui#1232]
Currently, our redux-form validation prevents form submission whenever there are any errors. This means that users cannot save a proposal or invoice draft unless they have all the required fields filled in.

Users should be able to save drafts with as little information provided as they wish

**Comment by thi4go** [comment]
Working on this!

**Comment by fernandoabolafio** [comment]
Addressed on v2. We won't be adding this for the old version.
