### ISSUE TITLE
Cannot submit proposal after image error

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#1238]
I am not able to submit a proposal after I receive an "image exceeds the maximum size"  error.
There are multiple errors here:

How to reproduce:
- Go to the submit proposal route
- Attach a file larger enough to receive the error message. (Ps: at the moment the image is selected the client validation occurs successfully displaying an error message  at the top of the attachment area but the 'submit' button is not disabled)
- Submit the proposal
- The client validation occurs again but now displaying the error message at the top of the page. 
- Now the 'submit' button is disabled and even if I remove the errored file it doesn't return to the enabled state.

We need to make sure:
1. Client-side validation occurs at the form filling time, no need to wait for the user pressing the 'submit' button.
2. Errors are not duplicated in two areas of the screen.

**Comment by victorgcramos** [comment]
Good caught, @fernandoabolafio! Let me take this!
