### ISSUE TITLE
Validation errors if all rows are removed (soft UX crash) [CMS]

### ISSUE THREAD

**Issue by degeri** [decred/politeiagui#1250]
To reproduce

Go to: https://cms.decred.org/invoices/new

scroll down click on "Add Row" then give "Remove Row" this will change  "Display 5 validation errors" to "Display 42 validation errors" if you click on the "Display 42 validation errors" the page blanks out.

Here is the console error. 

`TypeError: "t.map is not a function"
    b InvoiceDatasheetField.js:32
    Zi 2.ecd2212c.chunk.js:1
    Co 2.ecd2212c.chunk.js:1
    Ro 2.ecd2212c.chunk.js:1
    $a 2.ecd2212c.chunk.js:1
    Ka 2.ecd2212c.chunk.js:1
    Ts 2.ecd2212c.chunk.js:1
    Cs 2.ecd2212c.chunk.js:1
    Ns 2.ecd2212c.chunk.js:1
    On 2.ecd2212c.chunk.js:1
2.ecd2212c.chunk.js:1:770541
    da https://cms.decred.org/static/js/2.ecd2212c.chunk.js:1
    callback https://cms.decred.org/static/js/2.ecd2212c.chunk.js:1
    ia https://cms.decred.org/static/js/2.ecd2212c.chunk.js:1
    ra https://cms.decred.org/static/js/2.ecd2212c.chunk.js:1
    qa https://cms.decred.org/static/js/2.ecd2212c.chunk.js:1
    Ha https://cms.decred.org/static/js/2.ecd2212c.chunk.js:1
    Ps https://cms.decred.org/static/js/2.ecd2212c.chunk.js:1
    unstable_runWithPriority https://cms.decred.org/static/js/2.ecd2212c.chunk.js:1
    Ps https://cms.decred.org/static/js/2.ecd2212c.chunk.js:1
    Ts https://cms.decred.org/static/js/2.ecd2212c.chunk.js:1
    Cs https://cms.decred.org/static/js/2.ecd2212c.chunk.js:1
    Ns https://cms.decred.org/static/js/2.ecd2212c.chunk.js:1
    On https://cms.decred.org/static/js/2.ecd2212c.chunk.js:1
TypeError: t.map is not a function InvoiceDatasheetField.js:32:20`

![image](https://user-images.githubusercontent.com/41839293/58747256-33241e80-8486-11e9-8df4-83ce9a96d8a3.png)

**Comment by camus-code** [comment]
Great catch @degeri . It appears the error message "lineitems field must have at least 1 items" is not being added to the errors array, hence why it's displaying 42 error messages (number of characters in this error), and why the .map function is causing a UX crash

Working on this one
