### ISSUE TITLE
[cms] Improve UX in the description editor

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#1258]
Right now is really hard to type longer texts in the description field. A few things that I noticed to be improved:
- Allow adding a line break by pressing `shift + enter`
- Allow moving cursors across lines using the arrow keys
- Make the editor resize as the text grows
- In summary, only blur the editor once the user hits either just `enter` or just `tab`.

**Comment by camus-code** [comment]
Working on this one. 

@fernandoabolafio should this UX improvement also be applied to the proposal token since it's a multi-line editor? or should we keep that as is since most users will simply be copy + pasting the token?
