### ISSUE TITLE
Remove Validation Errors from State upon Image Removal

### ISSUE THREAD

**Issue by camus-code** [decred/politeiagui#1267]
Errors are not being cleared from the state whenever the user removes the image(s) in question. 

This is a visual bug only as it does not actually prevent the user from submitting, but the errors should be updated upon image uploading AND removal

**Comment by thi4go** [comment]
fixing this

**Comment by thi4go** [comment]
This is sort of duplicate issue from #1238, and PR https://github.com/decred/politeiagui/pull/1265 fixes this. You can close it @camus-code

**Comment by camus-code** [comment]
Ok cool. I had brought this issue up in terms of #1238, wasn't too clear if this issue was fixed. Thanks for clarification @thi4go
