### ISSUE TITLE
[cms] Submit button disabled in Draft invoice

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#1269]
What I did:

1. Create invoice and fill all fields correctly
2. Save as Draft
  * redirected to Drafts page - suboptimal UX, what if I didn't want to leave the invoice?
3. Open the draft
4. Submit button is gray and unclickable

To work-around, I re-selected the month and it became active again and I submitted successfully.

**Comment by camus-code** [comment]
good catch @xaur. Just pushed a PR to fix the disabled submit button. 

Was playing around with the UX issue you mentioned as well. I think that warrants its own issue to be honest, as I believe the change might be a little more work than fits in this issue. (Not to mention this UX issue is present on politeia as well as CMS].

You can go ahead and file that issue if you'd like

**Comment by xaur** [comment]
Sure #1273
