### ISSUE TITLE
[pi/cms] Submit form crash when inputting invalid characters

### ISSUE THREAD

**Issue by thi4go** [decred/politeiagui#1278]
The form is crashing when inputting invalid characters in a sequence. Happens both in cms and pi.

![crash](https://user-images.githubusercontent.com/2729122/59708102-7991b100-91da-11e9-834e-b2f22340288e.gif)

**Comment by victorgcramos** [comment]
I could only get this error on Pi... Are you sure it happens on CMS @thi4go?

**Comment by thi4go** [comment]
You're right mate, happening only on Pi. Reviewing the PR now :+1:
