### ISSUE TITLE
[cms] Remove month/year from EditInvoice

### ISSUE THREAD

**Issue by alexlyp** [decred/politeiagui#1283]
https://github.com/decred/politeia/pull/924

After this PR users are no longer able to edit month/year of invoices, so those should be not be changeable in the GUI form.

**Comment by thi4go** [comment]
On this

**Comment by alexlyp** [comment]
it's already completed. ^^ There is the PR above

**Comment by thi4go** [comment]
Woops completely passed it by hahaha thanks for the heads up @alexlyp
