### ISSUE TITLE
[cms] Error on admin logout

### ISSUE THREAD

**Issue by alexlyp** [decred/politeiagui#1287]
When logging out as an admin (may happen on a regular account too), looks like the logout successfully occurs.  But an error is being shown to me "Error fetching invoices.  You must be logged in to perform this action."  It is on the base URL when showing that error.

**Comment by victorgcramos** [comment]
It looks like a race condition on the logout method. Working on this!

**Comment by sambiohazard** [comment]
i had the exact same issue on a non-admin account. Screenshot below.
![image](https://user-images.githubusercontent.com/42676388/60761401-330ad600-a065-11e9-8085-df9189a611e1.png)
