### ISSUE TITLE
Remove dcrdata best block request

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#1288]
Privacy Badger has been flagging dcrdata as a tracker.  decred/politeia#928 added the best block to the vote status response so that the gui doesn't have to pull the best block from dcrdata.

**Comment by camus-code** [comment]
Sorry forgot to comment. Picked this one up

**Comment by lukebp** [comment]
This also needs to be incorporated into the redesign gui.

**Comment by fernandoabolafio** [comment]
Already addressed for redesign GUI. We're leaving the old version as it is for now.
