### ISSUE TITLE
[Redesign] Add "No ... tickets" text to the pages with no tickets to show

### ISSUE THREAD

**Issue by tiagoalvesdulce** [decred/politeiagui#1307]
Add "No ... tickets" text to the pages with no tickets to show
![image](https://user-images.githubusercontent.com/8841018/61380841-cab4c380-a8b2-11e9-8812-d4a39cff2d86.png)

Example (16px, Regular, #596D81): 
![image](https://user-images.githubusercontent.com/8841018/61380931-f172fa00-a8b2-11e9-828e-d65b98b6b926.png)

_Originally posted by @MariaPleshkova in https://github.com/decred/politeiagui/pull/1304#issuecomment-512272256_

**Comment by victorgcramos** [comment]
on this!
