### ISSUE TITLE
[redesign] Display a loading indicator before starting to fetch the proposals

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#1308]
We need a loading indicator while the proposals lazy loading hasn't started yet (e.g while fetching the token inventory).

This issue is a continuation of a discussion in #1296. I will quote@MariaPleshkova suggestion here:

> @lukebp I think it can be solved by adding this effect of blinking gray cards once the page starts showing any content on it. I mean we can just add a few (eg 3 or 4) of these gray rectangles even before the system counts the numper of proposals. What do you think @fernandoabolafio ?

_Originally posted by @MariaPleshkova in https://github.com/decred/politeiagui/pull/1296#issuecomment-512731934_

**Comment by fernandoabolafio** [comment]
@MariaPleshkova I think it would look weird, for example, when we display 3 proposals placeholders and then the list doesn't load any proposal after all.

Perhaps we can display just a more discrete loading under the tabs. Example:
<img width="538" alt="Screen Shot 2019-07-18 at 15 30 33" src="https://user-images.githubusercontent.com/14864439/61461455-01e9aa00-a971-11e9-8092-8cf955729801.png">
And add blinking to the tabs count container, maybe?

**Comment by MariaPleshkova** [comment]
@fernandoabolafio hm, yeah, that sounds ok!

**Comment by thi4go** [comment]
Working on this!
