### ISSUE TITLE
User page: "Locked" field is displayed twice

### ISSUE THREAD

**Issue by jholdstock** [decred/politeiagui#1316]
When viewing my own user page, I see "Locked: No" twice:

![Screenshot from 2019-07-31 12-23-10](https://user-images.githubusercontent.com/6762864/62208301-50923d80-b38e-11e9-95a2-dd123c79624f.png)

**Comment by jholdstock** [comment]
I've just scanned the code and this issue actually seems like it might be fixed already in master. I will leave the issue open for a Pi dev to review, just in case.

**Comment by fernandoabolafio** [comment]
Yep, it is fixed on master already.
