### ISSUE TITLE
Provide a direct link to the voting charts

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#1318]
From the proposal page, provide a direct link to the real time charts for the proposal at
https://dcrdata.decred.org/proposals/

This is dependent on this merged PR being available on production.
decred/dcrdata#1450.

*Originally opened by @raedah at decred/politeia#965*.

**Comment by chappjc** [comment]
It's in dcrdata 5.1, up on alpha right now.  Should be released and on the main site in the next couple weeks

**Comment by raedah** [comment]
I have verified it is not functional on dcrdata production.

example: dcrdata.org/proposal/073694ed82d34b2bfff51e35220e8052ad4060899b23bc25791a9383375cae70

**Comment by chappjc** [comment]
Thanks for following up @raedah.  5.1.x dcrdata has been deployed for some time.  I forgot to circle back here.

**Comment by amassarwi** [comment]
Would like to add it when @MariaPleshkova provide some input
