### ISSUE TITLE
[redesign] Comments tweaks to match design specs

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#1319]
Based on [@MariaPleshkova comments](https://github.com/decred/politeiagui/pull/1309#issuecomment-517717485) copied from #1309:

>@fernandoabolafio well, I guess these are the last ones for this PR (but overall looks pretty good):

1. make the distance between "comments" and a number 10px
![image](https://user-images.githubusercontent.com/8841018/62374923-b83eb900-b545-11e9-9026-b24fad9c46bc.png)

2. found this issue on designs also. Change the color of the text inside the field to #091440, please. Bc it looks like it's not active at that moment, but it is
![image](https://user-images.githubusercontent.com/8841018/62375046-110e5180-b546-11e9-92e5-1766b4ae939d.png)

3. when Preview is active, I think, we can remove this field's frame and, therefore, move it a little bit to the left (to the left container border). And in this case change the color to #596D81. (sorry for that again)
![image](https://user-images.githubusercontent.com/8841018/62375405-e7a1f580-b546-11e9-8ec5-43902b05535f.png)

**Comment by victorgcramos** [comment]
On this!
