### ISSUE TITLE
Preferences tab is shown for another user

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#1321]
I think I should not see Preferences tab of other users

https://proposals.decred.org/user/eb486ed6-bbb3-4815-9547-599cc0f28325?tab=preferences

![prefs](https://user-images.githubusercontent.com/24484727/62421074-90f20400-b68b-11e9-838a-49176c73aa46.png)

**Comment by fernandoabolafio** [comment]
Should be fixed in the newly released version.
