### ISSUE TITLE
[redesign] Add Vertical Spacing prop to control spaces between form elements

### ISSUE THREAD

**Issue by victorgcramos** [decred/politeiagui#1324]
This Vertical Spacing prop was a suggestion from @fernandoabolafio on https://github.com/decred/politeiagui/pull/1317:
> What I thought of doing is to expose a prop in the LoginForm such as verticalSpacing which we can set a value to propagate the mentioned paddings accordingly.

As discussed with Fernando, we found out that the best way to coordinate those spaces between form elements is by having a prop that controls it.

For example, the following image describes a Vertical Spacing of 30px:

![](https://user-images.githubusercontent.com/14864439/62537953-ef68df00-b851-11e9-9bf1-9891b6b66807.png)

**Comment by amassarwi** [comment]
On it

**Comment by tiagoalvesdulce** [comment]
This should be addressed by the pi-ui spacing css variables
