### ISSUE TITLE
Creating a new proposal fails

### ISSUE THREAD

**Issue by marcopeereboom** [decred/politeiagui#133]
Here is a proposal creation:
![screen shot 2017-12-07 at 11 26 04 am](https://user-images.githubusercontent.com/4366787/33728859-7c3255b4-db41-11e7-88eb-09a1a20904f7.png)

We need key introspection in order to debug this.

**Comment by sndurkin** [comment]
@marcopeereboom, did you by any chance create another user after your initial user? @go1dfish correct me if I'm wrong but the code doesn't look like it currently supports keys for multiple email addresses.

**Comment by fernandoabolafio** [comment]
@marcopeereboom this can be closed. This has been addressed already by allowing updating the key pair and also displaying the pub key on account's page.
