### ISSUE TITLE
[redesign] Implement proposal version picker and proposal version diff

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#1342]
Implement proposal version picker and proposal version diff as per design specs.

**Comment by fernandoabolafio** [comment]
We're still waiting on the design specs from @MariaPleshkova on this one, but the feature is already being refactored by @victorgcramos.

**Comment by MariaPleshkova** [comment]
Well. These are the specs for proposal version picker: https://xd.adobe.com/spec/bdccfcfa-b9d7-4a2e-6c4d-72ec41052479-cbfd/
And preview: https://xd.adobe.com/view/5baeca8d-2cba-42e6-4441-366365b64952-2d9f/

The last version diff was designed in a little bit different way (there are 2 separate tabs: the view and a tab with changes)
![image](https://user-images.githubusercontent.com/8841018/63780348-a22bda80-c8f0-11e9-9081-66e699630f2a.png)

But I thought it's more clear when we have 1 common tab with final text and changes together (as it is on https://proposals.decred.org right now)
![image](https://user-images.githubusercontent.com/8841018/63780535-f46cfb80-c8f0-11e9-8afc-4a56a1543828.png)

So what do you think?

**Comment by fernandoabolafio** [comment]
closed on #1363
