### ISSUE TITLE
[redesign] Censor of comments

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#1343]
Implement the censor of comments as per design specs.
Needs design specs from @MariaPleshkova .

**Comment by MariaPleshkova** [comment]
This is what I ended up with:
![image](https://user-images.githubusercontent.com/8841018/63836515-5f1a4780-c982-11e9-9baa-5e7dd7a0ee36.png)
![image](https://user-images.githubusercontent.com/8841018/63836530-65a8bf00-c982-11e9-8a42-d555f0045885.png)
![image](https://user-images.githubusercontent.com/8841018/63836559-735e4480-c982-11e9-8f00-841c561d3b55.png)
![image](https://user-images.githubusercontent.com/8841018/63836986-49f1e880-c983-11e9-8fda-5934bedc6533.png)

Attaching an updated link to the specs of admin views. There you can find these screens as well (last 4).
preview: https://xd.adobe.com/view/90a9155f-0071-4e1b-78d1-e56b363473e1-e698/
spec: https://xd.adobe.com/spec/4e7eb732-a445-46b0-4f7e-4152097a10c8-384f/

**Comment by fernandoabolafio** [comment]
@MariaPleshkova the copy in the "comment censored" modal should be something like: 
"The comment has been censored! Now it will no longer be visible for other users."
Because there is no such "censored" tab for comments.

**Comment by MariaPleshkova** [comment]
@fernandoabolafio oh, right, I saw the Censored tab, but it's for censored proposals, I guess, yeah
