### ISSUE TITLE
[redesign] Highlight of new comments since last visit

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#1348]
Implement the highlight of new comments since the last visit.

**Comment by MariaPleshkova** [comment]
Ended up with gray background and a new sign
![image](https://user-images.githubusercontent.com/8841018/63921135-ef23c400-ca4a-11e9-9bf2-896fb92290aa.png)

preview: https://xd.adobe.com/view/a1603ff9-93fa-48ef-48b8-bb6b76c2ff28-d751/
spec: https://xd.adobe.com/spec/1cd5981b-67a1-4336-66b5-c77e874766fc-6ae4/
