### ISSUE TITLE
Date displayed when viewing previous proposal versions is off by one month

### ISSUE THREAD

**Issue by RichardRed0x** [decred/politeiagui#1354]
![image](https://user-images.githubusercontent.com/37707106/63949096-c105aa80-ca71-11e9-82be-bfe54cec50f6.png)

Have only checked the i2 proposal and this one but seems like all the dates are given as 07, should be 08. i.e. 2019-07-26 should be 2019-08-26

**Comment by fernandoabolafio** [comment]
Should be fixed in the newly released version
