### ISSUE TITLE
External link warning modal prevents all input on mobile Safari

### ISSUE THREAD

**Issue by sefbkn** [decred/politeiagui#1355]
When clicking an external link on iOS safari, the warning modal renders behind the modal background. The user should be able to click "Proceed" or "Cancel".

![image](https://user-images.githubusercontent.com/4587690/63949689-c7cbf780-ca48-11e9-8245-697cb2303eb6.png)

**Comment by fernandoabolafio** [comment]
Should be fixed in the newly released version.
