### ISSUE TITLE
[redesign] Use batch vote summary route

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#1357]
The `AllVoteStatus` and `VoteStatus` routes are being deprecated and replaced by the `BatchVoteSummary` route (decred/politeia#967).

The gui will need to replace any `AllVoteStatus` and `VoteStatus` calls with a `BatchVoteSummary` call.

**Comment by amassarwi** [comment]
Would like to work on it next...

**Comment by lukebp** [comment]
Just fyi, these calls not being batched are causing dcrdata to hit its rate limit.  Each time a proposal tab is loaded it results in 5 dcrdata best block calls on the backend since the vote statuses are being fetched individually.  Let's try and get this fixed asap.
