### ISSUE TITLE
[redesign] Start vote modal causes the screen to shake a little

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#1358]
@MariaPleshkova found this issue which its happening for chrome on windows, 1920x1080
![555](https://user-images.githubusercontent.com/8841018/64009271-3760e600-cb20-11e9-88ff-df9bf499a804.gif)

**Comment by amassarwi** [comment]
@fernandoabolafio I think it's related to the scroll block - your improvement should improve this as well

**Comment by fernandoabolafio** [comment]
closed with #1404
