### ISSUE TITLE
Unexpected "session expired" message

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#1361]
Noticing this for couple weeks now

- open proposals.decred.org after the session has expired
  - => "Log in or sign up" in top right corner suggests I'm logged out as expected
- click on any proposal
  - => top right corner suddenly shows my name, a red "session expired" top banner shows up, and after couple seconds (and a _ton_ of burned CPU cycles?) the login popup is shown

**Comment by fernandoabolafio** [comment]
Should be fixed on the newly released version.
