### ISSUE TITLE
[redesign] Move comments "censor" button for mobile

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#1367]
As @MariaPleshkova suggested:

@fernandoabolafio I suggest to do it this way on mobile
![image](https://user-images.githubusercontent.com/8841018/64318432-b9d72300-cfc2-11e9-8d10-d7066d17a991.png)
It's better not to put Censor button close to Reply

**Comment by amassarwi** [comment]
would like to implement this change
