### ISSUE TITLE
Display which version of a proposal a comment was made on

### ISSUE THREAD

**Issue by jzbz** [decred/politeiagui#1370]
It occurs to me it would be handy to have an indication of what version of a proposal a comment was made on.
Displaying info like:
```
<user> <points> <time> <prop-version>
```
It makes it easier for comments to be considered in context. E.g., if a proposal has its cost updated to reflect stakeholder feedback a comment saying "this seems really expensive" becomes potentially misleading and may not reflect the submitter's feelings about the current state of the proposal.

**Comment by linnutee** [comment]
@MariaPleshkova could address this one in the new designs as well. Regarding the positioning and visual design, the sensible placement would likely be by the time indicator. Can discuss some specifics on matrix also if needed.

However, do see this creating two potential issues also. Firstly if the prop version is always visible and repeated on every comment, this creates bloat. Secondly, afaik there is not an easy way to view what the previous proposal contained (or switch between several proposals), so improving the accessibility for this should be addressed also. 

To solve the first bloat issue, displaying the <prop-versions> could only happen IF there is a mismatch between the current proposal version and the proposal version at the time the comment was made. 

Second case could be solved through a somewhat similar interaction pattern to how Gh does edited comments. Perhaps also design some interaction via the comments tagging, so the UI would either filter or highlight the context of a specific version. (ie. clicking on a version on comments highlights all same version comments).

**Comment by fernandoabolafio** [comment]
First of all, we cannot implement this on politeiagui without previous work on the politeia backend. The comment data doesn't contain in which version it was written. That said we need @lukebp to drop his thoughts on this matter. 

@linnutee regarding this:
> Secondly, afaik there is not an easy way to view what the previous proposal contained (or switch between several proposals), so improving the accessibility for this should be addressed also.

We do have a proposal version viewer in the politeiagui and we're currently working on implementing a new one for the redesigned pigui as per specs from @MariaPleshkova: https://xd.adobe.com/view/5baeca8d-2cba-42e6-4441-366365b64952-2d9f/.
The PR for that is almost ready to go in: https://github.com/decred/politeiagui/pull/1363.

**Comment by MariaPleshkova** [comment]
Well, if we still gonna implement this, I'd agree with above comments about positioning by the time indicator. Like this:
![image](https://user-images.githubusercontent.com/8841018/64642673-8f98c180-d417-11e9-99b5-1db0e4557b44.png)


I also think that it would be great to open an appropriate version when clicking on it (the same as when clicking on a proposal version in a proposal itself). But the idea @linnutee suggested

> clicking on a version on comments highlights all same version comments

also sounds cool. So maybe we can add smth like a small modal as hover effect on a proposal version with, for example, 

- See all the same version comments 

- See version n

options.

**Comment by lukebp** [comment]
We're going to move forward with this.  There is some backend work that needs to be done before the frontend can be implemented.  I'll be opening issues for that work shortly.

@MariaPleshkova one thing to keep in mind with this design is that we'll also be allowing comments to be edited in the future.  There will need to be some sort of drop down menu that allows the user to view old versions of the comment, similar to how you can view old versions of a proposal.  Just wanted to make sure you're aware of this in case it conflicts with what you were thinking.

**Comment by xaur** [comment]
This was requested in https://github.com/decred/politeia/issues/534 and on [Reddit](https://www.reddit.com/r/decred/comments/emgubs/decred_journal_december_2019/fdxkp62/).

**Comment by xaur** [comment]
Ditto's [phase 3](https://proposals.decred.org/proposals/012b4e335f25704e28ef196d650316dca421f730225d39e37b31b3c646eb8497) proposal shows a good use case for the feature requested in this issue. The proposal received a lot of thoughtful comments and was substantially modified in response. Now it is a bit confusing to read the comments made before the large edit without visual clues to what version the comment was made for.

**Comment by lukebp** [comment]
@xaur we plan on doing that.  It requires some backend changes first: decred/politeia#1099.

**Comment by lukebp** [comment]
There was some discussion about this today in the proposals matrix channel.

https://matrix.to/#/!MIGqWXfLFBwhipPKYL:decred.org/$15793965341843UuAUW:decred.org?via=decred.org&via=matrix.org&via=zettaport.com

**Comment by lukebp** [comment]
Moving this issue to the feature request thread (#2578).  This is still blocked by backend changes.  We can add this to the next pi proposals.
