### ISSUE TITLE
Improve the preview of a proposal + change the style of "Save as draft" button

### ISSUE THREAD

**Issue by MariaPleshkova** [decred/politeiagui#1389]
Remove this text frame when choosing the Preview. Add a horizontal line instead + another button style for Save as draft

Implementation:
![image](https://user-images.githubusercontent.com/8841018/64708357-2b303d80-d4bd-11e9-8df3-1cc3c71a41c2.png)

Specs:
![image](https://user-images.githubusercontent.com/8841018/64708516-63d01700-d4bd-11e9-96bb-bf097c73ad38.png)

**Comment by fernandoabolafio** [comment]
@thi4go I think we would benefit from changing the button component (in the pi-ui lib). We currently have 3 button "styles":  
   - primary
   - secondary
   - disable

I think we could make the button with background white and color blue the secondary and add another style (for example "no-borders") which is like the "secondary" but has no borders.
The other option would be just tweak it on politeiagui. Anyway we need to define what should be the default for the secondary style. What do you think?

**Comment by fernandoabolafio** [comment]
The button for "submit draft" is already fixed because of the latest changes on pi-ui. The remaining tweak for the horizonal-bottom bar I am adding to a misc PR I'm about to push.
