### ISSUE TITLE
[redesign] Small tweak of the Formatting help modal

### ISSUE THREAD

**Issue by MariaPleshkova** [decred/politeiagui#1390]
Make the content of each and every line in these 2 columns center aligned:
![image](https://user-images.githubusercontent.com/8841018/64708703-b4e00b00-d4bd-11e9-95b2-fde59a8f2bad.png)

**Comment by thi4go** [comment]
Hey guys, I had some trouble getting this alignment right for some reason, so I decided to focus on working on some more bigger issues for now. If we can relocate this one would be great, or I can get back to it once I'm done. Just letting everyone know.
