### ISSUE TITLE
Fix the problem with 2 separate similar My proposals pages + Change the name to My proposals instead of Your proposals

### ISSUE THREAD

**Issue by MariaPleshkova** [decred/politeiagui#1392]
It's confusing that the same page is called differently. 
![image](https://user-images.githubusercontent.com/8841018/64709058-46e81380-d4be-11e9-8c5a-cef4e5f94171.png)

Let's go for "My proposals" in both cases. 

One more problem with My proposals is that there are 2 almost similar pages with the same functionality, but they both can be reached with 2 different ways: from this dropdown OR under Proposals tab in Account. I guess it happened accidently and suggest to remove the tab Proposals from Account and to leave only My proposals in this dropdown. This way it's easier to reach it + there's Draft tab in My proposals unlike Proposals tab.

**Comment by fernandoabolafio** [comment]
@MariaPleshkova they aren't the same thing. "My proposals" page is accessible only reachable for the authenticated user where he can see all proposals submitted by him. While the proposals tab in  Account is meant to be accessible by any user browsing through the user account. 
That said, I agree the title of the page should be "My proposals" but I don't think we need to remove the proposals tab under Account yet. What I think we need to do is review the way we're handling account x profile. Currently what is very confusing that we have all in the same place. The way I see account should be a place for the user to manage his settings (and admins ?) and the profile to be a presentational page only. What do you think?

**Comment by victorgcramos** [comment]
I want to add my thoughts on this topic if you don't mind. I think that the page `/proposals/user` can be replaced by adding the "draft" view to user proposals public page (`/user/<id>?tab=proposals`), and using the `My Proposals` item to redirect to `/user/<id>?tab=proposals`, and display the user's drafts. What do you think?

**Comment by victorgcramos** [comment]
[Here](https://github.com/victorgcramos/politeiagui/tree/1392-my-proposals-page) is a quick preview of how my suggestion works.
