### ISSUE TITLE
Thumbs up/down improving

### ISSUE THREAD

**Issue by MariaPleshkova** [decred/politeiagui#1393]
Thumbs up/down still don't work right

Implementation:
![image](https://user-images.githubusercontent.com/8841018/64709913-b579a100-d4bf-11e9-9a4a-17e2397afcb4.png)

Specs:
![image](https://user-images.githubusercontent.com/8841018/64709934-c0343600-d4bf-11e9-97e5-fd5d725f8b5b.png)

**Comment by fernandoabolafio** [comment]
Duplicated of https://github.com/decred/politeiagui/issues/1320
