### ISSUE TITLE
[redesign] Duplicated batched calls on tab switch

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#1410]
1- Go to the Public Proposals page
2- Switch the tab, the first two calls to `batch` and `batchsummary` are duplicated. They are sending the same tokens in the payload. 

After this first call, as we scroll the page, the other calls are working as expected.

**Comment by amassarwi** [comment]
will look into it :eyes:

**Comment by amassarwi** [comment]
trying to on master locally and on https://pi-redesign.authit.co - approved and rejected tabs working as expected.
was it a specific tab ?
