### ISSUE TITLE
[redesign] "Waiting for approval" proposal status is not clear

### ISSUE THREAD

**Issue by RichardRed0x** [decred/politeiagui#1413]
![image](https://user-images.githubusercontent.com/37707106/65058550-5a86f480-d96c-11e9-99b6-945dfb0ac9ae.png)

I assume it means that the proposal owner has authorized voting to start? "Waiting for approval" reads more like waiting for admin approval to be displayed, to me.

The others are labelled "Hasn't authorized yet", which is also not that clear.

How about: "Waiting for owner authorization for voting" and "Waiting for admin authorization for voting"? They're a bit longer but it's hard to explain this fairly unusual status in a few words.

**Comment by tiagoalvesdulce** [comment]
@MariaPleshkova

**Comment by noahpierau** [comment]
Great issue, I had the same experience. 

When we look at it from a user perspective, users want to see which action is required from them. Something like: 

- "Proposal is being discussed" 
- "Proposal has been finalized" 

Ideally we'd also have a green tag for when admins have decided to approve the proposal vote: 

- "Voting will start within 24h"

**Comment by MariaPleshkova** [comment]
That's a good remark!
The statuses @RichardRed0x suggested are more clear, I agree. But what about shortening them a bit? They are really too long. Maybe we can leave only "Waiting for owner authorization" and "Waiting for admin authorization" without "for voting" end? I think it's more or less clear that it's for voting. 
Also regarding "Proposal has been finalized", there is "Finished" status already.

**Comment by thi4go** [comment]
On this
