### ISSUE TITLE
[redesign] Credits tab flickering on initial load

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#1418]
Navigate to your user account page.
Switch from the Identity tab to the Credits tab.
On the initial load of the Credits tab you'll see a flickering of the Credits view.  The top part of the Credits view is painted to the screen, then the loading icon shows up making it disappear, then the screen will be repainted with the full credits view once the credit transactions have loaded.

**Comment by camus-code** [comment]
Working on this
