### ISSUE TITLE
[cms/proposals]  Accounts/User Information causing tons of requests?

### ISSUE THREAD

**Issue by alexlyp** [decred/politeiagui#1420]
On cms or pigui (v1), when going to the accounts page (/user/user-id/tab=general) there end up being tons of similar URLs in the history even though there was only 1 original request.

**Comment by amassarwi** [comment]
Would like to work on this next

**Comment by tiagoalvesdulce** [comment]
@alexlyp are you still experiencing this after the redesign?

**Comment by alexlyp** [comment]
I believe so, though getting an error currently when requesting the account information.
https://github.com/decred/politeiagui/pull/1625#issuecomment-573814267
So once that error is patched I'll close this issue accordingly.

**Comment by amassarwi** [comment]
@alexlyp this isn't relevant anymore, right  ?

**Comment by alexlyp** [comment]
All done.  Closing
