### ISSUE TITLE
[redesign] Buttons looking weird in the New Proposal page on mobile

### ISSUE THREAD

**Issue by tiagoalvesdulce** [decred/politeiagui#1427]
<img width="251" alt="Screen Shot 2019-09-19 at 10 45 17" src="https://user-images.githubusercontent.com/13955303/65250818-93d67600-dacc-11e9-800a-44fd1ed67f68.png">

**Comment by amassarwi** [comment]
@tiagoalvesdulce I can fix this one, do you have the specs for it ?

**Comment by tiagoalvesdulce** [comment]
<img width="244" alt="Screen Shot 2019-09-19 at 16 25 09" src="https://user-images.githubusercontent.com/13955303/65274616-1c1f4000-dafa-11e9-9d58-ff8559b16bde.png">

**Comment by amassarwi** [comment]
@tiagoalvesdulce thanks )
