### ISSUE TITLE
Request: make it easy to spot completed proposals

### ISSUE THREAD

**Issue by noahpierau** [decred/politeiagui#1431]
Right now there are several proposal status indicators `Hasn't authorized yet, Waiting for approval, Finished, Abandonded` (discussed in #1413) and several tabs `In Discussion, Voting, Approved, Rejected, Abandoned` on Politeia. 

However, for an outsider it is not clear which proposals were actually completed and which ones are still in progress. In order to make it easy to spot completed proposals, I would suggest to either add a new status indicator that is assigned to all completed proposals in the `approved` tab, or create a totally new tab that will contain all completed proposals.

**Comment by tiagoalvesdulce** [comment]
@MariaPleshkova

**Comment by MariaPleshkova** [comment]
Actually, there were some different tabs on the layouts, like Active voting and Finished voting. So I suggest to split Voting tab into these 2 and remove In progress then (because as far as I understand In progress and Active voting mean the same, yes?)

**Comment by fernandoabolafio** [comment]
There is no "In Progress" tab. The tabs are "In Discussion", "Voting", "Approved", "Rejected" and "Abandoned".
I don't think that placing all finished proposals under the same tab would help either.  What I think we could do is maybe add some icons/indicators for the tabs? To represent in which tabs the proposals are still in progress and the ones which are completed?

**Comment by noahpierau** [comment]
That sounds like a good idea @fernandoabolafio.

Right now the icons/indicators used after the voting ended are `gray-cross Finished` for rejected proposals and `green-check Finished` for approved proposals. Maybe we could add a `blue-circle Complete` (or something like that) for the proposals that were actually completed?

My aim with this request is to:
1. give outsiders a better insight into the governance process of Decred
2. make it easy for stakeholders to check what happened with their votes
3. it will become immediately clear when a proposal is not yet marked as complete, this creates some extra accountability for proposal submitters

**Comment by MariaPleshkova** [comment]
@fernandoabolafio do you mean to add the same icons from statuses to the tabs?
![image](https://user-images.githubusercontent.com/8841018/65518544-1f953b80-deed-11e9-8d96-45805877c848.png)

**Comment by noahpierau** [comment]
Ah yes, those were the icons I assumed he meant. I didn't know blue was are already taken. How about this as example: 

- Abandoned: 
    - "orange-cross Abandoned"
- Voting: 
    - "blue-dots Active"
- Rejected: 
    - "red-cross Finished"
- Approved: 
    - "green-check Finished"
    - "black-check Complete"

just as an example, feel free to adapt

**Comment by lukebp** [comment]
This needs to be figured out on the backend first before we start talking about the frontend implementation.

**Comment by noahpierau** [comment]
Based on a conversation in general: 

It would be very cool to have proposal authors be able to provide updates in one place. To do that, we need to integrate progress updates for proposals. 

The icons/indicators of proposals in the "Approved" tab could include a share of the budget that was already paid (in USD terms or in percentages) so anyone can see how far ahead a proposal is (since milestones in the proposals are linked to payouts).

An additional benefit: this way it's possible to spot proposals that have "under-promised" and/or "over-delivered" (completed the proposal while invoicing less than the approved budget)

**Comment by noahpierau** [comment]
Should I close this issue because backend work is required? Or leave it open for now?

**Comment by fernandoabolafio** [comment]
Firstly I thought you just wanted a better indication of which proposals are "voting completed". Now I understand that you're more concerned with the competition signal of proposals after the vote (e.g budge spending, outcomes, etc). Such level of detail after vote requires a considerable amount of backend work. If that is indeed the case I think we can close it and feel free to move it to another discussion on the backend repo.
If considering the current "state-state-of-the-art" you think we can improve the UI/UX indication for users about the proposal status let us know.

**Comment by lukebp** [comment]
decred/politeia#825

@noahpierau you can close this issue.  Further discussion can be on the issue I linked above.
