### ISSUE TITLE
[redesign] Wrong scroll lock

### ISSUE THREAD

**Issue by tiagoalvesdulce** [decred/politeiagui#1435]
If the Credits tab on Account page is accessed by clicking the plus icon in the header the scroll is being locked somehow.

**Comment by thi4go** [comment]
On this

**Comment by tiagoalvesdulce** [comment]
Looks like the problem is with the sidebar drawer. Every time I open it my scrollbar gets locked. So, it's working as expected when opened but it's not unlocking the scrollbar after closing.

**Comment by thi4go** [comment]
Still having some trouble reproducing this, and breaking the scroll lock. Not sure why, but seems fine here

**Comment by fernandoabolafio** [comment]
This should be fixed with https://github.com/decred/pi-ui/pull/159/
