### ISSUE TITLE
[redesign] Drawer content needs to be aways on top of other elements

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#1447]
While testing test-proposals on a mobile device (Samsung s9) using Chrome browser. I noticed the drawer content is not consistently on top of the other elements:
![a55e1c86-752d-464f-8f19-a4facc286052](https://user-images.githubusercontent.com/14864439/65503776-e8f7fa80-dec5-11e9-8ad3-47b0398d99ba.jpeg)

**Comment by thi4go** [comment]
On this

**Comment by thi4go** [comment]
Hey @fernandoabolafio, I'm having some trouble reproducing this. Is there a specific context where this happens? On a proposal card with finished vote, for example?

**Comment by fernandoabolafio** [comment]
@thi4go This happens to me on test-proposals.decred.org, in the "approved" tab when accessed from my cellphone.

**Comment by tiagoalvesdulce** [comment]
@fernandoabolafio I couldn't reproduce it on my end as well.

**Comment by tiagoalvesdulce** [comment]
Closing because I can't reproduce it. Feel free to reopen if more people are complaining about it.
