### ISSUE TITLE
[redesign] Proposal credits found by a rescan need a page refresh to get added

### ISSUE THREAD

**Issue by thi4go** [decred/politeiagui#1457]
Had an account that was missing two proposal credits; when I hit rescan, it found those two credits, but it wasn't added to my header field, only when I ran a page refresh. It needs to update the state accordingly.

**Comment by tiagoalvesdulce** [comment]
The proposal credits state could use a normalization similar as the one Fernando did for the comments on https://github.com/decred/politeiagui/pull/1448.

**Comment by thi4go** [comment]
Working on that @tiagoalvesdulce :+1:
