### ISSUE TITLE
[redesign] Credits tab keeps showing the spinner indefinitely 

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#1461]
When I go to the "credits" tab under a user account it keeps showing the spinner indefinitely.

**Comment by fernandoabolafio** [comment]
Looks like it is happening only for users who haven't purchased any proposals credits yet.

**Comment by fernandoabolafio** [comment]
It was broken on #1445

**Comment by thi4go** [comment]
Another case where this happens is when accessing a user profile url (https://localhost:3000/user/b68b0be7-e416-42d2-99ac-cded9306877b) while being logged out. Think this doesn't need a new issue.

**Comment by fernandoabolafio** [comment]
closed on #1465
