### ISSUE TITLE
Test failing sporadically

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#147]
The test below is failing sporadically when running continues integration from travis:
```
✖ resetPassword

   - Reset password (5.019s)
   Timed out while waiting for element <.message-ct.message-error> to be present for 3000 milliseconds.  - expected "visible" but got: "not found"
```
Need to investigate what is causing it to occur to decide for rewriting the test or removing it.

**Comment by vctt94** [comment]
I believe that because all tests are starting at the same time, even with a bigger time to get visible, they are failing because is using a lot of processing. We could use a queue or something similar so tests run each at a time.

**Comment by fernandoabolafio** [comment]
Yes, is definetly a processing overload issue. When I ran the test on a single session at my computer it works perfectly. If I try to run the tests into 2 or more sessions simultaneosly some of the test cases starts to fail. So this is probably due the capability of the instance being used by Travis.
