### ISSUE TITLE
[cms] Update invoice submission for SubContractors

### ISSUE THREAD

**Issue by alexlyp** [decred/politeiagui#1471]
https://github.com/decred/politeia/pull/1023

This recent politeia PR adds the ability to denote a given line item as a billed subcontractor hours.

It also adds a new request so users may return a list of subcontractors that are using them as a supervisor. This will allow us to populate a dropdown (when in the new type 4) with their list and they can simple select their subcontractor for that line item.

**Comment by victorgcramos** [comment]
Just waiting for https://github.com/decred/politeia/pull/1023 to be merged to jump into this!
