### ISSUE TITLE
[redesign] Proposal paywall polling needs polishment

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#1472]
There are a few things we need to improve on the proposal credits paywall:
- The paywall polling should be triggered only when the current user accesses its own account credits. Right now the polling is fired even when we access another user's account credits.
- The paywall is triggered every time we access the credits tab, despite the user having an active purchase or not. This should be adjusted to:
   - The user generates a new payment that triggers the polling.
   - When the user accesses the credits tab, we ask the backend once (or a limited number of times) if there is any pending transaction, if there is we keep polling, otherwise we stop it.

**Comment by amassarwi** [comment]
Would like to work on that
