### ISSUE TITLE
[redesign] Weird action buttons positioning on Edit Proposal mobile view

### ISSUE THREAD

**Issue by victorgcramos** [decred/politeiagui#1484]
The action buttons are misaligned. The image above can illustrate the wrong positioning of the elements: 
![Screen Shot 2019-10-09 at 21 39 44](https://user-images.githubusercontent.com/22639213/66530408-11930d80-eade-11e9-9827-3938110abec9.png)

**Comment by victorgcramos** [comment]
@thi4go could you try to replicate this?

**Comment by tiagoalvesdulce** [comment]
I replicated it here. The position is wrong for some screen sizes.

**Comment by thi4go** [comment]
Getting the same here mate, nice catch. Have the impression we already fixed this, but maybe the recent tweaks with the ui elements changed this a bit.

New proposal:
![image](https://user-images.githubusercontent.com/2729122/66573981-dc240980-eb49-11e9-8f00-e57fce0ea5ad.png)

Edit proposal:
![image](https://user-images.githubusercontent.com/2729122/66574065-fd84f580-eb49-11e9-8abf-76b4ff25d0da.png)
