### ISSUE TITLE
[redesign] Don't allow new replies under a censored comment

### ISSUE THREAD

**Issue by thi4go** [decred/politeiagui#1485]
When a comment is censored, only its children comments can be replied to. This is so that people don't start a whole new conversation thread under a censored comment, which doesn't make sense.

**Comment by thi4go** [comment]
Will be fixing this

**Comment by tiagoalvesdulce** [comment]
This issue requires backend work. What's your opinion about this @lukebp ?

**Comment by lukebp** [comment]
I don't think this is a big deal.  If you guys feel strongly about this we can have a discussion in the politeia channel and see what other people think.

**Comment by thi4go** [comment]
Since this isn't a pressing concern, I'll be closing this issue until this discussion is brought up again, and we can focus on more important issues for now.
