### ISSUE TITLE
[redesign] Proposal form UI/UX

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#1487]
I think the proposal form has too many buttons under the text editor, especially when editing a proposal. Currently, it looks like this:

<img width="791" alt="Screen Shot 2019-10-10 at 17 49 23" src="https://user-images.githubusercontent.com/14864439/66585021-6722f500-eb86-11e9-951c-9bdae088d419.png">

What I thought about is to remove the "New Proposal" button on the top and add the  "cancel button" there instead. Something like this:

<img width="794" alt="Screen Shot 2019-10-10 at 17 51 47" src="https://user-images.githubusercontent.com/14864439/66585262-d1d43080-eb86-11e9-9cb4-da57906e3cff.png">

mobile:

<img width="340" alt="Screen Shot 2019-10-10 at 17 52 29" src="https://user-images.githubusercontent.com/14864439/66585287-dac50200-eb86-11e9-9321-b8e297f05272.png">

@MariaPleshkova

**Comment by tiagoalvesdulce** [comment]
Looks good to me but I think we also need a "Reset" button to do what the Cancel button is currently doing.

**Comment by fernandoabolafio** [comment]
Ok so looks like we need to fit two buttons here:
- Cancel: cancel the "edit" operation and takes the user to the "proposal detail" page.
- Reset: remove the changes applied in the current editing session. 

@MariaPleshkova can you help us fit all of this together?  I think we can explore better space left where we use to have the "new proposal" button and place those minor actions there.

**Comment by MariaPleshkova** [comment]
@fernandoabolafio Cancel button instead of New proposal one looks good. 
Regarding Reset one - I don't understand the difference between Cancel and Reset. If we click on Cancel it will remove the changes and will go to the previous page. But what Reset button gonna do?

**Comment by MariaPleshkova** [comment]
@fernandoabolafio @amassarwi but do we really need this? Is it a popular action?

**Comment by amassarwi** [comment]
In my opinion in this case it won't be that valuable.
Also, less action items on screen is cleaner ux In my eyes.

**Comment by fernandoabolafio** [comment]
Ok, let's keep only **cancel** button which routes back to the proposal details.

**Comment by thi4go** [comment]
Will be solving this in the same PR for #1484

**Comment by fernandoabolafio** [comment]
closed on #1493
