### ISSUE TITLE
JS error thrown when using non-Latin characters in proposal description

### ISSUE THREAD

**Issue by sndurkin** [decred/politeiagui#149]
User tried to submit a proposal with non-Latin characters (e.g. čćžšđ):

    Uncaught DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
       at C (https://test-proposals.decred.org/static/js/main.7efc4892.js:1:111741)
       at Object._ (https://test-proposals.decred.org/static/js/main.7efc4892.js:1:111845)
       at https://test-proposals.decred.org/static/js/main.7efc4892.js:1:123454
       at https://test-proposals.decred.org/static/js/main.7efc4892.js:1:121325
       at https://test-proposals.decred.org/static/js/main.7efc4892.js:1:678877
       at dispatch (https://test-proposals.decred.org/static/js/main.7efc4892.js:1:676085)
       at https://test-proposals.decred.org/static/js/main.7efc4892.js:1:1119549
       at https://test-proposals.decred.org/static/js/main.7efc4892.js:1:678877
       at Object.onSave (https://test-proposals.decred.org/static/js/main.7efc4892.js:1:675400)
       at t.value (https://test-proposals.decred.org/static/js/main.7efc4892.js:1:1186602)
    b @ react-dom.production.min.js:36
    rethrowCaughtError @ react-dom.production.min.js:35
    processEventQueue @ react-dom.production.min.js:49
    handleTopLevel @ react-dom.production.min.js:57
    w @ react-dom.production.min.js:43
    batchedUpdates @ react-dom.production.min.js:190
    _ @ react-dom.production.min.js:41
    A @ react-dom.production.min.js:41
    batchedUpdates @ react-dom.production.min.js:42
    dispatchEvent @ react-dom.production.min.js:45

**Comment by tiagoalvesdulce** [comment]
Should we allow these characters or should we add an error message when the user tries to submit a proposal with latin characters in the description?

**Comment by sndurkin** [comment]
@marcopeereboom, what do you think?

**Comment by marcopeereboom** [comment]
So I think we should disallow non 7 bit ASCII because the lingua franca of the decred project is English.  Not sure how we can handle non-English props.
