### ISSUE TITLE
Redux state normalization

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#1490]
As previously discussed here: https://github.com/decred/politeiagui/pull/1448#issuecomment-535465091 we have technical debt in the way we currently cache data fetched from the API. Our caching works per endpoint versus per data entity as it should be. The biggest issues caused by this approach are:
 - Violates the "single-source-of-truth" principle, as the same data can be cached in different places.
 - Hard to give maintenance as, for instance, all state modifiers are in the same reducer/file.
 - Slow down the overall scalability.

## Functional comparison

**Current flow:**

![Untitled Diagram (3)](https://user-images.githubusercontent.com/14864439/66762813-f3932780-eea6-11e9-8418-44ae5b8a7dc2.png)

**Flow suggested:**

![Untitled Diagram (4)](https://user-images.githubusercontent.com/14864439/66762877-16bdd700-eea7-11e9-9d59-a8c00914bde1.png)

As shown in the flowcharts above, the new approach adds a second reducer that reacts to "RECEIVE_DATA" actions and properly creates/updates a normalized state accordingly to each entity's needs and structure.  The API reducer will be kept only for managing "control values" such as the params used for the request, "isRequesting" and "hasError". 

## Structural comparison

![Untitled Diagram (5)](https://user-images.githubusercontent.com/14864439/66763278-dc086e80-eea7-11e9-8739-9bff7b38814b.png)

The major structural change will be uncoupling those huge API modules into smaller and better manageable modules.

## Execution

These will be a progressive work and will be done by parts. The checklist of entities to be moved into its own state branch are:
- [x] Comments
- [x] Proposal Credits
- [x] Proposals
- [x] Proposals votes
- [x] User
- [ ] Paywall
- [x] Invoices

**Comment by thi4go** [comment]
I'm thrilled with this ongoing refactor on our state management system. Many thanks for pulling this out mate. Decoupling our state from the gigantic `api` module will have a major impact on the code's maintainability and scalability. By having the state separated by contexts (proposals, user, votes...), we will have each part of the state management control living close to each other, that is, the actions, reducers and selectors. This will result in a much more comprehensive flow of data, instead of having to go through enormous files to understand whats going on, or to add new features.

I'd like to help out on this process. Thought of normalizing the user data now. Any considerations @fernandoabolafio? As soon as you ok this I can get started on it.

**Comment by victorgcramos** [comment]
Good point, @fernandoabolafio! I agree with @thi4go here about the scalability. I am able to help with this as well!

**Comment by fernandoabolafio** [comment]
@thi4go the actions are the trickiest part because while I want to split it by context there are cases where an action will affect two reducers (not considering the API reducer). For example, "RECEIVE_START_VOTE" action affects the proposalVotes and the proposal reducer. Should this action be part of `actions/proposals.js` or `actions/proposalVotes.js`? Looks like the latter is more suitable. Anyhow, I think we can apply the changes for reducers and selectors first, once we're done with that it will be more clear for us how to deal with the actions. I am open to suggestions here. What do you think? @victorgcramos feel free to weight in here too.


> I'd like to help out on this process. Thought of normalizing the user data now. Any considerations @fernandoabolafio? As soon as you ok this I can get started on it.

You can get started on that if you want.

**Comment by victorgcramos** [comment]
IMO, it should be on `proposalVotes.js`... Makes more sense since they share the same "vote" name on both reducer and file.

**Comment by thi4go** [comment]
Going forward with normalizing user data, I agree that we should first refactor reducer/selector, and from there decide the best approach for the actions. I'm inclined to say that from the action's naming and its general idea, we'll be able to intuitively tell where it belongs. In that particular case I agree that it should be on `proposalVotes` model.

**Comment by thi4go** [comment]
Hey @fernandoabolafio, as described in PR #1514, we could benefit from normalizing the paywall data across our state as well. Can we put it on our list?

**Comment by fernandoabolafio** [comment]
Yes @thiago. Adding it.

**Comment by amassarwi** [comment]
@fernandoabolafio user checkbox was ticked!
Would like to add the paywall refactoring if it still in todo
