### ISSUE TITLE
RFPs in the proposal list views

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#1491]
The request for proposal (RFP) backend work is nearing completion.  One item that still needs to be decided is how the RFP proposal and the proposals that are submitted to the RFP (RFP options) are going to be displayed in the proposal list views.  These design decisions will effect how RFP proposals and the RFP options are returned in the `TokenInventory` call.  The backend RFP work cannot be completed until we figure this out.

A little background on how the RFP process will work.  An RFP is a special kind of proposal that allows other proposals to link to it.  I'll use the market maker proposals to illustrate how it works.
 
- jz would have submitted an RFP proposal detailing what the Decred community was looking for in a market maker and opening up the process for potential market makers to submit proposals that link to the RFP.
- Market makers submit individual proposals that are linked to the RFP proposal.  Each proposal submitted and linked to the RFP becomes an RFP option.
- When an admin starts the voting process on the RFP, the vote commences on all of the RFP options simultaneously.  The Decred stakeholders vote yes/no on each of the RFP options individually like you would normal proposals.  The RFP proposal itself is never actually voted on.
- The proposal with the most net yes votes wins (must also meet the normal quorum requirement).  The i2 proposal would be declared the winner.  There can only be one winner so even if one of the other market maker proposals met the 60% pass requirement, their proposal would still be considered rejected if it did not get more net yes votes than the i2 proposal.

We need to figure out how these RFP proposals and RFP options will be displayed in the proposal list views.

**Considerations:**
- The RFP options fit into the existing architecture where a proposal is either approved, rejected, or abandoned, but the RFP proposal itself does not since it is never actually voted on.  Once the voting period has ended on the RFP options, what tab (approved, rejected, abandoned, etc) should the RFP proposal be listed under?
- Should the RFP options be listed as individual proposals in the list views or should the RFP and all of the RFP options be grouped together as a single item?
- It will be possible for an RFP option to meet the normal quorum and pass requirements, but still be rejected if one of the other RFP options has more net yes votes.  This could lead to confusion if, for example, a proposal with a 70% pass rate that met the quorum requirement is listed in the "Rejected" column.

**Potential Solutions**
1. We could group the RFP and all the RFP options as a single list item.  After the vote is over, the list item would should the yes/no results for each RFP option.  The RFP list item would be listed under the "Approved" tab if one of the options was approved.  It would be listed under the "Rejected" tab if none of the options met the quorum and pass requirements.
- Cons: the only way to access an individual RFP option would be through the RFP proposal.  The RFP options would not be listed individually under the Approved, Rejected, or Abandoned tabs.  This could be confusing since the RFP proposals are voted on individually so you may think that they should be listed in the Approved, Rejected, or Abandoned tabs based on their individual outcome.

2. The RFP proposal would be listed under a new RFP tab.  The RFP options would be listed individually under the Approved, Rejected, and Abandoned tabs based on the outcome of their individual vote.
- Cons: a proposal that would normally be considered approved because it met the normal quorum and pass requirements could still be listed under the rejected tab if another RFP option received more net yes votes.  This is confusing.

I need the design team to put some thought into this and weigh in.
cc: @linnutee @MariaPleshkova

**Comment by fernandoabolafio** [comment]
Why not place the RFP as a regular proposal under the "In discussion" tab and clearly indicates that it is an RFP proposal? IMO is not wrong to place it "under discussion" while the options have not yet been voted and move it to "approved" or "rejected" once the options voting is completed. 
This how I imagine this, in a very basic way:
![Screen Shot 2019-10-14 at 18 13 10](https://user-images.githubusercontent.com/14864439/66766492-808daf00-eeae-11e9-821c-4f8ae622bbda.png)

Then in the proposal detail view, we would have the link to the applicants directly.

**Comment by lukebp** [comment]
> Why not place the RFP as a regular proposal under the "In discussion" tab and clearly indicates that it is an RFP proposal? 

Right, I'm mainly talking about deciding where it should be listed once voting is complete.

>  move it to "approved" or "rejected" once the options voting is completed

You never actually vote on the RFP proposal itself, but listing it under "Approved" or "Rejected" based on whether one of the RFP options was approved is what I described in option 1.  I think if you did this though you would need to should the results of all the RFP options together as a single list item since RFP itself isn't actually approved or rejected, one of the specific RFP options is.

**Comment by lukebp** [comment]
I had this incorrect.  The RFP proposal will actually be voted on.  Only once the RFP proposal has been approved will there be a period that allows other proposals to link to the RFP, then there will be a separate vote on those proposals.  This makes displaying RFP proposals in the gui much easier since they will fit into the existing approved or rejected tabs.

Clothing this issue.
