### ISSUE TITLE
Users should be informed that 2 newlines are needed to create new paragraphs

### ISSUE THREAD

**Issue by sndurkin** [decred/politeiagui#150]
A user on Slack reported that newlines on comments are broken; they weren't aware you need 2 newline characters to create a new paragraph.

I know this mistake is made fairly often with new users on Reddit, and I think the same will happen on the proposal system as a lot of people won't be familiar with Markdown formatting. I think the UI can be a little smarter here and inform users if they're using single newline characters in their proposal or comment that it will not show up as separate paragraphs.

**Comment by fernandoabolafio** [comment]
@sndurkin what if we add another section above this table to give tips to the user?. So we can add tips for the most painful troubles users have with markdown.
![screen shot 2017-12-13 at 5 48 42 pm](https://user-images.githubusercontent.com/14864439/33959276-1cc22248-e02e-11e7-8fbb-728cc9a1aa80.png)

**Comment by sndurkin** [comment]
People might ignore the tips and still make that mistake, but I guess it's an easier solution than adding logic to detect newlines and warn the user. I think we should do that and also display the preview for comments, and if we still see users making formatting mistakes, we can revisit.

**Comment by fernandoabolafio** [comment]
Cool! Im going to implement that then.
