### ISSUE TITLE
[redesign] Credits table overflowing on small screens

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#1500]
![overflowTable](https://user-images.githubusercontent.com/14864439/67000602-6c2cfa80-f0d8-11e9-9ef3-c48505b7494c.gif)

**Comment by amassarwi** [comment]
Found the source, the table is exceeding it's container, adding `table-layout: fixed;` to table element (in `pi-ui`) should solve it, adding PR in `pi-ui` repo.

**Comment by amassarwi** [comment]
Depends on https://github.com/decred/pi-ui/pull/169
