### ISSUE TITLE
[redesign] First click on submit in proposal form doesn't fire action

### ISSUE THREAD

**Issue by thi4go** [decred/politeiagui#1504]
This is a minor bug on proposal form; when I edit the body of a proposal, submit works properly when first clicked. When I edit only the title of the proposal, I have to click submit button two times for it to fire up.

![submit_bug](https://user-images.githubusercontent.com/2729122/67209973-a9ea9580-f3ee-11e9-9c2b-ae919fdfb60d.gif)

**Comment by amassarwi** [comment]
@thi4go I can have a look, if you are not working on it @thi4go :thinking: ?

**Comment by thi4go** [comment]
Go ahead mate, I'm not working on it currently 👍

**Comment by amassarwi** [comment]
@fernandoabolafio can be closed, was fixed with #1508
