### ISSUE TITLE
[redesign] Editing a proposal doesn't update the proposals list cache

### ISSUE THREAD

**Issue by thi4go** [decred/politeiagui#1505]
This results in inconsistent display of data on our proposal listings, under our proposal state tabs, i.e: "In Discussion", etc.

**Comment by amassarwi** [comment]
On it, if no one started already...

**Comment by fernandoabolafio** [comment]
@amassarwi this should be fixed on my pr #1492

**Comment by amassarwi** [comment]
Sweet, so maybe I'll try fix #1505 then ?

**Comment by fernandoabolafio** [comment]
Sure. Just make sure @thi4go isn't working on it already.

**Comment by tiagoalvesdulce** [comment]
Should be fixed on https://github.com/decred/politeiagui/pull/1492
