### ISSUE TITLE
Getting forbidden access 'randomly'

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#1529]
Sometimes when you go to https://test-proposals.decred.org/?tab=voting you may hit `Error: Forbidden`. After refreshing, it goes away. This doesn't happen very often hence it can be hard to reproduce. 
This issue is to track another occurrences of it  and to determine the root cause.

**Comment by amassarwi** [comment]
I could reproduce it: 
basically each time I open new chrome blank window,  then when pasting `https://test-proposals.decred.org/?tab=voting` to the address bar and hitting enter I get `Error: Forbidden`

It seems like `/api/v1/proposals/batch` , `/api/v1/proposals/batchvotesummary` calls were blocked with `403 forbidden` from the backend.

![image](https://user-images.githubusercontent.com/10324528/67716198-a9906280-f9cb-11e9-9cd6-bb580882bb76.png)

**Comment by fernandoabolafio** [comment]
Yeah, that's indeed what is going on. I cannot reproduce it anymore just by opening a blank window and pasting the URL. This is probably due to CSRF. Notice that the GET calls aren't being blocked, just the 2 POST calls: `/batch` and `/batchvotesummary`.
