### ISSUE TITLE
[cms] DCC details

### ISSUE THREAD

**Issue by alexlyp** [decred/politeiagui#1538]
DCC's will need to have a details content page much like invoices or proposals.  

The records themselves have a json payload just like invoices that can be decoded into a regular object.   

https://github.com/decred/politeia/blob/master/politeiawww/api/cms/v1/v1.go#L616-L635

That provides a decent rundown of the possible fields that need may to be rendered on the details page.

Most importantly the sponsor statement and the current status needs to be prominently shown.

**Comment by victorgcramos** [comment]
I'm on this too, since I'm handling the DCC listing.
