### ISSUE TITLE
Proposal link icons messed are misaligned on detail page

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#1556]
This was probably introduced on #1552. The positioning on the proposals list looks fine but when I access the proposal detail page it looks like this:

![Screen Shot 2019-11-04 at 11 13 49](https://user-images.githubusercontent.com/14864439/68113581-6c106580-fef4-11e9-983a-f45b89153a2e.png)

**Comment by amassarwi** [comment]
@fernandoabolafio master locally:
![image](https://user-images.githubusercontent.com/10324528/68162569-9c89eb00-ff58-11e9-9f70-e2e912e89b28.png)

**Comment by fernandoabolafio** [comment]
Ok, I can't reproduce anymore either. Closing for now.
