### ISSUE TITLE
Vote bar: enhance indicator labels 

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#1557]
As [discussed via Matrix](https://matrix.to/#/!VFRvyndKpzcLrVslQD:decred.org/$157286058232157KTxFg:decred.org?via=decred.org&via=matrix.org&via=zettaport.com), 2 main things need to be clarified in the vote stats view:
 - Indicate the gray mark refers to "pass percentage"
 - Indicate what is the min quorum

**Comment by RichardRed0x** [comment]
Here are some suggestions for the labels:
"60% Yes votes required for approval"
"XXXX votes cast, quorum requirement is YYYY votes"

**Comment by RichardRed0x** [comment]
The quorum one is probably too long to display all the time, could show on mouseover like the gray line.

**Comment by MariaPleshkova** [comment]
Yes, @RichardRed0x , good idea! 
It can be like this:
![image](https://user-images.githubusercontent.com/8841018/68203916-ebc33080-ffd7-11e9-9a55-8bc8184b17b8.png)

**Comment by amassarwi** [comment]
Adding this...
