### ISSUE TITLE
Proposal detail page top alignment is messed up

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#1570]
I believe the changes applied in this PR: https://github.com/decred/pi-ui/pull/184 messed up with the alignment of the proposal detail page:

<img width="1015" alt="Screen Shot 2019-11-11 at 18 25 16" src="https://user-images.githubusercontent.com/14864439/68607745-a6a86e00-04b1-11ea-96b2-48c85534e5bd.png">

**Comment by amassarwi** [comment]
On it 👀

**Comment by amassarwi** [comment]
Should be fixed with: https://github.com/decred/pi-ui/pull/185
