### ISSUE TITLE
High CPU usage after upvote

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#1577]
- I click upvote comment button
- After 3 seconds the upvote is added (which is too long on its own, but that's a separate issue)
- Then the CPU usage spikes to 100% for ~10 seconds and Firefox offers me to kill the offending script: https://proposals.decred.org/static/js/16.ea6869a6.chunk.js:1

This wasn't the case before the redesign. My browser setup didn't change.

**Comment by xaur** [comment]
When posting a comment I had to cancel two "Kill this script?" popups. I wonder what numbers is it crunching so heavily?

**Comment by fernandoabolafio** [comment]
@xaur in what proposal did it happen?

**Comment by xaur** [comment]
The upvote CPU drain happened in both [Spanish Marketing](https://proposals.decred.org/proposals/5af0ce1cd325be6be39109c2750f34095c4e8feeea962ede058a1e4f4a61473e) and [TinyDecred budget](https://proposals.decred.org/proposals/ad0f9688b3467734e2581604914b2cc32c6eb7991dff460eff41d21f66d88451) proposals.

The post-comment one happened in Spanish Marketing proposal but not in TinyDecred budget.

**Comment by xaur** [comment]
Was making a few comment upvotes today in the Latam proposal and there is no more freezing of Firefox. The CPU spike around 10 seconds after the upvote is down from 100% to 20% and doesn't last long. And to be fair it's hard to be sure that other stuff is not happening in the system.

**Comment by fernandoabolafio** [comment]
Ok @xaur I will consider this as closed because of https://github.com/decred/politeiagui/pull/1578. If you find any other issues in this regard, feel free to open more issues.
