### ISSUE TITLE
Author of proposal is not shown

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#158]
Author is shown for comments but not for proposals. Marco [says](https://www.reddit.com/r/decred/comments/7it18v/ama_14th_december_ask_me_anything_with_marco/dr9imwz/) it's a bug.

[Example](https://test-proposals.decred.org/proposals/d36cfd61aea212d8913dc3a8074833b95a0f6579263a2e6585bc7e07fffebe17/).

**Comment by marcopeereboom** [comment]
Actually, i think we should make it a config option in WWW.  Either show author everywhere or don't show it at all.

**Comment by xaur** [comment]
Any good reason to not show the author?
