### ISSUE TITLE
Enable darkmode

### ISSUE THREAD

**Issue by amassarwi** [decred/politeiagui#1584]
We would like to enable the dark mode theme. 
`pi-ui` already supports dark mode which need to be tested and integrated within `pigui`

**Comment by amassarwi** [comment]
Would love to add this after finalizing my wip in `pi-ui`

**Comment by victorgcramos** [comment]
This is a great improvement! I'd love to see this working haha

**Comment by amassarwi** [comment]
@fernandoabolafio @MariaPleshkova Any ideas how would the theme mode `toggle` look like ? and where should it be added ?

**Comment by MariaPleshkova** [comment]
@amassarwi @fernandoabolafio I think we can add it to the drop down. Like this:
![image](https://user-images.githubusercontent.com/8841018/69331484-ea476880-0c65-11ea-9c15-24c4b3e255ea.png)

Or we also can add some kind of toggle switch:
![image](https://user-images.githubusercontent.com/8841018/69332132-19120e80-0c67-11ea-87ba-f396ad814505.png)

What do you think?

**Comment by amassarwi** [comment]
@MariaPleshkova honestly I like the switch toggle much more, but it need to be added to `pi-ui` components first, let's see what others think.

**Comment by fernandoabolafio** [comment]
The toggle looks good to me as well. 👍

**Comment by amassarwi** [comment]
Waiting on https://github.com/decred/pi-ui/issues/193

**Comment by MariaPleshkova** [comment]
Here is the spec link of two screens with enabled dark mode. They can be as examples for you while creating the rest of the screens:

https://xd.adobe.com/view/1fea4fa1-a829-428c-48d9-3f72193f1be9-69db/

**Comment by amassarwi** [comment]
Great, thanks @MariaPleshkova
