### ISSUE TITLE
Loading indicator causes too much changes on the screen

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#159]
As I browse through proposals, my screen flashes back and forth between content and huge rotating loading indicator. I think it would be better to replace rotating logo with covering the dynamic area with semi transparent white cover.

**Comment by tiagoalvesdulce** [comment]
Good catch @xaur. I'll improve our loading indicator to prevent this flashing between it and the content.

**Comment by xaur** [comment]
Besides transparent white blanked, another common non-intrusive approach is thin (1-2px) line on top, like here on GitHub.
