### ISSUE TITLE
Mobile-friendly version

### ISSUE THREAD

**Issue by sndurkin** [decred/politeiagui#162]
It's not high on priority list right now, but I'm adding the issue just because we'll eventually want some kind of version that's friendlier to mobile devices.

**Comment by rrecuero** [comment]
I would be interested in working on this and create mobile friendly responsive design from scratch

**Comment by sndurkin** [comment]
@rrecuero that would be great, but hold off on implementing it for now because I'm expecting there to be a couple months after launch where we'll be getting some really valuable feedback about usability and necessary features, and after that is mostly settled, I'd like to get some UX guys in to do a redesign. I think the mobile version could be part of that redesign.

**Comment by rrecuero** [comment]
Yes, I agree @sndurkin. Redesigning it first and make it responsive as part of that redesign.

**Comment by fernandoabolafio** [comment]
Accomplished with the redesigned version.
