### ISSUE TITLE
Change the color of small sorting dropdowns (darkmde)

### ISSUE THREAD

**Issue by MariaPleshkova** [decred/politeiagui#1641]
**Implementation:**
![image](https://user-images.githubusercontent.com/8841018/71166184-3be21380-2263-11ea-8bd3-a1fc749a7078.png)
![image](https://user-images.githubusercontent.com/8841018/71166224-4bf9f300-2263-11ea-9b3b-5f32133ca729.png)

**Specs:**
![image](https://user-images.githubusercontent.com/8841018/71166373-a5fab880-2263-11ea-8ff1-6d875737ab13.png)

Background color in a dropdown itself should be the same as main background color on what this dropdown is. The color of its stroke+arrow inside should be `#99C1E3`, text color `#B7DEEE`

**Comment by amassarwi** [comment]
@MariaPleshkova what about the dropdown's menu ? how should it look like ?

**Comment by MariaPleshkova** [comment]
@amassarwi I guess the same as this one: 
![image](https://user-images.githubusercontent.com/8841018/72259201-e9f19b00-3620-11ea-8b1e-54061708a8d8.png)

![image](https://user-images.githubusercontent.com/8841018/72259577-e1e62b00-3621-11ea-806e-57d8e9e38bde.png)

Dropdown's background color `#223767` ;  active item `#B7DEEE` ;  inactive item `#6F98D3`.
You can find the spec here: https://xd.adobe.com/view/1fea4fa1-a829-428c-48d9-3f72193f1be9-69db/

**Comment by amassarwi** [comment]
@MariaPleshkova 
Looks good, thanks )
