### ISSUE TITLE
[cms] Properly handle January on SubmitInvoice

### ISSUE THREAD

**Issue by alexlyp** [decred/politeiagui#1652]
Due to the current month handling in SubmitPageInvoice, when the current month is January and the user makes no changes, it ends up submitting the invoice month/year as 0/2020 (for example now).  

I have added PR for validation to no accept those month/year combination any more but this corner case should be fixed on the GUI side as well.

**Comment by alexlyp** [comment]
https://github.com/decred/politeiagui/blob/master/src/components/snew/SubmitPage/SubmitPageInvoice.js#L49-L61

**Comment by victorgcramos** [comment]
on this!
