### ISSUE TITLE
[darkmode] change credits 'plus' icon button background color

### ISSUE THREAD

**Issue by amassarwi** [decred/politeiagui#1665]
With the latest button background color changes the credits 'plus' button became less visible!
What would be better color for it ? @MariaPleshkova
Should we use the buttons `blue` from the light mode ? 

![image](https://user-images.githubusercontent.com/10324528/72282360-c6d4e480-363c-11ea-8add-960ebc4ba207.png)

**Comment by MariaPleshkova** [comment]
yes, I'd leave it the same as in light mode
![image](https://user-images.githubusercontent.com/8841018/72599945-bade7080-3923-11ea-8a32-e11977d711ce.png)

**Comment by amassarwi** [comment]
tackled in #1700
