### ISSUE TITLE
[cms] Submit DCC enhancement

### ISSUE THREAD

**Issue by alexlyp** [decred/politeiagui#1668]
When selecting either Issuance or Revocation the form should change accordingly.

Issuance: 
- Show Domain
- Show Contractor Type
- Dropdown showing only Nominee Users

Revocation:
- Hide Domain (automatically set to whatever user is selected)
- Hide Contractor Type (since this should be set to Revoke internally)
- Dropdown showing only Full Users

**Comment by amassarwi** [comment]
Implemented in #1773
