### ISSUE TITLE
[cms] Submit DCC user selection dropdown

### ISSUE THREAD

**Issue by alexlyp** [decred/politeiagui#1669]
We should have a dropdown that shows user names instead of a basic text field with entry of a userid.

I believe I'll need to add a new authenticated route to allow requesting of users and return their username, domain and current type.  Will update this issue when that PR is up and ready.

**Comment by alexlyp** [comment]
The PR for this new route is up and can be used to dev this feature out: https://github.com/decred/politeia/pull/1100

**Comment by amassarwi** [comment]
Added in #1773
