### ISSUE TITLE
[cms-v2] Invoice form auto save

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#1672]
Implement the capability of auto-saving the invoice being edited so the changes aren't lost if the user accidentally leaves the page. 
This isn't the same as a draft. The auto-saving saves the changes just for the session and aren't persisted once the tab is closed or the invoice is submitted.

**Comment by amassarwi** [comment]
On it

**Comment by amassarwi** [comment]
Added in #1754
