### ISSUE TITLE
[darkmode] Buttons

### ISSUE THREAD

**Issue by tiagoalvesdulce** [decred/politeiagui#1682]
I'm not loving our buttons in dark mode. The primary button doesn't have enough contrast while the disabled button has a lot of it. The secondary button doesn't look good either. What do you think, @MariaPleshkova ?

![dark mode button](https://user-images.githubusercontent.com/13955303/72381612-728e3b00-36f6-11ea-92ae-6e43a90d4906.gif)
![Screen Shot 2020-01-14 at 17 49 18](https://user-images.githubusercontent.com/13955303/72381617-75892b80-36f6-11ea-9a10-bb1844430b96.png)
<img width="172" alt="Screen Shot 2020-01-16 at 16 10 45" src="https://user-images.githubusercontent.com/13955303/72561863-e2342f80-3888-11ea-9403-68b91738fd84.png">

**Comment by MariaPleshkova** [comment]
@tiagoalvesdulce 
- primary button active `#2970FF`
![image](https://user-images.githubusercontent.com/8841018/72601963-7bb21e80-3927-11ea-99bc-28c5ea938280.png)

- primary button disabled : background `#1F325F`, text `#152042`
![image](https://user-images.githubusercontent.com/8841018/72602046-aa2ff980-3927-11ea-9e8e-e1616eb080a2.png)

-secondary button 1 (eg "Save as draft"): stroke and text `#2970FF`
  secondary button 2 (eg "Formatting help") : text `#6F98D3`
![image](https://user-images.githubusercontent.com/8841018/72603334-e06e7880-3929-11ea-93be-62410d91d442.png)
