### ISSUE TITLE
[cms-v2] New DCC

### ISSUE THREAD

**Issue by victorgcramos** [decred/politeiagui#1686]
The submit/new DCC page for CMS v2 should include the same info than v1, such as:

- *DCC Type*
    Issuance or revocation
- *Nominee User ID*:
    This should include the adjustments from #1669 
- *Statement*
- *Domain*
-*Contractor Type*

The enhancements from #1668 and #1670 should also be included.

**Comment by victorgcramos** [comment]
V1 Reference: #1539

**Comment by amassarwi** [comment]
Implemented in #1773
