### ISSUE TITLE
Need to display a message when there is a key mismatch between client and server

### ISSUE THREAD

**Issue by sndurkin** [decred/politeiagui#169]
When the user logs in, the server sends the active public key that it has in the DB for that user. If this public key doesn't match the browser's local key (or there isn't a local key at all), the user should be alerted that he won't be able to perform any actions until it's resolved. The user should be directed to the user profile section for managing his keys so that he can either import an existing private key or generate a new one.

The message should probably be displayed on all pages and, additionally, actions like submitting proposals and comments should be disabled.

This issue sort of depends on #168; the message can be implemented before #168 is closed but will probably have to be slightly amended after it's in.

**Comment by brunobraga95** [comment]
I will work on this issue.

**Comment by brunobraga95** [comment]
could this message be displayed as a modal? do you have any design thoughts on this?
I am thinking about saving this information at the `store` and then in the `app` container, or the "root" component equivalent, check this information and depending on its value show a modal and disable possible actions.

also, is there right now such a feature as actions disabled? or should this be implemented as well?
We could either somehow disable every input component related to things like submiting proposals and comments, or we could allow the user to edit it, but not actually send it to the server.

**Comment by sndurkin** [comment]
I was thinking it could just be displayed as a persistent inline message at the top of every page, but a modal could work too. I don't think there is currently any feature to disable/hide actions, so we would have to implement that too.
