### ISSUE TITLE
[darkmode] Success icon not looking good

### ISSUE THREAD

**Issue by tiagoalvesdulce** [decred/politeiagui#1696]
<img width="346" alt="Screen Shot 2020-01-16 at 16 12 06" src="https://user-images.githubusercontent.com/13955303/72561959-190a4580-3889-11ea-9dbe-0d1ec65e3434.png">

**Comment by tiagoalvesdulce** [comment]
@MariaPleshkova

**Comment by MariaPleshkova** [comment]
@tiagoalvesdulce I guess it can be like this 
![image](https://user-images.githubusercontent.com/8841018/72608394-9f7b6180-3933-11ea-891d-9afa5d4c7fdf.png)

`#527CC9 `- light; `#1B2B54` - dark checkmark

[checkmark.svg.zip](https://github.com/decred/politeiagui/files/4076549/checkmark.svg.zip)
But weird,  it seems like it's a little bit different checkmark icon...
