### ISSUE TITLE
[darkmode] Table pagination elements need polishment

### ISSUE THREAD

**Issue by tiagoalvesdulce** [decred/politeiagui#1697]
This is how they're looking right now:
<img width="147" alt="Screen Shot 2020-01-16 at 16 14 29" src="https://user-images.githubusercontent.com/13955303/72562049-4c4cd480-3889-11ea-9668-b779541e3833.png">

@MariaPleshkova

**Comment by MariaPleshkova** [comment]
@tiagoalvesdulce 
![image](https://user-images.githubusercontent.com/8841018/72620124-bc259280-394f-11ea-82b7-7f108b7df80a.png)

1- `#2971FF`
2- `#E9F8FE`
3- `#769ECF`
4- `#2F4D8C`
5- `#99C1E3`

Arrows icons:
[Arrows.zip](https://github.com/decred/politeiagui/files/4077261/Arrows.zip)
