### ISSUE TITLE
[darkmode] Reply collapse/expand box color

### ISSUE THREAD

**Issue by amassarwi** [decred/politeiagui#1698]
Should get darker colors, what do you think @MariaPleshkova ?

![image](https://user-images.githubusercontent.com/10324528/72563612-52a17780-38ae-11ea-891b-f222ad2c2abe.png)

![image](https://user-images.githubusercontent.com/10324528/72563642-651bb100-38ae-11ea-9071-f41d56a9dcde.png)

**Comment by MariaPleshkova** [comment]
@amassarwi 
![image](https://user-images.githubusercontent.com/8841018/72712950-296a3b00-3b7d-11ea-8378-ab17cf43c6c5.png)

1- `#2970FF`
2- `#6F98D3`
3- `#B7DEEE`
4- `#6F98D3`
5- `#1B2B54`
6- `#6F98D3`
7- `#B7DEEE`
8- `#2F4D8C`
9- `#E9F8FE`
10- `#99C1E3`

Spec: https://xd.adobe.com/view/1fea4fa1-a829-428c-48d9-3f72193f1be9-69db/

**Comment by amassarwi** [comment]
@MariaPleshkova Thanks for the details specs and colors, actually me issue was about only 7 & 8, but great that you provided more colors, will apply them all :100:

**Comment by amassarwi** [comment]
Regarding `2` `#7DA7D9` was used instead of `#6F98D3`  - to keep it consistent with proposal's time ago & version colors.
