### ISSUE TITLE
[cms-v2] Can't expire user update key token 

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#1707]
1. Go to the User account, under the "identity" tab
2. Create a new identity and make sure the request was successful
3. Refresh the page and go to the account tab
4. Make sure you are an admin and expire the verification token for key update

Result: The request is successful but the key isn't really expired. Nor the frontend reflects that and if you try to create a new identity (step 2) it will say that there is an active token yet. 

It can be either a frontend bug or an API bug, in any case it needs further investigation and fix.

**Comment by tiagoalvesdulce** [comment]
Fixed on the backend re-adding the legacy endpoints to cmswww
