### ISSUE TITLE
My comment votes are not shown on closed proposals

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#1710]
I see the pressed buttons of comment upvotes/downvotes for proposals in In Discussion or Voting stage, but not Approved/Rejected/Abandoned stage.

**Comment by xaur** [comment]
@tiagoalvesdulce still seeing this, is it not deployed yet? If so, when is the next deployment?

**Comment by tiagoalvesdulce** [comment]
yep @xaur, not deployed yet. ETA for the next deployment is 3-4 weeks.
