### ISSUE TITLE
[darktheme] Markdown quotes & H6 color

### ISSUE THREAD

**Issue by amassarwi** [decred/politeiagui#1737]
As discussed on matrix, markdown quotes & H6 should have `#99C1E3` as text color.

**Comment by tiagoalvesdulce** [comment]
<img width="594" alt="Screen Shot 2020-01-30 at 18 23 23" src="https://user-images.githubusercontent.com/13955303/73491872-4c22fd80-438e-11ea-8a4a-096ff774dc9b.png">
<img width="76" alt="Screen Shot 2020-01-30 at 18 23 09" src="https://user-images.githubusercontent.com/13955303/73491873-4c22fd80-438e-11ea-8e28-d504ade28b88.png">
<img width="593" alt="Screen Shot 2020-01-30 at 18 22 37" src="https://user-images.githubusercontent.com/13955303/73491874-4c22fd80-438e-11ea-867a-a67cb10de418.png">

I think all those texts shouldn't be gray as well
