### ISSUE TITLE
Improve logout page UI

### ISSUE THREAD

**Issue by sndurkin** [decred/politeiagui#174]
The logout page just shows this:

![image](https://user-images.githubusercontent.com/1452379/34909395-ef5dcfd4-f86d-11e7-8423-96d94977e2e0.png)

The logout message needs to be improved a little.

**Comment by fernandoabolafio** [comment]
I will work on it.
I thought something like:

YOU ARE NOW LOGGED OUT. THANK YOU AND HAVE A GREAT DAY.
[Log back in](https://localhost:3000/user/signup) or check it out [Decred's](https://www.decred.org/) website.


Where log back in redirects the user to the login/signup page. The link to Decred's website could be any other link. The idea is to use it as an opportunity to improve user engagement.
