### ISSUE TITLE
[cms-v2] Save draft isn't saving sheet info

### ISSUE THREAD

**Issue by tiagoalvesdulce** [decred/politeiagui#1746]
![bug draft](https://user-images.githubusercontent.com/13955303/73661276-8fc08480-4678-11ea-95b6-2208aa24d935.gif)

The content from the sheet should be saved.

**Comment by thi4go** [comment]
Hey mate @tiagoalvesdulce, I couldn't reproduce this error on my end. Tried on different browsers and they all seem to be working as expected.

![draft](https://user-images.githubusercontent.com/2729122/73778028-400db600-4769-11ea-8aeb-e3ca4d68e1ff.gif)
