### ISSUE TITLE
[cms-v2] Invoice form auto save issues

### ISSUE THREAD

**Issue by tiagoalvesdulce** [decred/politeiagui#1760]
1. Submit button not active after a refresh even if all the fields are properly filled. I have to touch a field for it to get active. See:

![bug auto save](https://user-images.githubusercontent.com/13955303/74157717-82b31080-4bf7-11ea-93a0-ebe4be005267.gif)

2. After submitting a proposal, the session storage should be cleared.

**Comment by amassarwi** [comment]
@tiagoalvesdulce Regarding 2. it was addressed in #1758
