### ISSUE TITLE
Issue with modal icons on light theme

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#1779]
When running the proposals app I found issues with the color of the modal icon:

<img width="732" alt="Screenshot 2020-02-15 at 13 46 48" src="https://user-images.githubusercontent.com/14864439/74589577-b2eb1c80-5006-11ea-8810-0e574ee26e37.png">

<img width="655" alt="Screenshot 2020-02-15 at 13 54 24" src="https://user-images.githubusercontent.com/14864439/74589578-b4b4e000-5006-11ea-9ab6-24db632cd5fa.png">

**Comment by amassarwi** [comment]
@fernandoabolafio is it on `master`? or `cmsv2` ? :thinking:

**Comment by amassarwi** [comment]
@fernandoabolafio Can't reproduce neither on `master` nor on `cmsv2`.
I guess you have old `pi-ui` old version linked or something ? 
Can you double check which branch did it happen on ?

**Comment by fernandoabolafio** [comment]
@amassarwi you're right I had an old version of pi-ui linked to my pgui repo. Sorry for that.
