### ISSUE TITLE
[cms] Identities not available on some user accounts

### ISSUE THREAD

**Issue by thi4go** [decred/politeiagui#1783]
As brought up on https://matrix.to/#/!zUNclAsjlDCTJWzPVS:decred.org/$158184521121033FggcJ:decred.org?via=decred.org&via=matrix.org, some users on cms appear to have an identity, but it isn't showing on their user profile. This should be just a presentational issue, since the user does have an identity.

**Comment by tiagoalvesdulce** [comment]
Closing because I couldn't repro. Feel free to reopen if it's still needed.
