### ISSUE TITLE
Search in proposals and comments

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#1784]
Suggested [on Reddit](https://www.reddit.com/r/decred/comments/f4i870/decred_wishlist/fhsfrrt/). I bet it will require quite a lot of work and is not a high priority for now, but I think it's a good idea because the amount of knowledge stored in proposals and comments will keep growing.

**Comment by lukebp** [comment]
Closing this since it is a backend issue.  Search is on my radar and will be a priority in the near future.  You can add it to the politeia feature request thread (decred/politeia#1502) if you would like to document this feature request.
