### ISSUE TITLE
Don't render cast comment votes until server response is received

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#1792]
A few server lags when casting comment likes prompted me to open the dev tools and notice that comment likes are rendered immediately and speculatively before receiving the confirmation from the server. Then if the request times out or errors, the changed comment score is reverted and the pressed like/dislike buttons are returned to unpressed state. Unexpectedly, this state reversion is also followed by a few redrawings of the comment areas.

This speculative behavior is undesirable because it fools the user to believe his comment votes were cast sooner than it really happens on the server. If I cast a few votes, see that they are immediately applied and close the tab while there is a connectivity or server issue, the votes will not be applied and I will never know about it.

Another undesirable effect is that this behavior hides the fact that requests are processed slowly.

**Comment by thi4go** [comment]
Will work on this.
