### ISSUE TITLE
Code sections overflowing Markdown Preview

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#182]
Maybe add an horizontal scroll?
![screen shot 2018-01-18 at 11 54 18 am](https://user-images.githubusercontent.com/14864439/35101366-74053fde-fc46-11e7-9f57-5a386acae88b.png)

**Comment by thi4go** [comment]
I believe this is due to incorrect markdown. To add a horizontal scroll, use three slashes:

```
/Users/<username>/Library/Application Support/Politeiad/politeiad.conf
```

**Comment by fernandoabolafio** [comment]
I agree @thi4go however the markdown preview should at least cutt off the overflowing part so It doesn't look like a bug.

**Comment by thi4go** [comment]
You're right @fernandoabolafio ! Setted css overflow to auto on mde-review-content, and it solved it
