### ISSUE TITLE
[nojs] Edits for NoJS site

### ISSUE THREAD

**Issue by degeri** [decred/politeiagui#1830]
Most of the site works well over rendertron. Currently working on dockerizing it so that we can deploy it to the path 

` https://site.com/nojavascript`

But there are some small changes we need to make that handles special conditions. 

If the URI contains ?nojavascript=True the following changes need to be done.

1. The 5 different tabs at https://proposals.decred.org/
" Discussion,Voting,Approved,Rejected,Abandoned " all are JS triggered events. These need to become hardlinks (href) 

2 .  Some of the URL's should get rewritten. With an extra path. 
```

https://site.com/proposals/{token} => https://site.com/nojavascript/proposals/{token} 
https://site.com/user/{UUID} => https://site.com/nojavascript/user/{UUID} 
```
screenshots indicating the locations below. 
a.
![image](https://user-images.githubusercontent.com/41839293/77335547-96898080-6d26-11ea-9cce-5004f06d90a4.png)
b.
![image](https://user-images.githubusercontent.com/41839293/77335569-a1441580-6d26-11ea-84ed-95da157f0616.png)
c.
![image](https://user-images.githubusercontent.com/41839293/77335551-9ab59e00-6d26-11ea-9df0-ef096af5ebd2.png)

These changes are only for the root / and the /proposals/* pages.

**Comment by thi4go** [comment]
Will be working on this

**Comment by amassarwi** [comment]
@degeri @thi4go this issue was implemented in #1833 and can be closed, right ?

**Comment by thi4go** [comment]
That's right mate! :+1:

**Comment by degeri** [comment]
Yes closing it now.
