### ISSUE TITLE
[cms-v2] Minor adjustments

### ISSUE THREAD

**Issue by victorgcramos** [decred/politeiagui#1839]
- [ ] `user/search` search button needs some margin on mobile view
- [ ] Non-contractor users can't submit DCCs
- [ ] Remove logged in user from dcc revocation nominee list
- [ ] Approving/Rejecting DCCs not updating the UI until a refresh is done
- [ ] Align Approve/reject admin action selector on DCC with support/oppose buttons
- [ ] Change "before you signup" message (#1664)
- [x] Fix Admin actions on mobile view
- [ ] ~Dark Decred CMS logo on dark theme~

**Comment by tiagoalvesdulce** [comment]
[ ] Approving/Rejecting DCCs not updating the UI until a refresh is done

**Comment by victorgcramos** [comment]
@tiagoalvesdulce I think that there will be too many buttons because there is also the support/oppose buttons. After discussing with @amassarwi we decided to use this selector.

**Comment by tiagoalvesdulce** [comment]
Hmm, ok. We can keep it this way

**Comment by victorgcramos** [comment]
I think that these action buttons should be horizontally aligned, btw
![Screen Shot 2020-03-26 at 17 19 25](https://user-images.githubusercontent.com/22639213/77692753-f336a680-6f85-11ea-877a-7af8cf9d6741.png)

**Comment by tiagoalvesdulce** [comment]
https://github.com/decred/politeiagui/issues/1664

**Comment by thi4go** [comment]
One more minor UI detail. Header buttons are not positioned correctly on mobile view:

![image](https://user-images.githubusercontent.com/2729122/77759443-7fdb7600-7013-11ea-8e99-0a541bf7bbeb.png)

**Comment by victorgcramos** [comment]
@thi4go nice catch!
