### ISSUE TITLE
[cms-v2] DCC domain's not matching

### ISSUE THREAD

**Issue by alexlyp** [decred/politeiagui#1840]
On a couple of attempts at creating new DCC's I have received an error about not having a matching domain as the nominee.  I confirmed in the account settings/manage user that the domains do match and tried again with no success.

I then switched my domain to something else (marketing) then switched the DCC domain and it worked.  

After that it seems to work as expected whenever submitting any DCCs without needing to do any Domain switching via manage user.  So could just be something goofy with my environment.

**Comment by victorgcramos** [comment]
Is it still happening, @alexlyp? I couldn't replicate it on my local env

**Comment by tiagoalvesdulce** [comment]
Closing because I couldn't repro too. Feel free to reopen if the error persists.
