### ISSUE TITLE
[cms-v2] Replace TextInput by TextArea in the description field of the Invoice form

### ISSUE THREAD

**Issue by tiagoalvesdulce** [decred/politeiagui#1849]
We are currently using TextInputs for the description field but it's normally the place people use to detail their work. Adding support to markdown there will increase the UX a lot.

**Comment by victorgcramos** [comment]
We need this also for DCC statements!

**Comment by tiagoalvesdulce** [comment]
That'd be great

**Comment by tiagoalvesdulce** [comment]
We decided to go with the TextArea instead of the MarkdownEditor for now

**Comment by victorgcramos** [comment]
On this!
