### ISSUE TITLE
[cms-v2] Crashes when logging out

### ISSUE THREAD

**Issue by thi4go** [decred/politeiagui#1852]
Found two cases where the app crashes when logging out.

- from a user account page, `/user/b6200f1b-7b55-47e5-9084-f15968f393d3` for instance, the app tries to make a request to fetch that user information, which is a action that requires being logged in. 

- from the invoice form, after logging out, the app tries to fill the initial values for the form, where it uses logged in user information for it, resulting in a crash.

These errors need to be handled gracefully, and make sure that the app doesn't crash when it seeks information from a logged in user.

**Comment by amassarwi** [comment]
On it
