### ISSUE TITLE
[cms] Force github name entry for developer users

### ISSUE THREAD

**Issue by alexlyp** [decred/politeiagui#1859]
Similar to the current alert we should for missing/bad identity on GUI, we should also show an alert (and possibly not let users enter invoices) for when developer users don't have a GithubName set.

Then have a link to a form (or modal) for them to add that information (that uses the cmsedituser request).

**Comment by victorgcramos** [comment]
I'd like to work on this. I'm actually finishing some details from #1849 ad I should be able to jump to this 👍

**Comment by alexlyp** [comment]
How's progress on this going @victorgcramos ?

**Comment by victorgcramos** [comment]
@alexlyp just pushed it!
