### ISSUE TITLE
[cms] Improve invoice list

### ISSUE THREAD

**Issue by vctt94** [decred/politeiagui#1862]
Right now it is only possible to show invoices monthly or all of them, but tipically, a contractor send a monthly invoice, ending with a "list" of one invoice/month 

![image](https://user-images.githubusercontent.com/15069783/79489717-1a671d80-7ff2-11ea-8955-c5ecaacb0e7b.png)

It would be good having an anual option to show them as well

**Comment by victorgcramos** [comment]
On this!
