### ISSUE TITLE
[cms] New Invoice page nits

### ISSUE THREAD

**Issue by alexlyp** [decred/politeiagui#1864]
- the line item number and type cols are way too wide
- the rate hours, expense and subtotal cols could be narrower
- description col needs to be the widest
- font size could drop quite a bit on the invoice line items cols

**Comment by thi4go** [comment]
will work on this

**Comment by victorgcramos** [comment]
@thi4go I think it would be also good to improve cell skipping using `tab` keyboard button. `readonly` cells  block the `tab` skipping. It's just a tweak, don't know if it takes a lot of work to do, but it would also make the UX more fluid. Let me know what you think!
