### ISSUE TITLE
Prevent state updates after the component is unmounted

### ISSUE THREAD

**Issue by tiagoalvesdulce** [decred/politeiagui#1871]
When using the `useEffect` hook, the return parameter is used to clean up any async task that was triggered by the hook. We should use that to cancel unfinished async requests in order to prevent unnecessary attempts to update the state.

The warning is:
![image](https://user-images.githubusercontent.com/13955303/79773885-61ae2080-8308-11ea-9432-e5b73e1a70c7.png)

What I'm thinking so far is: the [fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) now accepts a signal variable that can be used to [abort the request](https://dom.spec.whatwg.org/#interface-AbortSignal). We can write a higher-order function that receives a `fetch` function and returns a cancel function that can be invoked to abort the request. Any thoughts?

**Comment by amassarwi** [comment]
Yep, looks like that's the way to go here:
https://dev.to/pallymore/clean-up-async-requests-in-useeffect-hooks-90h

**Comment by tiagoalvesdulce** [comment]
I investigated the issue a bit further and it occurs in some situations that we are not dealing with the `fetch` API but with any type of async action (like `setTimeout()`, for example). One example of bad usage is: https://github.com/decred/politeiagui/blob/aef05ee8b37f9da6cbf60aa58c3db5927feb3dcd/src/components/ModalBuyProposalCredits/ModalBuyProposalCredits.jsx#L32

This line is setting the modal type 300ms after it's closed. The problem is that now Modal components are completely removed from the DOM when closed.

I'll deal with this in the PR to fix the warning generated by uncleaned fetches as well.

**Comment by tiagoalvesdulce** [comment]
**Update:** this seems to be happening in two steps Modals as well. I think that what's happening is: Formik fires an action > app enters in loading state (here the Formik form is being unmounted but the action is still not completed) > action completes and tries to update the unmounted component (warning happens) > loading is finished > component is mounted again.

Clearing these warnings means touching the code in multiple parts so I'll be waiting until we release the RFP version to go ahead and work on this. Since it's a much larger issue than I thought initially, help is most welcome.

**Comment by amassarwi** [comment]
@tiagoalvesdulce 
Postponing it makes sense mate, I could help when RFP work is done, maybe we can split the work pi/cms or something like that

**Comment by tiagoalvesdulce** [comment]
I came up with a solution to verify the mounted state on `useEffect`: https://github.com/decred/politeiagui/pull/2277. This should clean the majority of these annoying warnings. I'm closing this issue and individual occurrences should be treated individually, mostly by extending the solution of 2277 to the problematic hooks.
