### ISSUE TITLE
Datepicker: switch to dark datepicker in dark mode

### ISSUE THREAD

**Issue by amassarwi** [decred/politeiagui#1874]
`pi-ui`'s `Datepicker` component should already support dark theme - has a `theme` prop, please check pi-ui's docz for more insights.

So passing `dark` as `theme` prop when dark mode is switched on in `pigui`/`cmsgui` should do the trick!

**Comment by victorgcramos** [comment]
I fixed this by using the `useTheme` hook on pi-ui. Didn't see this issue, so I fixed on https://github.com/decred/pi-ui/pull/256

**Comment by tiagoalvesdulce** [comment]
I think you solution is fine, @victorgcramos. Is it OK to you, @amassarwi ?

**Comment by amassarwi** [comment]
Yep, pretty neat!
