### ISSUE TITLE
Add metadata to proposal submissions

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#1883]
decred/politeia#1175 adds an additional `Metadata` field to `NewProposal` and `EditProposal` submissions.  This is how user defined proposal metadata, such as the proposal title, will now be passed in.  This is a breaking change for the gui since this new field is required.

Here are the bits relevant for the gui changes.

https://github.com/decred/politeia/blob/8bd5385bd0cfc5ca99d717e71aab44d2b00413b1/politeiawww/api/www/v1/v1.go#L386-L407

https://github.com/decred/politeia/blob/8bd5385bd0cfc5ca99d717e71aab44d2b00413b1/politeiawww/api/www/v1/v1.go#L774-L787

https://github.com/decred/politeia/blob/8bd5385bd0cfc5ca99d717e71aab44d2b00413b1/politeiawww/api/www/v1/v1.go#L1217-L1231

**Comment by amassarwi** [comment]
Implemented in #1886
