### ISSUE TITLE
Datepicker isn't showing selected value on toggle

### ISSUE THREAD

**Issue by amassarwi** [decred/politeiagui#1888]
I guess this was introduced with the latest invoices filtering work, see screenshot below: 

*Selected value is April 2020 and datepicker showing year 2018*
![image](https://user-images.githubusercontent.com/10324528/80793449-6e980300-8b97-11ea-914f-ba1f4509efad.png)

**Comment by amassarwi** [comment]
Also, as I said here: https://github.com/decred/politeiagui/pull/1873#issuecomment-617086867
Datepicker support range mode and it would be great if we show a range when a range option is selected:

![image](https://user-images.githubusercontent.com/10324528/80793727-32b16d80-8b98-11ea-8cad-031fdd159878.png)

**Comment by victorgcramos** [comment]
On this!
