### ISSUE TITLE
Security audit

### ISSUE THREAD

**Issue by sndurkin** [decred/politeiagui#189]
This article was published recently which highlights a potential attack vector by adding malicious code to an npm dependency: https://hackernoon.com/im-harvesting-credit-card-numbers-and-passwords-from-your-site-here-s-how-9a8cb347c5b5

Politeia GUI makes heavy use of npm modules, so we need to do a security audit of the code and discuss what steps (if any) we should take to shield sensitive user information such as emails, passwords and private keys from potentially malicious code running in a dependency.

**Comment by xaur** [comment]
Also check eval() as reported in decred/decrediton#1096

**Comment by tiagoalvesdulce** [comment]
A good solution was pointed out by the author of the article:

> As suggested here, you might want to consider having dedicated, lightweight pages for login and credit card collection that are served up in an iFrame. 

I think that having iframes written by us without the use of **any** external dependency to handle login, change password and update/save/import private keys could be a good start.

**Comment by JFixby** [comment]
Bank provide login form inside Java applet. Here is an example:

https://www.luxtrust.lu/en/management

![image](https://user-images.githubusercontent.com/1580663/35441836-58cbbe40-02a5-11e8-9f3b-62d0734b1da8.png)

**Comment by thi4go** [comment]
Same author did a Part 2 article on how to stop sensitive information from being harvested.

[https://hackernoon.com/part-2-how-to-stop-me-harvesting-credit-card-numbers-and-passwords-from-your-site-844f739659b9]

**Comment by xaur** [comment]
This is probably known, but just in case: in GitHub repository settings there's "Vulnerability alerts: Receive alerts for known security vulnerablities found in dependencies.".

**Comment by sndurkin** [comment]
Thanks everyone for your input! I like the idea of encapsulating forms and handling of sensitive information in a separate iframe with minimal JS, but I don't think it's something that we need to address immediately, so I'm going to put a future label on it for now.

**Comment by StabbarN** [comment]
A quick but important improvment would be to prevent `eval()`, see https://github.com/decred/decrediton/issues/1096

**Comment by StabbarN** [comment]
https://www.texthelp.com/en-gb/company/corporate-blog/february-2018/data-security-investigation-underway-at-texthelp/

> At 11:14 am GMT on Sunday 11th February 2018, a JavaScript file which is part of the Texthelp Browsealoud product was compromised during a cyber attack.  The attacker added malicious code to the file to use the browser CPU in an attempt to illegally generate cryptocurrency.  This was a criminal act and a thorough investigation is currently underway.

**Comment by degeri** [comment]
Guys is this useful  ? 

1.This protects against malicious js edits.

https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity (Include the hash for all includes so that if a js get changed or compromised the browser will not run it provided that the attacker cannot change the hash itself) 
More links:
https://frederik-braun.com/using-subresource-integrity.html

2.As the article states we can also set CSP which is a good option:
https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP
https://www.owasp.org/index.php/Content_Security_Policy

**Comment by JFixby** [comment]
https://thehackernews.com/2018/11/nodejs-event-stream-module.html?fbclid=IwAR1U5w1uC_twtr44cb3XUifnBTEeIZEaKvLlrwTSvunJLiwvKdgAhobX8xM

```
A widely used third-party NodeJS module with nearly 2 million downloads a week was compromised after one of its open-source contributor gone rogue, who infected it with a malicious code that was programmed to steal funds stored in Bitcoin wallet apps.

The Node.js library in question is "Event-Stream," a toolkit that makes it easy for developers to create and work with streams, a collection of data in Node.js — just like arrays or strings.
```

**Comment by xaur** [comment]
Mind the `?fbclid=IwAR1U5w1uC_twtr44cb3XUifnBTEeIZEaKvLlrwTSvunJLiwvKdgAhobX8xM`.

Seems our software is not vulnerable to that particular Node.js lib vulnerability https://matrix.to/#/!MgQoetFiyjrHAywokv:decred.org/$1543327747976fnYkf:zettaport.com .

**Comment by marcopeereboom** [comment]
@degeri has been doing a great job on this.
