### ISSUE TITLE
Error building project with mock api

### ISSUE THREAD

**Issue by thi4go** [decred/politeiagui#190]
Yarn not able to build project correctly. It tries to access serviceKey from the undefined object keys.
Tried checking out to https://github.com/decred/politeiagui/commit/4f01e9d7ac478b90e9e9286b7444a0980fdf832f and the error persisted.

Error with $ yarn uidev
![image](https://user-images.githubusercontent.com/2729122/35399366-354a8476-01db-11e8-9da5-bc61bb5c0f42.png)

localhost:3000/ :
![image](https://user-images.githubusercontent.com/2729122/35399119-b1057d6a-01da-11e8-9faf-d7131dd455d6.png)

**Comment by tiagoalvesdulce** [comment]
Here it works just fine. Can you remove `pem` and install it again? Looks like it's causing the error for you.

**Comment by thi4go** [comment]
You're right ! It solved by reinstalled pem. Sorry for opening this issue, can you close it?

Thanks !
