### ISSUE TITLE
[cms] Invoices tab in User details

### ISSUE THREAD

**Issue by alexlyp** [decred/politeiagui#1905]
Before v2 we had a tab in user details that would show admins all invoices a given user has ever submitted.  I'd like to make sure that gets added again.

**Comment by thi4go** [comment]
On this.

**Comment by alexlyp** [comment]
How's it going @thi4go?  Would like to get done soonish so the administrators have access to this for the upcoming round of reviews. Thanks

**Comment by thi4go** [comment]
Will get it ready by eod mate! :+1:
