### ISSUE TITLE
Show approved/rejected proposal date

### ISSUE THREAD

**Issue by victorgcramos** [decred/politeiagui#1907]
The mobile view for the **voting date**  is not able to show the full date. It would be nice to show the information on click, not just on hover.
<img width="380" alt="Captura de Tela 2020-05-07 às 16 22 33" src="https://user-images.githubusercontent.com/22639213/81336072-0b1e4180-907f-11ea-84da-90f7a3845ce7.png">

**Comment by tiagoalvesdulce** [comment]
We should default the Tooltip to toggle on click in mobile screens. It's the expected UX. I opened an [issue](https://github.com/decred/pi-ui/issues/259) for this at pi-ui.
