### ISSUE TITLE
Improve confimation dialogs

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#191]
Right now all the confirmation dialogs are the native one from the browser. I think we could have a custom confirmation modal for it, in order to keep the UI consitency and also improve the message displayed on them. 
See how this looks right now:
![screen shot 2018-01-27 at 11 17 45 am](https://user-images.githubusercontent.com/14864439/35472315-3e4ccfd2-0354-11e8-985f-c22062dda7a0.png)

**Comment by fernandoabolafio** [comment]
@brunobraga95 do you think the modal you're developing on #184 can be used here?

**Comment by brunobraga95** [comment]
yes it can, I will need to make a few changes on it can be done.

**Comment by brunobraga95** [comment]
I will work on this one after #169 is merged.

**Comment by fernandoabolafio** [comment]
At some point **might** be a redesign of Politeia's UI. However, the current UI is the one which will be launched and used as far as we know. Thus, we need to provide good UI/UX. So this is a needed polishment.
Do you still intend to work on it? Otherwise, I can tackle it.
