### ISSUE TITLE
Double : in the Account page

### ISSUE THREAD

**Issue by tiagoalvesdulce** [decred/politeiagui#1911]
<img width="670" alt="Screen Shot 2020-05-11 at 10 56 11" src="https://user-images.githubusercontent.com/13955303/81570029-6c435f00-9376-11ea-91ed-7202e729bb5c.png">

**Comment by blaltarriba** [comment]
I would like to make this issue my first contribution to Decred. 

I already saw how to fix this.

**Comment by tiagoalvesdulce** [comment]
Nice, @blaltarriba! I'm waiting for your PR. [Join matrix](https://docs.decred.org/getting-started/joining-matrix-channels/) and introduce yourself in the #politeia channel. You can also use this channel to ask questions and discuss future issues with the team.
