### ISSUE TITLE
[CMS] Update your Github username warning alert has the wrong colors in darkmode

### ISSUE THREAD

**Issue by tiagoalvesdulce** [decred/politeiagui#1918]
<img width="588" alt="Screen Shot 2020-05-12 at 08 38 29" src="https://user-images.githubusercontent.com/13955303/81683433-85a6e280-942c-11ea-95ef-4ea5916558d1.png">

**Comment by blaltarriba** [comment]
I see the component used is `Message` from `pi-ui` project. In that project there is no value set for darkmode.

Is there any place where I can find the colors to be set for dark mode?

**Comment by tiagoalvesdulce** [comment]
Yeah, this issue should be solved on pi-ui, it's a good issue to know that project a bit better.

We use CSS variables for the theming and toggle between themes with a react-hook. You can notice that we use a `ThemeProvider` component that comes from `pi-ui` to wrap our entire app here: https://github.com/decred/politeiagui/blob/d98c129f682396b62dbced069ae723710671304a/src/App.js#L59

You can check the implementation of our theming on `pi-ui` inside the `src/theme` directory. You will notice that we have a file for the light theme and one for the dark theme there. These files hold the definition of the variables for each theme.

This specific issue is related with the variables `warning-message-background` and `warning-message-color` not being defined in the `darkTheme.js` with the proper colors. Regarding the proper colors to use, I think we can go with the same colors used for the info message right now.

You can use `docz:dev` or yarn links to develop in `pi-ui`.

Here is the repo link: https://github.com/decred/pi-ui.
