### ISSUE TITLE
[CMS] Edit Contractor Info

### ISSUE THREAD

**Issue by tiagoalvesdulce** [decred/politeiagui#1920]
1. I think the edit icon is very small in the right top corner of the card and it's not clear that you have to click there to Edit your info. I think a button would be better.
2. The cursor of the mouse is not changing to pointer when hovering the edit icon, if we decide to keep it, we should fix it.
3. The spacings in this page could be improved. When you toggle to the Edit mode the space between the title of the Edit section and the DCC info section is bigger than the internal spaces of the Edit section, which is a poor UI.
4. If the user hasn't already filled their info and we don't have Contractor Info to show, we could show the Edit contractor form straight. There's no need to show empty contractor info. 

![edit](https://user-images.githubusercontent.com/13955303/81691293-f3eea380-9432-11ea-8e4d-cbad48adaf22.gif)

**Comment by amassarwi** [comment]
Also, empty field seem to be not focusable - I was able to navigate with tabs though.

**Comment by tiagoalvesdulce** [comment]
This page has one more issue. There's a lot to be solved. I'll work on it.

![issue](https://user-images.githubusercontent.com/13955303/85149040-37ed7900-b227-11ea-8133-70d4de910b43.gif)
