### ISSUE TITLE
[CMS] Description field losing focus if clicked multiple times on empty state

### ISSUE THREAD

**Issue by tiagoalvesdulce** [decred/politeiagui#1923]
![losing focus](https://user-images.githubusercontent.com/13955303/81821423-31713080-9508-11ea-9423-1c28f3769c29.gif)

The field should keep focused in this case.

**Comment by victorgcramos** [comment]
I think this behavior is caused by the tooltip component that wraps the text inputs

**Comment by tiagoalvesdulce** [comment]
Fixed on https://github.com/decred/politeiagui/pull/2027/
