### ISSUE TITLE
[CMS] Invoice spreadsheet enhancements

### ISSUE THREAD

**Issue by tiagoalvesdulce** [decred/politeiagui#1924]
1. Tab navigation can be improved in the entire new invoice page and in the spreadsheet.
    1. ~The focus should move from the Contractor Rate field to the first non-filled field of the spreadsheet.~
    2. The tab behavior inside the spreadsheet isn't right. Should focus on the next empty field instead of going all the way up to the logo of the app.

2. Much contractors use spreadsheets to keep track of their hours. We already support copy/paste if it is correctly formatted but the spreadsheet editor in the website isn't scaling if the user wants to paste multiple lines. For example, if you want to paste a 10 line spreadsheet you have to click `add row` 9 times and then paste it. Ideally, we would verify the number of lines and adapt the website editor accordingly.

**Comment by alexlyp** [comment]
I'd also like to suggest that the description field be fully selectable.  Currently I believe it just highlights the entire cell, but sometimes administrators like to copy just URLs etc

**Comment by tiagoalvesdulce** [comment]
I investigated and figured out that the Tooltip was messing up with the focus on tab navigation inside the datasheet. The Tooltip is causing other issues like https://github.com/decred/politeiagui/issues/2005 and https://github.com/decred/politeiagui/issues/1923. We can:

1. Try to improve the Tooltip component to work better with inputs (find a way to change its z-index or wrapper size when it's active, prevent it to mess up with the tab navigation and prevent it to "steal" the input focus).
2. Find another way to show errors in the datasheet.

cc: @victorgcramos @amassarwi @thi4go

**Comment by amassarwi** [comment]
@tiagoalvesdulce Thanks for investigating.
I'm fine with both ways, z-index solution may be not that sustainable for the long run, as I'm not sure if it's gonna work in *all* combinations.

I have idea for 2. we could show a global error message for all line items, we can please it on top, I'd still highlight the input with redish error state colors, but error text will be displayed in the the global message context.
This should work nicely on mobile screens as well.
