### ISSUE TITLE
Allow short token URLs

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#1939]
decred/politeia#1136 adds the ability to use shortened tokens, the first 7 characters of the token, to retrieve the proposal details.  This should also work for all routes that require the token as a route param.

Now that we can lookup proposals using the shortened token, we want to be able to reference proposals using shortened URLs.

https://proposals.decred.org/proposals/0230918

**Comment by lukebp** [comment]
In fact, it would be nice if the proposal URL defaulted to the shortened version (ex. when you select the proposal from the list view).  The main purpose of the shortened token is to make it easier for people to share links, so we want the default URL that they see to be the short one.

**Comment by amassarwi** [comment]
Nice one :+1: 
I would like to work on it
