### ISSUE TITLE
Workaround for timeout during anchoring

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#1941]
decred/politeia#1112 is a well known issue that keeps causing users a lot of problems.  This will be fixed with the new tlog backend, but that work is still in progress.  As a temporary workaround, can we prevent submitting comments in the gui starting at minute 58 of every hour and lasting for 5 minutes?  We should show an error message to the user explaining the situation.  Something along the lines of:

"Commenting temporarily unavailable while an hourly censorship resistance routine is in progress. Sorry for the inconvenience. This will be fixed soon. Check back in 5 minutes."

**Comment by victorgcramos** [comment]
on this!

**Comment by xaur** [comment]
I suggest make UX adjustments that are cheap to us while making the user aware of the situation as early as possible _and_ making best effort to prevent the loss of user's text (which is annoying and demotivating).

For example, at minute 57 (1 min in advance), add an orange banner in a very visible place (e.g. at the bottom of the text box or near the Comment button). We may want to allow the user to use the text box and the Preview tab to keep writing, but inform that he should delay publishing or even block the Comment button.

If there is infrastructure in place to save the draft in local storage, that would be an extra step to prevent data loss (although it's a whole new feature with its own UX flows, a bunch of code and state bugs).

As for the moment when to lift the restriction, ideally it should be not "after 5 minutes" but when the anchoring (or any other backend jobs blocking the database) is finished, to cover the edge cases where it takes longer than 5 minutes. But if there is no API to know that, a 5 minute heuristic may work for now.

**Comment by lukebp** [comment]
> As for the moment when to lift the restriction, ideally it should be not "after 5 minutes" but when the anchoring (or any other backend jobs blocking the database) is finished, to cover the edge cases where it takes longer than 5 minutes. But if there is no API to know that, a 5 minute heuristic may work for now.

There's not way to do that.  It usually takes about 3 minutes, so use 5 minutes to be safe.

This is just a temporary workaround so it doesn't need to be fancy.  Keep it simple.  We'll get this in for the upcoming RFP release then the release after that will be the tlog release that fixes the issue.

**Comment by xaur** [comment]
What about comment up/down votes? Do they too need to be blocked as part of this workaround?

I didn't look at them closely, but sometimes I get a feeling that they aren't cast after 58th minute too.

**Comment by xaur** [comment]
Checked again and yes, if I cast up/down votes on comments after 58th minute, they are quietly undone after what appears to be an error timeout. This is not right because the immediate speculative UI feedback fools the user to believe his vote was delivered while it was not. This sounds very similar to an issue reported in #1792, but in the context of the anchoring workaround.
