### ISSUE TITLE
[cms] Error after doing a subcontractor line item invoice

### ISSUE THREAD

**Issue by alexlyp** [decred/politeiagui#1946]
I'm receiving the following error when trying to view the details of an invoice that includes a just a line item for a subcontractor:

`methods__WEBPACK_IMPORTED_MODULE_11__.default.RECEIVE__RECORD_COMMENTS is not a function`
onFetchInvoiceComments/</<
src/github.com/decred/politeiagui/src/actions/api.js:301

The user that created the invoice is set as a supervisor and the test subcontractor was properly populated and selected in the dropdown in the new invoice form.

**Comment by alexlyp** [comment]
This was due to not doing a `--buildcache` on politeiad after the recent token prefix PR

**Comment by victorgcramos** [comment]
on this!
