### ISSUE TITLE
[cms] Allow viewing of older versions of Invoice Details

### ISSUE THREAD

**Issue by alexlyp** [decred/politeiagui#1948]
I envision this would work exactly like proposals.  A little dropdown on the version (when it's != 1) that would allow the user or the administrator to select and view that version of the invoice.

This requires. https://github.com/decred/politeia/pull/1200

**Comment by victorgcramos** [comment]
On this!

**Comment by victorgcramos** [comment]
holding this one a little bit until RFP gets deployed. After that, i'll be back to this!
