### ISSUE TITLE
[rfp] RFP Icon Font is different from platform's default font

### ISSUE THREAD

**Issue by victorgcramos** [decred/politeiagui#1952]
Just noticed that this icon is looking a bit weird.

> @victorgcramos regarding the icon font, I've discussed it with @tiagoalvesdulce and ideally we should get a different .svg, the problem is that we use plain text inside the .svg which uses the default browser font-family, I will try fix it with css, but ideally this should be part of the .svg I mean the letters should be also vectors and not plain text, this will also fix the scaling problems we have, on some screens the tag looks a bit like a rectangle.

_Originally posted by @amassarwi in https://github.com/decred/politeiagui/issues/1951#issuecomment-635665082_

<img width="819" alt="Captura de Tela 2020-05-28 às 18 06 03" src="https://user-images.githubusercontent.com/22639213/83203660-4cef5480-a120-11ea-836c-34e6d1a786e5.png">

**Comment by MariaPleshkova** [comment]
Try this one:
[rfp_tag_svg_txt.svg.zip](https://github.com/decred/politeiagui/files/4700191/rfp_tag_svg_txt.svg.zip)

**Comment by amassarwi** [comment]
@MariaPleshkova Thanks, will give it a try

**Comment by amassarwi** [comment]
.svg replaced on #1957
