### ISSUE TITLE
Dark Mode toggle only available for logged in users

### ISSUE THREAD

**Issue by victorgcramos** [decred/politeiagui#1960]
Just noticed that we don't display the **Dark Theme** toggle for not logged in sessions, because it is only displayed the user's options dropdown

When user is not logged in
<img width="1157" alt="Captura de Tela 2020-05-29 às 16 49 25" src="https://user-images.githubusercontent.com/22639213/83299351-6221bd00-a1cc-11ea-89d3-d7dd66ed8180.png">

User logged in
<img width="1250" alt="Captura de Tela 2020-05-29 às 16 52 26" src="https://user-images.githubusercontent.com/22639213/83299597-dfe5c880-a1cc-11ea-82eb-58931df6b5d4.png">

**Comment by amassarwi** [comment]
@victorgcramos Nice one, on this!
