### ISSUE TITLE
[rfp] Invalid RFP Proposal deadline

### ISSUE THREAD

**Issue by victorgcramos** [decred/politeiagui#1963]
Got this error when selecting the **first** available date on RFP Proposal deadline:

`74 invalid proposal linkby: linkby period cannot be shorter than 1209600 seconds`
<img width="1233" alt="Captura de Tela 2020-05-28 às 16 54 44" src="https://user-images.githubusercontent.com/22639213/83193637-c6ca1280-a10d-11ea-8725-968ceef81539.png">

_Originally posted by @victorgcramos in https://github.com/decred/politeiagui/issues/1951#issuecomment-635607494_

We should also add this `74` error code into our error helpers, so we can display a user-friendly error message.

**Comment by victorgcramos** [comment]
On this!

**Comment by amassarwi** [comment]
@victorgcramos This could be time zone issue, we get a second timestamp for BE and we convert it to json date ` { day, month, year } ` and then we user picks the first date, we take the last minute of that day and convert it to seconds timestamp without TZ considerations, I guess this cause this error in some rare edge cases when the timestamp is close to end of day.

**Comment by victorgcramos** [comment]
I'll investigate this issue then! Thanks for the advice, let's see if I can replicate this easily! 🤙🏼

**Comment by amassarwi** [comment]
Great mate, I think I have quite simple not complicated way to fix this, you could check in our submit, after converting the date to seconds timestamp that the value is **not** less than the BE value, and if it yes, we can submit the min value instead.
What do you think?

**Comment by victorgcramos** [comment]
I like the solution! Thanks!

**Comment by victorgcramos** [comment]
After investigating this, I couldn't replicate the error. What @amassarwi said has a very remote chance to happen again (once in 86400) so i'm closing this issue.

**Comment by amassarwi** [comment]
After checking the exact timestamp in BE logs this seems like a BE issue.
