### ISSUE TITLE
Proposals with too much info are not responsive in the proposal list

### ISSUE THREAD

**Issue by tiagoalvesdulce** [decred/politeiagui#1971]
There's too much content to be shown between 635px and 900px sizes. See:

635px:
![Screen Shot 2020-06-03 at 15 41 56](https://user-images.githubusercontent.com/13955303/83676458-13e83180-a5b1-11ea-9847-77b45a8e2787.png)

900px:
![Screen Shot 2020-06-03 at 15 42 40](https://user-images.githubusercontent.com/13955303/83676416-029f2500-a5b1-11ea-9508-54af7b7ea912.png)

**Comment by amassarwi** [comment]
Closed in #1974
