### ISSUE TITLE
Account dropdown menu is clickable but invisible

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#1973]
When I click the account dropdown, the menu is not shown. However, when I hover the mouse at where the items should be, the pointer changes and I can click them to actually open the Account page or Logout.

Using Firefox.

![dropdown-1](https://user-images.githubusercontent.com/24484727/83682884-0d1ee600-a5d4-11ea-8883-82f8926ccaa9.png)
![dropdown-2](https://user-images.githubusercontent.com/24484727/83682892-1019d680-a5d4-11ea-9321-538339c2a1d3.png)

**Comment by lukebp** [comment]
This cannot be reproduced on master.  We're about to do a production update in the next week or so with a lot of frontend changes.  There's a high likelihood that this already fixed so I'm closing this issue.  If you can reproduce it on test-proposals then we can open it back up, but we haven't been able to reproduce locally.

**Comment by tiagoalvesdulce** [comment]
Related to https://github.com/decred/politeiagui/issues/1972#issuecomment-641543605

**Comment by xaur** [comment]
Happy to report that menu drop down list became visible on the CMS after the latest deployment. I wonder if the same fix can be applied to Politeia, where it is still not visible for me?

**Comment by amassarwi** [comment]
This was fixed on master, it should work for you after next pigui deployment
