### ISSUE TITLE
Duplicate RFP submission requests

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#1987]
Duplicate `/proposals/batch` and `/proposals/batchvotesummary` are being sent.

https://test-proposals.decred.org/proposals/0de5bd8

**Comment by lukebp** [comment]
I also noticed that on the landing page, a `/proposals/batch` request is sent for each RFP submission in order to fetch the RFP proposal title.  Currently, there are two RFP submissions for the "Build a Decred Citadel" RFP proposal.  Because there are two submissions, duplicate requests are being sent to fetch the "Build a Decred Citadel" proposal title.

Should this request not be batched?

**Comment by amassarwi** [comment]
> Duplicate /proposals/batch and /proposals/batchvotesummary are being sent.

Looking at it.

> I also noticed that on the landing page, a /proposals/batch request is sent for each RFP submission in order to fetch the RFP proposal title. Currently, there are two RFP submissions for the "Build a Decred Citadel" RFP proposal. Because there are two submissions, duplicate requests are being sent to fetch the "Build a Decred Citadel" proposal title.

Currently we fetch the RFP title for each proposal card displayed on the list separately.
When displaying a proposal card we check if it's a RFP submission then we fetch the RFP details using the batch call.
We will need somehow to parse the displayed list when list's data fetched, check if there are any submissions, check if RFPs where already fetched as part of the displayed list, fetch batch of all missing RFPs and fill titles for submissions and store the titles in the gui state.

Also, currently we re-fetch the titles on each tab switch as we don't cache the titles in the application state, the solution above is handling this case as well.

**Comment by amassarwi** [comment]
#2007 should fix this first part:

>Duplicate /proposals/batch and /proposals/batchvotesummary are being sent.
>
> https://test-proposals.decred.org/proposals/0de5bd8

**Comment by amassarwi** [comment]
As the issue in the title was fixed this issue is a bit confusing.
I'm closing it and will open a separate issue to describe the multi extra calls we fire to fetch submissions info.
