### ISSUE TITLE
CSRF bug in Brave

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#1991]
There appears to be a CSRF bug when using Brave browser.  Elian reported that he was receiving a 403 when trying to create a new user on test-proposals.  Clearing cookies did not fix the issue.  He was able to create a new user when he switched to Firefox.

**Comment by lukebp** [comment]
Per the conversation in matrix, this could be unrelated to Brave and instead be a general problem with the gui not properly clearing out expired CSRF tokens properly.

**Comment by tiagoalvesdulce** [comment]
I'm closing because I couldn't repro and it might be something with his Brave setup (extensions, plugins, etc.). Feel free to reopen if this happens to other users.
