### ISSUE TITLE
upgrade react-mde commands

### ISSUE THREAD

**Issue by victorgcramos** [decred/politeiagui#1993]
Noticed this after upgrading our `react-mde` package to the latest version. `commands` module is no longer exported, so we need to handle these changes on `MarkdownEditor` https://github.com/decred/politeiagui/blob/450e34fb5b8f60d8c0c83949332dadd44f2006f7/src/components/MarkdownEditor/commands.jsx#L2

**Comment by tiagoalvesdulce** [comment]
Fixed on https://github.com/decred/politeiagui/pull/2158
