### ISSUE TITLE
[darktheme] ContentLoader showing light colors in some pages

### ISSUE THREAD

**Issue by amassarwi** [decred/politeiagui#1995]
Currently only the proposal loader showing dark colors using the provided theme to show loading place holders.

Proper usage:
https://github.com/decred/politeiagui/blob/master/src/components/Proposal/ProposalLoader.jsx#L21

Hardcoded light colors example - there are few more in code base:
https://github.com/decred/politeiagui/blob/master/src/components/CommentForm/CommentFormLoader.jsx#L9

**Comment by victorgcramos** [comment]
On this!
