### ISSUE TITLE
[cms] Click on '6 months' filter leads to undefined month name

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#2003]
- Go to 'my invoices' page
- Click the '6 months' filter
- The initial month appears as undefined

<img width="441" alt="Screenshot 2020-06-14 at 12 12 22" src="https://user-images.githubusercontent.com/14864439/84590613-638fee00-ae38-11ea-96d4-61b70a16f9eb.png">

**Comment by amassarwi** [comment]
Having a look
