### ISSUE TITLE
[cms] cell cursor is hard for editting

### ISSUE THREAD

**Issue by vctt94** [decred/politeiagui#2005]
Right now if you want to edit a specif part of the text, of a description, for example, this cell cursor makes it much harder.

It would be good if we change it for a diffrent cursor

**Comment by victorgcramos** [comment]
After double-clicking the cell, the cursor should change to text editing cursor.

Check this:
![cell-cursor](https://user-images.githubusercontent.com/22639213/84707006-548e6600-af34-11ea-90bc-f6faacb99ef3.gif)

**Comment by vctt94** [comment]
I see. So that's probably a different bug and looks like it only happens when the cell is empty

**Comment by victorgcramos** [comment]
Got it. This happens when the cell is error-marked. I guess this happens because the Tooltip overlaps the input.
![cell-cursor-errored](https://user-images.githubusercontent.com/22639213/84711368-8c99a700-af3c-11ea-9408-d0fa96a434a0.gif)

**Comment by tiagoalvesdulce** [comment]
Fixed on https://github.com/decred/politeiagui/pull/2027/
