### ISSUE TITLE
Improve paywall blocking proposal submission

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#201]
As far as I understand the Submission Proposal button on the right sidebar is being blocked while the user hasn't confirmed its payment. However there are a few improvements that can be done:
- The route itself isn't being blocked. I can easily access the submission page typing`proposals/new` in the URL. We should either block any way to access this route or let the user access the route but show an error when trying to submit a new proposal. Also If we keep blocking the button which leads to `proposals/new` this button should be disabled. 

- **This is might be a non-issue soon but I wil report it as I see right now:** If access the politeia running the backend (e.g `yarn start`) and then login using the `politeiawww_refclient` this client hasn't paid its fee so it needs a way to access the paywall. I couldn't find a way to see the paywall address besides after signing up.

**Comment by sndurkin** [comment]
Regarding your first comment, the server will either send an error when the user tries to submit a new proposal before having paid, or the admins will be notified if the user hasn't paid yet. This functionality doesn't exist in the server yet but will be added soon.

I'm not sure what to do about the refclient yet, I'll have to see what Marco wants to do about that. The paywall address is sent via the [login reply](https://github.com/decred/politeia/blob/master/politeiawww/api/v1/api.md#login-reply).

**Comment by fernandoabolafio** [comment]
Regarding the question **Block proposal submission route?** 
I see it as something we have to carefully handle since the user can spend a considerable time writing his proposal and realize that he cannot submit it yet what can be quite frustrating(**1**). In another hand, since he already wrote his proposal it might encourage him to pay the fee and go forward with the submission (**2**).
I would bet that 2 is the scenario we want. And instead of blocking the route we can provide good information that he won't be able to submit before paying, however, he can write his proposal on our Editor. 
Once #218 goes in the text will be persisted during the session time. But we need to make sure that he may save his text in another place if he can't pay the fee at that moment.

**Comment by fernandoabolafio** [comment]
This is fixed already.
