### ISSUE TITLE
[cms] Admin page for proposal billing summary

### ISSUE THREAD

**Issue by alexlyp** [decred/politeiagui#2019]
There are 2 new admin requests being added to politeiawww:
https://github.com/decred/politeia/pull/1224

We'd like to add a new administrator page that will show a list of all approved proposals along with their title and their total billed amount.

Then when an administrator clicks on a proposal, it can display all of the individual invoice and line item information in a orderly fashion.  Maybe cells or a grid that has each line item shown with username, their rate and how much they were billing for that line item.  That's a little different than pure line item information due to have the contractor name and rate information.

**Comment by xaur** [comment]
Nice, per-line-item rate is flexible and future-proof. Eg. the same person can get two proposals with different rates approved.
