### ISSUE TITLE
Huge gap in network requests

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2038]
The proposal details page load times are extremely slow because of a huge gap in the network requests.  What's going on here?

<img width="1675" alt="image" src="https://user-images.githubusercontent.com/9039877/86253258-8842d000-bb71-11ea-8400-703049d86712.png">

**Comment by victorgcramos** [comment]
on this!

**Comment by lukebp** [comment]
Firefox is not showing the download time of the request payload in the chart. That's what it taking so long.  This particular proposal had an image attachment that was causing the delay.
