### ISSUE TITLE
Avoid multiple local calls to fetch RFPs & submissions information

### ISSUE THREAD

**Issue by amassarwi** [decred/politeiagui#2043]
As was reported here by @lukebp:
> I also noticed that on the landing page, a /proposals/batch request is sent for each RFP submission in order to fetch the RFP proposal title. Currently, there are two RFP submissions for the "Build a Decred Citadel" RFP proposal. Because there are two submissions, duplicate requests are being sent to fetch the "Build a Decred Citadel" proposal title.

And also on matrix by @lukebp as well: 

> Clicking the "Start Runoff Vote" button fires off a proposal details and a vote summary request. Curious as to why that is when all that data has already been loaded on the page.

Currently we fetch the RFP title for each proposal card displayed on the list separately.
When displaying a proposal card we check if it's a RFP submission then we fetch the RFP details using the batch call.
We will need somehow to parse the displayed list when list's data fetched, check if there are any submissions, check if RFPs where already fetched as part of the displayed list, fetch batch of all missing RFPs, fill titles for submissions and store the titles in the gui state and part of the submissions payload.

Same hold for RFP submissions information in scenarios like starting run off and showing vote progress of submissions in RFP details view, in all these cases pre-fetching the information and storing in redux store would prevent all these extra local calls.

**Comment by victorgcramos** [comment]
on this!

**Comment by amassarwi** [comment]
@victorgcramos 🚀
