### ISSUE TITLE
[cms] Exchange rate error when submitting a draft

### ISSUE THREAD

**Issue by thi4go** [decred/politeiagui#2056]
CMS is giving a exchange rate error when we try to submit draft invoices. Same exact invoice gets submitted propertly when not in draft mode, and gives an error when submitting on draft. see below

![Screenshot from 2020-07-13 12-52-35](https://user-images.githubusercontent.com/2729122/87325562-f7bca600-c507-11ea-8f51-0f04c7878bcf.png)

**Comment by alexlyp** [comment]
Yah I've noticed this as well.  I believe the exchange rate isn't being added to the payload being sent to cmswww.  If you select a different month/year then select back to the desired month it'll work.
