### ISSUE TITLE
Proposals: domain category filtering

### ISSUE THREAD

**Issue by linnutee** [decred/politeiagui#2069]
Bringing this up, if the categories implementation is still of interest and in the backlog, as the domains are present in CMS already. Should probably reflect the same domains as in CMS?

From a UX standpoint, it's possibly one of the simplest ways to increase visibility on the big picture, ie. which domains are getting attention and which are not. Also would provide opportunity to build further insight related features on top of those, 
re: https://github.com/decred/politeia/issues/678

There's a simple design pattern ready how they could be interacted with, as possibly a second filtering layer below the status categories (applied to each of them): https://xd.adobe.com/view/44a3298e-a814-42b2-643e-3aa39c8dec34-3292/screen/fd5e3ea1-7702-49a8-a171-05fef2eeb570/ (ignore the placeholder content on cats)

```
(All)
domain 1, domain 2, etc

(Voting)
domain 1, domain 2, etc

(Approved)
domain 1, domain 2, etc

(Rejected)
domain 1, domain 2, etc

(Abandoned)
domain 1, domain 2, etc
```

**Comment by tiagoalvesdulce** [comment]
I agree that the pi categories should reflect the same domains as in CMS. @thi4go is working on that here https://github.com/decred/politeia/pull/1214.

**Comment by xaur** [comment]
Proposal categories require capturing additonal metadata. On the backend, https://github.com/decred/politeia/pull/1214 was canceled and instead domains will be handled by https://github.com/decred/politeia/issues/1442 . On the frontend the new metadata will be handled by https://github.com/decred/politeiagui/issues/2459 .

**Comment by lukebp** [comment]
I've added this to the feature request thread (#2578).  I support this feature and will include it in a future pi proposal.
