### ISSUE TITLE
Set Politeia's logo as favicon

### ISSUE THREAD

**Issue by StabbarN** [decred/politeiagui#207]
The favicon and Polieia's logo is different. In my opinion, they should be the same, for consistency.

<img width="465" alt="screen shot 2018-02-07 at 21 10 15" src="https://user-images.githubusercontent.com/921390/35939161-97cee7b6-0c4b-11e8-85c1-67039222eb80.png">

**Comment by sanketsingh24** [comment]
Shall I work on this issue as my first PR ?

**Comment by StabbarN** [comment]
@sanketsingh24 Sure, that's fine for me.

**Comment by sanketsingh24** [comment]
Which color should favicon be?

**Comment by StabbarN** [comment]
I don't know but I guess white would be better. Do a pull request or ask in the Slack channel #politeia.
