### ISSUE TITLE
Explain how long it takes to update proposal credit balance

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#2070]
I sent DCR to purchase credits but 8 blocks after the tx was mined Politeia has still not credited it.

There are two issues here:

1. The UI has no text suggesting how long the user needs to wait after sending his transaction.
2. Politeia is not picking up the transaction immediately, as most crypto services do (e.g. "we do see your transaction in the mempool but please wait X confirmations (~Y minutes)")

**Comment by lukebp** [comment]
This is being fixed soon.  The backend is switching to dcrdata websockets which will allow the frontend to pick up transactions immediately show real time confirmations.  Work is in progress.

**Comment by xaur** [comment]
Great, thanks. Item 2 is in progress then. But I would still add a bit of text communicating the wait time. Even after the switch, the text could serve as a fallback in case anything happens to the dcrdata websocket.

**Comment by vibros68** [comment]
Hi. I am working on it
