### ISSUE TITLE
searching votes messes up proposal view

### ISSUE THREAD

**Issue by degeri** [decred/politeiagui#2072]
Clicking on the "search" button and then closing the modal cause the stats and information on a proposal to go missing. 

![image](https://user-images.githubusercontent.com/41839293/88304142-2b69ae00-cd08-11ea-8197-3f4ce3329c6a.png)

Before:
![image](https://user-images.githubusercontent.com/41839293/88304311-64a21e00-cd08-11ea-8b60-e55eae7d3a7f.png)

After:
![image](https://user-images.githubusercontent.com/41839293/88304343-6f5cb300-cd08-11ea-8fb6-ca8dc036b3d5.png)

**Comment by victorgcramos** [comment]
on this!
