### ISSUE TITLE
Confirmation dialog before submitting a proposal

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#2076]
Proposal submission is an irreversible operation that reduces the proposal credits balance.

I suggest to add a confirmation dialog to protect the users from accidentally clicking Submit button. Proposal submission is not a frequent operation so it shouldn't be to annoying.

**Comment by lukebp** [comment]
I don't think this is an issue and is excessive.  Users can edit their proposals if they find any mistakes in them after they submit.

**Comment by xaur** [comment]
Good point. If the mistake was in the text, edit feature does handle that. However, if the submission itself was a mistake, there is no feature to withdraw it (before admin published it) and refund the proposal credit. Anyway, thanks for considering.
