### ISSUE TITLE
Show status of proposals under review on the home page

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#2077]
I submitted a proposal, navigated to https://proposals.decred.org/ and see no indication that I have any proposals pending review. If I open my account and click Proposals tab, it is there.

The user always needs feedback to know that his actions were correct.

I suggest to add a label somewhere that clearly informs the user of the status of his unpublished proposal(s). A good place for it is the top bar before the `proposal credits` label, e.g.:

```
Politeia          pending proposals: 1 | proposal credits: 0 (+) | username (v)
```

Clicking `pending proposals` should take to the list of all submitted proposals that are not published, along with their statuses.

I didn't test the drafts feature. If the existence of drafts is not communicated like this, it can be included in the list too, so that the user never forgets about his draft.

Design issue to consider: adding another wide text label to the top bar might affect responsive design.

**Comment by lukebp** [comment]
This is a design issue that breaks the existing framework.  If you would like to discuss this change it needs to be discussed with the design team.

**Comment by xaur** [comment]
Sorry I don't understand. I propose a feature for the Politeia product and not a "Decred design"-wide change. I have submitted many issues in the past and this is the first time I am forwarded to a design repo to discuss a change specific to one product.
