### ISSUE TITLE
Support `quiesce` mode

### ISSUE THREAD

**Issue by amass01** [decred/politeiagui#2078]
`Quiesce` mode is being added to the BE, see https://github.com/decred/politeia/pull/1253, to give the admins a way to switch the BE to readonly mode
that they could backup politeia safely.

BE will be emitting a websokcet event each time an admin sets new `quiesce` mode value, we would like to add a redux middleware as described in [this article](https://dev.to/aduranil/how-to-use-websockets-with-redux-a-step-by-step-guide-to-writing-understanding-connecting-socket-middleware-to-your-project-km3) to be able to receive the WS notification from BE.

Credits to @tiagoalvesdulce for the approach and article.

**Comment by lukebp** [comment]
This is no longer required.
