### ISSUE TITLE
[cms] Proposal Billing Details page

### ISSUE THREAD

**Issue by alexlyp** [decred/politeiagui#2086]
Need to add a couple of columns and fix the total calculations.

Add Labor and Expense columns and make sure Totals in USD and DCR reflect that.

Currently it's just tabulating labor so on expense line items it's 0 for those line item types.

Also make sure that Sub contractor line item types are handled accordingly as well.

**Comment by victorgcramos** [comment]
on this!

**Comment by victorgcramos** [comment]
Waiting for https://github.com/decred/politeia/pull/1286
