### ISSUE TITLE
Show reason of comment censorship

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#2092]
https://proposals.decred.org/proposals/32cba00 is the first proposal where I noticed "Censored by moderators" message. It would be great to show a short reason text, e.g.

> Censored by moderators (off-topic)

**Comment by lukebp** [comment]
I agree the reason for censoring should be shown, but this needs to be added to the backend first.  That data is not currently returned from the api.

**Comment by amassarwi** [comment]
I can add that to BE side as well - will create an issue for that as well

**Comment by lukebp** [comment]
@amassarwi I wouldn't.  All of the plugins are being re-written for tlog, so any changes you made now would be replaced when we migrate to tlog, which is going to be the next update.  I made a note to return this data in the new tlog comments plugin so adding it once we launch tlog will be simple.

**Comment by amassarwi** [comment]
@lukebp I see, make total sense.

**Comment by lukebp** [comment]
This was added in #2454.
