### ISSUE TITLE
Proposal credit workflow bugs

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2108]
- The modal "Waiting for payment" tag does not update when the tx is registered.  You can see the tx show up in the payments list in the background, but the modal still displays the "Waiting for payment" tag.

![Screenshot from 2020-08-14 10-27-31](https://user-images.githubusercontent.com/9039877/90265856-cb52bd00-de18-11ea-8f49-0636fbd7b970.png)

- If you refresh the modal once the tx is registered, the tag will say "Waiting for confirmations" and will still be the same yellow color as the "Waiting for payment" tag.  I found this to be confusing from a UX standpoint for two reason. Its the same color as the previous "waiting for payment" tag so its hard to notice the change and it's different from the tag being shown in the payments list.  Seems like the modal tag and the list tags should be consistent.

![Screenshot from 2020-08-14 07-55-07](https://user-images.githubusercontent.com/9039877/90251658-bf103500-de03-11ea-8d72-32ef3f8dea54.png)

- Purchase more than one proposal credit (ex. 4). The modal will say "Send 0.4 dcr to...".  Close the modal and open it back it.  The modal now says "Send 0.1 dcr to..." when it should still say "Send 0.4 dcr to...".

- If you click the "Purchase more" button while the tx is pending then it opens correctly.  Once the tx has been confirmed, clicking the "Purchase more" button doesn't do anything.  You need to refresh the page to get the modal to open properly again.

**Comment by victorgcramos** [comment]
on this!
