### ISSUE TITLE
Add rules to New Proposal page

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#2116]
Some authors are not informed about the unwritten rules and make common mistakes like express the budget in DCR instead of USD or don't include an actionable plan. I guess not everybody clicks "Proposal Guidelines".

It would be good to put the most critical info in front of proposal authors at the proposal page. A good place for that is after proposal text field but before Submit button.

Rules I'm currently aware of, plus I'd move the guidelines link into the bullet list so that authors encounter it after scaning the rules list:

- Expenses must be denominated in USD (but will be paid in DCR)
- The work will be paid next month after the month it was done, as explained [here](https://docs.decred.org/contributing/contributor-compensation/)
- Proposal must include actionable plan
- Check [Proposal Guidelines](https://docs.decred.org/governance/politeia/proposal-guidelines/)

**Comment by RichardRed0x** [comment]
Good idea to make these more prominent.
