### ISSUE TITLE
Comment URLs do not use short proposal IDs

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#2118]
When I navigate the Politea UI I get short links like:

https://proposals.decred.org/proposals/7a67ed5

but when I copy comment permalink I get the long token:

https://proposals.decred.org/proposals/7a67ed5a1f9965c034d87ff2b6f3580f07e3567250394b5c885c9392ccd85134/comments/1

Would be nice to have this consistent.

Note that there are at least two ways to get comment URL: by right-click + copy the timestamp, and by left-clicking the chain icon in bottom right.

**Comment by lukebp** [comment]
This is not currently supported by the backend yet.

**Comment by lukebp** [comment]
This is being built into the tlog backend, so once that is released this issue can be picked up.

**Comment by degeri** [comment]
hmm this already works and only needs a js level change . 

I already reported this and its been fixed. 

https://github.com/decred/politeiagui/pull/2100

lmk if I am completely misunderstanding this.

**Comment by xaur** [comment]
Look like we can close this as duplicate then and wait for the next deployment.
