### ISSUE TITLE
Copy to clipboard does not work in Firefox

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#2119]
When clicking the chain icons in the bottom right of the proposal body or a comment, I get this in the console:

> document.execCommand(‘cut’/‘copy’) was denied because it was not called from inside a short running user-generated event handler.

A quick search suggests it has something to do with click handlers:

https://stackoverflow.com/questions/41094318/firefox-document-execcommand-cut-copy-was-denied-because-it-was-not-calle

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard

**Comment by lukebp** [comment]
I'm not able to reproduce this.  All copy functionality (copy token, copy proposal link, copy comment link) is working fine in firefox on my end.

**Comment by xaur** [comment]
Oops I had `dom.allow_cut_copy` disabled. Enabling it makes all three use cases work. Sorry for false report. I'm closing this.
