### ISSUE TITLE
Add proposal filter to Admin page

### ISSUE THREAD

**Issue by tiagoalvesdulce** [decred/politeiagui#212]
The admin page can look a bit messy showing censored and unreviewed proposals together. I think we should display a filter with Censored, Unreviewed and All options to control the type of proposals to show.

<img width="1280" alt="screen shot 2018-02-16 at 21 51 12" src="https://user-images.githubusercontent.com/13955303/36335081-7cb39c0e-1364-11e8-8b9a-cc97b972ab27.png">

**Comment by sndurkin** [comment]
This would be great to have, and maybe we can either save the user's preference in local storage or always default it to show only Unreviewed?

**Comment by tiagoalvesdulce** [comment]
I'd say that always default it to show unreviewed should work great
