### ISSUE TITLE
totp: Add Set/Verify TOTP in account area

### ISSUE THREAD

**Issue by alexlyp** [decred/politeiagui#2120]
This will be available in both cms and proposals.

This is the basic functionality for the Set and Verify TOTP:
1) A user requests to SetTOTP (can be a button) on a new accoun tab.
2) www returns a secret and an image (QR code png in bytes).
3) Display the QR code and add a Verification Code field below.
4) User enters a valid code from their TOTP client application and clicks verify.
5) Success message is shown if valid and they are all set for TOTP.

**Comment by victorgcramos** [comment]
I would like to work on this!
