### ISSUE TITLE
[cms] Revert proposal column changes

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2130]
#2016 may seem like it improves UX, but if you talk to the contractors that submit invoices you'll see that this makes things harder, not easier.  The workflow that most contractors use is:

1. Use some time tracking software to track work
2. Import time tracking data into a spreadsheet and format it correctly
3. Copy and paste it into cms

Using the proposal name breaks this workflow becuase you can't currently paste into the proposal column and even if you could, using a token is far simplier since its less likely to have formatting errors.  The user now has to go through every line item and select the proposal manually.  This is a huge pain.

Copy and pasting, even when the proposal column is blank, currently causes an infinite loading icon.

Allowing short proposal tokens would improve the UX more than using the proposal name.  If you want to show the name, show it in a tooltip or something.  #2123 should also be closed.

**Comment by victorgcramos** [comment]
On this!

**Comment by lukebp** [comment]
@victorgcramos I'd wait for @alexlyp to comment and ok these changes.

**Comment by tiagoalvesdulce** [comment]
Fixed in https://github.com/decred/politeiagui/pull/2301
