### ISSUE TITLE
Setup docker for politeia

### ISSUE THREAD

**Issue by tiagoalvesdulce** [decred/politeiagui#2135]
I am working on writing e2e tests for pgui (https://github.com/decred/politeiagui/issues/976). Would be really nice if we could include the e2e tests in our CI pipeline. In order to do that we need to setup a docker container to build and run cockroachdb, politeiad, politeiawww and politeiagui.

We also need user accounts to run the tests. I think that 3 users is enough:

1. Non-admin, non-paid user
2. Non-admin, paid user with 1 proposal credit
3. Admin, paid user with 100 proposal credits

**Comment by degeri** [comment]
Got this
