### ISSUE TITLE
Downvote button not showing

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2138]
The downvote button gets cut off on a 14'' screen.  I'm using Firefox.

![Screenshot from 2020-09-23 14-30-52](https://user-images.githubusercontent.com/9039877/94060446-99366280-fda9-11ea-8d61-7479e83f2cf4.png)

**Comment by tiagoalvesdulce** [comment]
Related to https://matrix.to/#/!ueeciPqvqEsPyPCJkp:decred.org/$fPGsDJR0qdJfoqSd6HPx6noo7BVlEwqEw6GRdBQi7xY?via=decred.org&via=matrix.org&via=planetdecred.org
