### ISSUE TITLE
About Politeia on small screens

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2140]
The "About Politeia" section looks pretty bad on a 14'' screen.

![Screenshot from 2020-09-24 08-57-15](https://user-images.githubusercontent.com/9039877/94155249-5aa1b600-fe44-11ea-959c-b3c57fb701a0.png)

**Comment by victorgcramos** [comment]
This looks like a PI-UI issue. I'll create it there and link it.

**Comment by brunaazambuja** [comment]
This issue was already resolved on pi-ui repository. PR: https://github.com/decred/pi-ui/pull/321

**Comment by xaur** [comment]
Related: #843
