### ISSUE TITLE
Inline markdown images

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2143]
This issue is meant to serve as a discussion on the topic of adding the ability to reference and render proposal image attachments inline in the proposal markdown file.

Is this feasable?
How would it work?
What work would be required?

**Comment by tiagoalvesdulce** [comment]
Hey, that's a good idea.

**Is this feasible?**
Yes, it is.

**How would it work?**
We have to allow users to upload images through the markdown editor and render them with the markdown renderer in the right placement.

**What work would be required?**
React-mde (our editor) currently allows image upload (https://github.com/andrerpena/react-mde/issues/189) and react-markdown (our renderer) allows the rendering of images (https://github.com/rexxars/react-markdown#node-types). We have to make sure we use the versions that support images and adapt our code. More importantly, we have to guarantee that we are applying the XSS filters to the markdown rendered images.

**Comment by victorgcramos** [comment]
I agree with @tiagoalvesdulce.

**Comment by lukebp** [comment]
Sounds like a plan.  Let's get this going.
