### ISSUE TITLE
See competing proposals for a RFP 

### ISSUE THREAD

**Issue by icedice1** [decred/politeiagui#2145]
It would be great from a UX perspective to be able to read a proposal for a RFP, then scroll and see an overview of the competing ones with links for further exploration.  

Example: 
![Web 1920 – 1](https://user-images.githubusercontent.com/44898172/94428177-91ebcc00-0190-11eb-9968-bff562ca21d4.png)

**Comment by icedice1** [comment]
The current option to get an overview is to either press the link: ''RFP: change the messaging on decred.org'' within a proposal.

Or navigating to Approved -> ''RFP: change the messaging on decred.org''

The solution i propose is getting the overview of all competing proposals after examining one of them.

**Comment by lukebp** [comment]
Thanks for the suggestion icedice1, but I disagree with this.  The proposal page shows all data of the selected proposal.  Adding the list of other submissions to all submission pages strikes me as too much, adding clutter to the page and displaying data that doesn't belong to the proposal.  All RFP submissions are already shown under the "Discussion" tab of the politea home page and can also be seen by navigating to the RFP proposal page, where they're listed in full.  I think this will suffice for now.
