### ISSUE TITLE
[cms] Choose line to be removed

### ISSUE THREAD

**Issue by vctt94** [decred/politeiagui#2149]
Right now, if clicking on remove item the last invoice line will be removed:

![image](https://user-images.githubusercontent.com/15069783/94926495-48082c00-0497-11eb-8fc5-932d58cb149c.png)

The problem is, not always the last line is the one we want removed, so having a way to choose a line, instead of always removing the last one, would be good.

**Comment by tiagoalvesdulce** [comment]
Thanks for the suggestion but this will be too complicated to implement and it's not worth the time. If you want to remove a line other than the last one you can copy the content from the last line and paste it into the line you want to delete and just remove the last one.
