### ISSUE TITLE
error message not shown for posting comment error

### ISSUE THREAD

**Issue by AlanL1** [decred/politeiagui#215]
When there is an error posting comment (e.g. 25 invalid signing key), no error message is shown in the UI.

Since the process politeiawww reports the correct error code, I suspect there is a problem in the UI code.

**Comment by tiagoalvesdulce** [comment]
It works here.

<img width="903" alt="screen shot 2018-04-18 at 14 48 22" src="https://user-images.githubusercontent.com/13955303/38949037-9c103138-4317-11e8-8bea-7ee7c846a5f0.png">

**Comment by sndurkin** [comment]
@AlanL1 please reopen if this is still an issue.
