### ISSUE TITLE
Upload new file text

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2150]
The upload new file copy says all the valid MIME types, but that's not entirely true since we only allow image attachments.  The text mime types are only allowed for the index file.  

![image](https://user-images.githubusercontent.com/9039877/95116880-55c6e700-070d-11eb-8ca2-67e478d60e99.png)

We can make this more user friendly.  Some suggestions:

- Change the text from `Valid MIME types` to `Valid image types`
- Parse the mime types and only display the `image/` ones. 
- Change the text from `Max number of files` to `Max number of images`

The end result would look something like:
Valid image types - png
Max image size - 512kb
Max number of images - 5

**Comment by tiagoalvesdulce** [comment]
Fixed on https://github.com/decred/politeiagui/pull/2158
