### ISSUE TITLE
[cms] Render Type column as text

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#2159]
I'm having Type column cells shown as `1` instead of `Labor`. Not sure if there's an issue with my browser but other columns look correct. Specifically, Domain and Proposal columns that also use drop downs are shown correctly.

**Comment by xaur** [comment]
@tiagoalvesdulce I'm still seeing numbers in Type column. Is this fix pending deployment?

**Comment by tiagoalvesdulce** [comment]
Should be fixed by @victorgcramos on #2198, not deployed yet.
