### ISSUE TITLE
[cms] Active DCCs should not have rejected timestamp

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#2165]
I see "submitted 3 days ago" and "rejected 3 days ago" timestamps for a DCC that is Active. This happens on both `/dccs` listing as well as `/dcc/uuid...` details page. Seeing that both timestamps are identical down to the second, I think it is a visual bug.

**Comment by alexlyp** [comment]
Fixed

**Comment by xaur** [comment]
I guess the fix was https://github.com/decred/politeia/pull/1327
