### ISSUE TITLE
Fix the view of the proposals page after clicking on the search icon

### ISSUE THREAD

**Issue by MariaPleshkova** [decred/politeiagui#2184]
When you click on the search icon above progress bar within a proposal card something goes wrong (even after closing search modal). So you always need to refresh the page to fix this.
![image](https://user-images.githubusercontent.com/8841018/97970011-f0304e00-1dd1-11eb-8ef0-08be2b820204.png)
![image](https://user-images.githubusercontent.com/8841018/97970029-f4f50200-1dd1-11eb-9d8a-a9b79372a878.png)
![image](https://user-images.githubusercontent.com/8841018/97970042-f9211f80-1dd1-11eb-880e-a698f72ed349.png)

**Comment by victorgcramos** [comment]
On this!

**Comment by victorgcramos** [comment]
This is already fixed on master. See on https://test-proposals.decred.org
