### ISSUE TITLE
Fix previews (create a proposal and write a comment)

### ISSUE THREAD

**Issue by MariaPleshkova** [decred/politeiagui#2188]
Previews should be shown within the same input field (like in here in gh), not below it (same for both create a proposal and write a comment). The reason is because when previews appear under text fields everything that is below it has to move down. So basically all content that is underneath always jump up and down.

Implementation: 
![image](https://user-images.githubusercontent.com/8841018/97971886-ca587880-1dd4-11eb-8c23-6e6c74760b9c.png)

Design: 
![image](https://user-images.githubusercontent.com/8841018/97971930-d6443a80-1dd4-11eb-9289-0b542b7785d1.png)

**Comment by victorgcramos** [comment]
I think we can wait until https://github.com/decred/politeiagui/pull/2158 gets merged, in order to avoid conflicts

**Comment by victorgcramos** [comment]
This can be closed. Previews are working as expected on master.
