### ISSUE TITLE
Highlight a selected item within menu dropdown

### ISSUE THREAD

**Issue by MariaPleshkova** [decred/politeiagui#2192]
_Light Mode_
Selected item color: `#091440`

_Dark mode_
Selected item color: `#B7DEEE`

Implementation: 
![image](https://user-images.githubusercontent.com/8841018/97974451-a9922200-1dd8-11eb-8967-f778c9a9e450.png)

Design (light mode example, Proposal page is opened): 
![image](https://user-images.githubusercontent.com/8841018/97974611-e2ca9200-1dd8-11eb-8df1-46d4af341d06.png)

**Comment by thi4go** [comment]
On this
