### ISSUE TITLE
Tests failing on Travis (sporadically)

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#220]
This was subject to a previous issue but I had to open it again. 
The tests are inconsistent (specially when executed on Travis) due timeout mostly of the times. 
The `e2e` tests tend to fail when running on a low processing machine or with lots of process running at the same time.
For example, on the opened PR #218 the tests can't pass on Travis even with a timeout of 30 seconds.
See, this is the signup part of the tests executed on Travis:
![screen shot 2018-03-13 at 1 24 59 pm](https://user-images.githubusercontent.com/14864439/37356598-2248edd6-26c5-11e8-851f-1f6f7ba61d0b.png)

And this is on my local machine:
![screen shot 2018-03-13 at 1 24 43 pm](https://user-images.githubusercontent.com/14864439/37356609-289a2ce0-26c5-11e8-882b-a9fa9ba9f41d.png)

Also, all tests pass on my local machine:
![screen shot 2018-03-13 at 1 21 54 pm](https://user-images.githubusercontent.com/14864439/37356631-339ebe4e-26c5-11e8-80f8-b962cf2406bd.png)

The current behavior is highly discouraging current and new contributors to politeiagui. 
I suggest we use Behavior Driven Development in replacement of this tests and disable them on Travis. Also, the reviewers can run the tests on their local machine before closing the PR to ensure everything looks fine for the current tests.

**Comment by fernandoabolafio** [comment]
@sndurkin @tiagoalvesdulce if you're ok with disabling it from Travis I can incorporate the change to my current opened Pull request #218. Let me know what are your thoughts.

**Comment by tiagoalvesdulce** [comment]
It's OK for me disabling it for now but we should add better tests soon. I'd recommend [Snapshot Testing](https://facebook.github.io/jest/docs/en/snapshot-testing.html) for components, so we can easily see how the DOM changed from 1 PR to another and Unit Testing for actions and reducers. More info [here](https://github.com/reactjs/redux/blob/master/docs/recipes/WritingTests.md).

**Comment by fernandoabolafio** [comment]
Cool! I've updated my PR. I agree with the tests you recommended. Can you create an issue for that?

**Comment by sndurkin** [comment]
I agree, let's disable the tests for now.
