### ISSUE TITLE
Seeing edit button on other's proposals authorized for vote

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#2202]
I noticed a pencil button after the titles of proposals authorized for voting.

![props-edit-btn](https://user-images.githubusercontent.com/24484727/99115230-fc928300-25e9-11eb-8a82-29a54a325320.png)

**Comment by amassarwi** [comment]
This was fixed in #2142

**Comment by victorgcramos** [comment]
this was fixed by #2218
