### ISSUE TITLE
[cms] Invoice details & edit pages endless loading

### ISSUE THREAD

**Issue by amassarwi** [decred/politeiagui#2204]
When having an invoice with wrong proposal token which causes a 400 error when displaying invoice details, the gui keeps loading forever!

**Comment by amassarwi** [comment]
It would be great if we add a validation in Invoice form to avoid it in the future, apparently one of my description fields was pasted as proposal token, this why the invoice has an item with invalid string as proposal token.

**Comment by xaur** [comment]
Closing duplicate #2249, but I will post here its summary.

It looks like we have _four_ issues here:

- first of all, the backend should not accept malformed proposal token value (create an issue if necessary)
- the UI should not crash on 400 from the backend and show something
- the UI should do a basic sanity check and not allow strings that don't look like proposal tokens
- the backend needs a more descriptive error message to show on the UI when it does a batch request with malformed tokens

**Comment by amassarwi** [comment]
Will open a different issue for the validation.

**Comment by xaur** [comment]
Backend validation: https://github.com/decred/politeia/pull/1344
