### ISSUE TITLE
Indicate issue deployment status

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#2211]
I often get confused when an issue gets closed once the PR resolving it gets merged, but the issue remains reproducible for week(s) until the next deployment. For team members it causes some extra explaining like "This was fixed in #X but not deployed yet".

It is helpful to know the status of the fix, specifically if it is deployed or not. How about tracking that status with a issue label like `pending deployment`?

Alternatively, it can be tracked with Project Boards. I see there are two [projects](https://github.com/decred/politeiagui/projects) and the CMS one even has the separation between Done/Deployed. But both boards seem outdated.

**Comment by victorgcramos** [comment]
That's a good suggestion! What do you think @tiagoalvesdulce?

**Comment by tiagoalvesdulce** [comment]
We will be using milestones in the near future like [dcrd](https://github.com/decred/dcrd/milestones) does.

**Comment by amassarwi** [comment]
Sounds good to me

**Comment by xaur** [comment]
dcrd uses milestones for releases. Can they be used to know deployment status of a bug/feature?

**Comment by tiagoalvesdulce** [comment]
We will stick to milestones but I think we can add the commit hashes that `politeiawww` and `politeiagui` are running to the frontend. Kind of like [dcrdata](https://dcrdata.decred.org/) does in the footer. Sounds good?

**Comment by xaur** [comment]
@tiagoalvesdulce my reply got way too long but we have a chance to fix some process bugs as well so please bear with me :)

1\. Version in the footer does help in testing and reporting bugs. Specifically, it allows a reporter to _compute_ answers to questions like "is this deployment affected by issue X?" or "is fix Y deployed yet?".

2\. The above questions can be asked about _two_ versions: backend and frontend.

3\. Security consideration. I assumed the version is _not_ shown on purpose, to hide which code the server is running from potential attackers.

It is fine for dcrdata which is a read-only explorer, but Politeia and CMS have user accounts and _control money_. It is at least worth considering and evaluating the impact with a security expert before exposing backend/frontend version to an open Internet.

4\. Seeing version(s) does not directly answer if the bug or fix is live. You have to look up the hash/version on GitHub, scan commits before that point and see if they include the fix. Non-dev users don't have these skills, but even for someone who can do it like myself, it takes time.

5\. Regardless of showing the version on the UI, it is a good idea to inform the reporter (and everybody) about whether or not the issue is _really_ resolved on a given _deployment_. That is when the issue becomes no longer _reproducible_ by real users.

I understand that just closing the issue when the fix is merged "removes it from the table" and clears up the space for focusing on next tasks as @lukebp explained in https://github.com/decred/politeia/issues/554#issuecomment-835525689 (when discussing a similar problem with "outdated" issues). I value free mental space myself and I fully share this idea. But please imagine how the current process looks and feels for someone "external" reporting the bug. I take time to notice the issue, reproduce it, write it up on GitHub, and I'm willing to re-test when needed. Then it is closed when "merged" and here's how it affects all roles involved:

- _reporter_ does not get notified when it is deployed and can be re-tested to verify
- it goes away from _developer_'s attention and whoever does the _deployment_ can forget to deploy (I suspect this is what caused #2424)
- _other people_ will not see it in the list of open issues and may report duplicates (because it's still reproducible) or otherwise rely on the belief the bug is no longer live

Besides all the practical downsides, it is also a small demotivating factor for future contributions, which we want to encourage to have more firepower and eyeballs hunting for bugs.

To conclude, I think we should not choose between developer convenience and reporter convenience but try to achieve both. For developers, it should be possible to setup _issue filters_ such that merged stuff is removed from sight but stays open in other listings. For reporters, it should be possible to get notified when a fix is deployed without jumping through the hoops like manual "polling" or Git math.

GitHub has good systems for this (issues, focused subscribtions and notifications, labels, projects, milestones, etc) and I'm 90% sure they can solve all the above problems.

**Comment by lukebp** [comment]
> Security consideration. I assumed the version is not shown on purpose, to hide which code the server is running from potential attackers.

This assumption is wrong.

> Seeing version(s) does not directly answer if the bug or fix is live. 

Stop trying to overcomplicate things.  Showing the commit hash that politeia and politeiagui are running is a simple solution that addresses the problem.


@xaur I'm actually getting pissed now.  You are not a developer.  We are not going to complicate the development process to suit your perfectionist whims.  We've had this dicussion before and I took the time to answer your questions and explain the reasoning behind the existing development processes.  Instead of accepting my answers and moving on you try and convince the other politeia developers to add in complexity.  This is 100% getting into provacateur territory and I will not put up with it.  If you try and influence the development process again I will ignore all input from you going foward, regardless of the topic.

**Comment by lukebp** [comment]
We use the pi-not-deployed tag now.
