### ISSUE TITLE
Any cased letter in email login

### ISSUE THREAD

**Issue by icedice1** [decred/politeiagui#2216]
I tried to login to politeia using uppercase letters in email, had to switch to lowercase for it to work.

**Comment by victorgcramos** [comment]
Agree with this one here. The e-mails are converted to lowercase when creating a new user, see: https://github.com/decred/politeia/blob/a3a16ab8550dd07fb6f6271af4cb4b0fe52ae6f3/politeiawww/user.go#L370

on it!
