### ISSUE TITLE
[cms/user-search] Improve page counting for long list results

### ISSUE THREAD

**Issue by victorgcramos** [decred/politeiagui#2219]
This is minor, but I noticed that if we have a very long user list as a result of searching users, the list counting will overflow the screen.

<img width="1363" alt="Screen Shot 2020-11-25 at 4 47 58 PM" src="https://user-images.githubusercontent.com/22639213/100275664-0d72bb00-2f3f-11eb-9b8e-40f9bcc78707.png">

**Comment by tiagoalvesdulce** [comment]
This is more of an issue with the Table component on pi-ui
