### ISSUE TITLE
[cms] Put name first in Invoice tab title

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#2234]
#2208 has improved tab title by adding name and month but it missed to place name at the beginning of the string. Try opening a lot of tabs and they all will show `Invoice from`.

I suggest to format tab title as `{name} {month} invoice`.

**Comment by victorgcramos** [comment]
as I mentioned on https://github.com/decred/politeiagui/pull/2238#pullrequestreview-549207907, I think we can remove this "invoice" suffix from the title on invoice list, and keep only on details.
