### ISSUE TITLE
[cms] User badge has "undefined" on All Invoices page search box

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#2235]
I entered a full username in the search box on All Invoices page and the suggested dropdown item is formatted like `{username} | undefined`. When I click it, a badge with same text is added to the search box.

**Comment by tiagoalvesdulce** [comment]
May have been fixed on https://github.com/decred/politeiagui/pull/2215. Can you double check @victorgcramos ?

**Comment by victorgcramos** [comment]
Yes, I think we just need to push the latest changes to production. All good here after #2215. Thanks @tiagoalvesdulce!
