### ISSUE TITLE
[cms] Suggest username in All Invoices page search box

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#2236]
I have to type exact full username in the All Invoices page search box to get that name shown in the dropdown item and become clickable. It would be a UX boost to suggest names that match an entered substring.

For users that are not allowed to see emails (non-admin users I guess), the search should not work over emails.

**Comment by tiagoalvesdulce** [comment]
This should be fixed.

![abc](https://user-images.githubusercontent.com/13955303/101638344-b5db5180-3a0c-11eb-95d9-349e307caab5.gif)

**Comment by xaur** [comment]
Not sure what that screenshot means @tiagoalvesdulce because it shows an empty `Search by User` field that I was referring to.

**Comment by tiagoalvesdulce** [comment]
It's a gif.

> I have to type exact full username in the All Invoices page search box to get that name shown in the dropdown item.

You won't have to type the full username anymore. The search will return every string that contains the string in the text box.

**Comment by xaur** [comment]
Oh I didn't notice its a gif, now I see how it will work. Thanks!
