### ISSUE TITLE
[cms] past 3 moth invoices loading forever

### ISSUE THREAD

**Issue by victorgcramos** [decred/politeiagui#2241]
When I click on "show", it shows the table as expected, but the loading icon is displayed when the table is hidden.

<img width="1663" alt="Screen Shot 2020-12-10 at 4 53 56 PM" src="https://user-images.githubusercontent.com/22639213/101822686-7bef7580-3b08-11eb-8e08-81e61e3bd3b4.png">

**Comment by alexlyp** [comment]
@tiagoalvesdulce is looking into the issue as well
