### ISSUE TITLE
Comments from the future

### ISSUE THREAD

**Issue by RichardRed0x** [decred/politeiagui#2246]
A small thing, but I noticed that my comments will sometimes appear as they're scheduled to appear in future, with "in less than a minute" time description.
![image](https://user-images.githubusercontent.com/37707106/101983305-2800a000-3c72-11eb-8dbc-4ee9d33e6958.png)

**Comment by victorgcramos** [comment]
although it seems common for someone who thinks ahead of our time like @RichardRed0x, this shouldn't happen. On it! 😁

**Comment by victorgcramos** [comment]
This should be fixed after tlog gets in.

**Comment by lukebp** [comment]
This was fixed in the v1.0.0 release and should no longer be present on the proposals site.
