### ISSUE TITLE
[cms] Commit seperation in code stats

### ISSUE THREAD

**Issue by alexlyp** [decred/politeiagui#2256]
Currently separate repo lists of commits are all put together and not separated

78f36a3, e061ab0, 815aba4, a63c165e8d82eb, acbb05e, fe12e8e, e3bf330, 66edb29, 367a918, 33f480b, f109dc4, 8af3637, 4516c5c, 36eeba7ebd86d6, 4766344, 25ce2ca, e545cf4, e1e6dcb, e9bd4d2, ecd10f7, 8ecee56, 32903b1, 8cb3883nonenonenonenone

for instance.

They probably should be separted by repo name as well.

**Comment by victorgcramos** [comment]
on it!

**Comment by victorgcramos** [comment]
on it!
