### ISSUE TITLE
[cms] Show monthly subtotals for Proposals Owned

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#2267]
When reviewing billing against my proposal it would help to see a subtotal (sum of labor and expenses) for each month. Some proposals promise a monthly expense limit and this feature is needed to facilitate that.

_extracted from https://github.com/decred/politeia/issues/1328#issuecomment-731605967 _

**Comment by tiagoalvesdulce** [comment]
Any idea of how to fit this in the screen?
<img width="1163" alt="Screen Shot 2020-12-23 at 11 58 29" src="https://user-images.githubusercontent.com/13955303/103009877-2eb2d100-4516-11eb-9c8e-a2a40f7fb46e.png">

**Comment by xaur** [comment]
@tiagoalvesdulce yes, either insert a monthly total row after each month, or split one big table into monthly tables.

**Comment by tiagoalvesdulce** [comment]
@xaur done! added a screenshot to the PR description.
