### ISSUE TITLE
Proposal votes bug

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2288]
Reproduction steps:
1. Go to the proposal details page of a vote that has finished.
2. Click the votes search button to bring up the votes search modal.  Wait for it to fetch the votes.
3. Exit the modal.  The vote tally is now missing and the proposal vote indicator now says "missing".

![image](https://user-images.githubusercontent.com/9039877/104510778-51825380-55b1-11eb-80dd-3b6ce3592cba.png)

**Comment by victorgcramos** [comment]
on this!

**Comment by tiagoalvesdulce** [comment]
This was fixed on https://github.com/decred/politeiagui/releases/tag/v1.0.0
