### ISSUE TITLE
External links in Dark Mode difficult to read

### ISSUE THREAD

**Issue by dezryth** [decred/politeiagui#2300]
Blue on top of blue is difficult to read. I suggest going with a different color: light green or something that will stand out more. See below: 
![image](https://user-images.githubusercontent.com/5300356/107211830-b2902200-69cb-11eb-8a77-d737c8501f94.png)

This should just be a simple css change. May be a good first issue.

**Comment by tiagoalvesdulce** [comment]
cc @MariaPleshkova

**Comment by amassarwi** [comment]
iirc we use light blue for links in other parts already, we might need just to apply it here as well.

**Comment by MariaPleshkova** [comment]
Hm. As I can see now we use `#0366d6` for links. But let's try our main blue color `#2970FF`, it's a bit brighter. Tbh I have no idea why it's another one there right now.
