### ISSUE TITLE
[proposals2] Create proposal bug.

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2318]
The following actions were taken to get this `[object Object]` bug.

1. Clicked new prop
2. Save draft

The user had paid their registration fee, but did not have any proposal credits yet.

![image](https://user-images.githubusercontent.com/9039877/113582707-52de7d80-95ee-11eb-8dee-3af867dc0fb7.png)
![image](https://user-images.githubusercontent.com/9039877/113582737-5a9e2200-95ee-11eb-8ecb-471c89ba8e4a.png)

**Comment by thi4go** [comment]
On this.
