### ISSUE TITLE
[politeiav2] Duplicated policy requests

### ISSUE THREAD

**Issue by victorgcramos** [decred/politeiagui#2336]
Just noticed that policy requests are duplicated on https://test-proposals2.decred.org/record/43e58fc

<img width="1578" alt="Screen Shot 2021-04-14 at 10 36 58 AM" src="https://user-images.githubusercontent.com/22639213/114719342-5ae49e80-9d0d-11eb-9e68-da0f18090ca4.png">

**Comment by amassarwi** [comment]
will have a look
