### ISSUE TITLE
[politeiav2] Weird vote end date

### ISSUE THREAD

**Issue by tiagoalvesdulce** [decred/politeiagui#2337]
![image](https://user-images.githubusercontent.com/13955303/115243126-f6548580-a0f8-11eb-92f4-f01b0c4264cf.png)

Noticed it on https://test-proposals2.decred.org/record/6d2bffd

**Comment by thi4go** [comment]
on it

**Comment by tiagoalvesdulce** [comment]
Fixed by https://github.com/decred/politeia/pull/1402

**Comment by thi4go** [comment]
Was actually a BE issue, fixed by Fixed by decred/politeia#1402
