### ISSUE TITLE
Edit: Updated propsoal not persisted.

### ISSUE THREAD

**Issue by amassarwi** [decred/politeiagui#2351]
When editing a proposal for the second time the proposal form displays old form values.

Related to #2365.

**Comment by amassarwi** [comment]
This is related to the redux normalized issue @thi4go tackling so it might resolved with #2365.
@thi4go could you please double check this one while finalizing your PR ?

**Comment by thi4go** [comment]
Sure thing mate, normalizing the state should solve this issue as well 👍

**Comment by amassarwi** [comment]
@thi4go awesome, thanks mate.

**Comment by tiagoalvesdulce** [comment]
Fixed. https://github.com/decred/politeiagui/pull/2365
