### ISSUE TITLE
Screen flickering when switching between proposal tabs

### ISSUE THREAD

**Issue by thi4go** [decred/politeiagui#2354]
We noticed a screen flickering when switching through the prop tabs.

![screen-recording-2021-04-29_07 34 38](https://user-images.githubusercontent.com/2729122/116698881-46ee9d00-a99b-11eb-8997-39dbc49a3e16.gif)

We should not show the `No proposals <state>` message when we already have loaded props in our state.

**Comment by amassarwi** [comment]
hrmmm i think this was fixed in https://github.com/decred/pi-ui/pull/322 let me double check the commit hashes.
