### ISSUE TITLE
Broken comment "View All" link

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2357]
1. Navigate to a comment permalink
    https://proposals.decred.org/record/91cfcc8/comments/2
2. The `View All` link is broken
    https://proposals.decred.org/proposals/2/91cfcc8

**Comment by lukebp** [comment]
@tiagoalvesdulce looks like the flat mode `see in context` link is also broken.  Probably the same issue.  Can you fix that as well?

**Comment by tiagoalvesdulce** [comment]
sure!
