### ISSUE TITLE
OpenGraph tags

### ISSUE THREAD

**Issue by jholdstock** [decred/politeiagui#2369]
There are no OpenGraph tags in the politeiagui HTML, which means that links shared on social media do not have any image, logo or description.

The following tools can be used to preview how shared links will appear on Twitter and Facebook.

https://cards-dev.twitter.com/validator
https://developers.facebook.com/tools/debug/?q=proposals.decred.org

Compare with the preview of dex.decred.org to see the potential improvement.

**Comment by jholdstock** [comment]
This also effects CMS of course

**Comment by vibros68** [comment]
I am on it

**Comment by lukebp** [comment]
@vibros68 the dcrweb metadata tags can be used as an example.  These are the important ones.

https://github.com/decred/dcrweb/blob/5128581207c7f8420d06f48e8380ec2f31b352e4/src/layouts/_default/baseof.html
