### ISSUE TITLE
Initial Load Flickering

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2371]
There's all kinds of weird flickering going on during the intial load.  See the attached video. Can we smooth this out?

https://user-images.githubusercontent.com/9039877/117089949-95de5e80-ad1c-11eb-95f0-208e7b6a9c04.mp4

**Comment by xaur** [comment]
Also getting some flickering, slightly different.

**Comment by amassarwi** [comment]
will investigate...

**Comment by lukebp** [comment]
Just noticed this, but what is up with the super skinny `About Politeia`?  That looks like a bug.

**Comment by tiagoalvesdulce** [comment]
Closed by #2395. I couldn't repro the skinny `About Politeia` section, please open a new issue if it's still happening with more details about screen size, browser, etc. See:


https://user-images.githubusercontent.com/13955303/118833197-a69fe000-b897-11eb-9171-b703b88574d6.mp4
