### ISSUE TITLE
Add button to start vote

### ISSUE THREAD

**Issue by marcopeereboom** [decred/politeiagui#240]
We need to add a button on the admin page to start a vote on a proposal.

It should pop up a modal where some questions are asked (leave blank for now) and then when the user ok's it prompt again to make sure to continue.

**Comment by fernandoabolafio** [comment]
I've implemented a better modal mechanics on PR #227 to covert such situations. Would be nice if we get that merged before.

**Comment by vctt94** [comment]
I opened a WIP PR, adding the button and I will wait till #227 gets merged for this modal then. About these questions, are they going to be vote options? Right now I am letting them hard coded.
