### ISSUE TITLE
Wrong cursor on Dark Mode toggle text

### ISSUE THREAD

**Issue by tiagoalvesdulce** [decred/politeiagui#2402]
![dark_mode_pointer](https://user-images.githubusercontent.com/13955303/119184043-42be1880-ba4b-11eb-99df-31b93eb4df07.gif)

That should be `cursor: pointer`.

**Comment by x-walker-x** [comment]
Hey, I want to work on this issue.

**Comment by tiagoalvesdulce** [comment]
Cool @x-walker-x! Hit me up on [matrix](https://decred.org/matrix/) if you need help: @tiagoalvesdulce:decred.org
