### ISSUE TITLE
Unnecessary duplicate requests

### ISSUE THREAD

**Issue by tiagoalvesdulce** [decred/politeiagui#2403]
See:

<img width="1280" alt="Screen_Shot_2021-05-21_at_10_41_18" src="https://user-images.githubusercontent.com/13955303/119184767-2f5f7d00-ba4c-11eb-9a6b-ec78e70b44c4.png">

This is causing the proposals list to flicker, see:

https://user-images.githubusercontent.com/13955303/119184853-4ef6a580-ba4c-11eb-88c4-aae5fa4a52d5.mp4

I think it's related to https://github.com/decred/politeiagui/issues/2353. cc @thi4go

**Comment by tiagoalvesdulce** [comment]
Still seeing this after https://github.com/decred/politeiagui/pull/2365

**Comment by vibros68** [comment]
I am on it
