### ISSUE TITLE
proposals-archive: Add site banner.

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2414]
UX issue:
1. User is browsing `proposals.decred.org` and they decide to look at an archived proposal.
2. They navigate to the archived proposal details page.
3. They click the politeia home button thinking it will take them back to the `proposals.decred.org` but it actually takes them to `proposals-archive.decred.org`.

This can be a source of confusion for the user.  We should add some sort of banner to all pages on the `proposals-archive` site that indicates the user on on the `proposals-archive` site and not on the regular `proposals.decred.org` site.

**Comment by tiagoalvesdulce** [comment]
I think something like this is good enough:

![pi banner](https://user-images.githubusercontent.com/13955303/121195969-75874f80-c846-11eb-99f7-13d702580326.png)

Should be implemented in the [gitbe-archive](https://github.com/decred/politeiagui/tree/gitbe-archive) branch.

**Comment by lukebp** [comment]
Minor grammar corrections.

`You are on the archived proposals website.  Click here to go to Politeia.`

**Comment by victorgcramos** [comment]
Good idea! In the future I think we should also change the navbar's politeia logo to something like "[logo] Archive". But for now, the banner is good and clean enough. What do you think @tiagoalvesdulce?

**Comment by tiagoalvesdulce** [comment]
This is a temporary solution because we still have proposals in the archive being billed against. In the future this proposals archive will just be a static database so we wouldn't need that.

**Comment by tiagoalvesdulce** [comment]
Taking this one because it's important for the release.
