### ISSUE TITLE
proposals-archive: Broken comment links.

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2419]
See details below:

![image](https://user-images.githubusercontent.com/9039877/120901206-0835ad80-c5ff-11eb-820c-dd5c10648548.png)

**Comment by amassarwi** [comment]
will fix

**Comment by lukebp** [comment]
The proposals-archive site uses the `gitbe-archive` branch so make sure to use that branch.

**Comment by amassarwi** [comment]
yep

**Comment by lukebp** [comment]
Duplicate. This was already fixed by #2342.
