### ISSUE TITLE
Published timestamp is missing

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2429]
The published timestamp that used to be on the list view item is missing.

proposals-archive
![image](https://user-images.githubusercontent.com/9039877/121810965-5dd60f80-cc28-11eb-8797-27d2b6b24921.png)

proposals
![image](https://user-images.githubusercontent.com/9039877/121810988-75ad9380-cc28-11eb-903a-42f17fea9f58.png)

**Comment by xaur** [comment]
Also missing the timestamps. I often look at them to see how old is the proposal to estimate how soon it will go to vote. I guess we're waiting for deployment now.

**Comment by lukebp** [comment]
Correct, just waiting on deployment.

**Comment by xaur** [comment]
Works as expected now, thanks.
