### ISSUE TITLE
Download bundle UX improvement

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2438]
There are currently UX differences when downloading the various bundles.

- `Load Comment Timestamps` and `Load Vote Timestamps` are prefixed with `Load` because those requests are paginated.
- `Load Comment Timestamps` and `Load Vote Timestamps` when selected will show a loading wheel wheel and a % complete indicator.
- When you download one of the non-paginated bundles, like the `Proposal Timestamps` bundle, the loading wheel is not shown even though it may take multiple seconds to fetch the timestamps.  

![image](https://user-images.githubusercontent.com/9039877/122471405-dfa99e00-cf84-11eb-8e3b-b78f74ede06a.png)

We should make the download UX consistent.

**For all downloads**
- Remove the `Load` prefix
- Show the loading wheel while the data is being fetched

**For paginated downloads**
- Show the % complete indicator

**Comment by vibros68** [comment]
Hi. I can not find what is the page this issue is referred to

**Comment by vibros68** [comment]
Should there UX effect be inline or open a modal, the effect is inside the modal and when the process is done we will close the modal?

**Comment by lukebp** [comment]
The `Available Downloads` should open a modal like it does now.  The loading wheel that you currently see when you click `Load Comment Timestamps` or `Load Vote Timestamps` should be applied to all downloads.  The % complete indicator should only be on the two paginated downloads (comment timestamps and vote timetamps).

**Comment by vibros68** [comment]
OKay. I am working on it

**Comment by vibros68** [comment]
I am having a proposal with 24 comments. They are loaded at the first loading with 1 request. Seem they are not paginated. The same problem with comments timestamp. When click on `Comments Timestamp`, entire 24 items were responsed in one request. This make the progress of download jump from 0% to 100%.

One more problem is the comment api take very long time to process. Always be about 5
![Screenshot from 2021-06-20 22-24-47](https://user-images.githubusercontent.com/84569563/122679779-61642a80-d216-11eb-9046-d0b1f2b07731.png)
0s per request for this endpoint

**Comment by lukebp** [comment]
Please re-read my previous comments more carefully.  The % complete indicator should only be shown on paginated requests.

**Comment by vibros68** [comment]
Hi it is `Load Comment Timestamps`. I removed `Load` and now it is `Comment Timestamps`. It is paginated function. And the code is expressing it
```
const DownloadCommentsTimestamps = ({ recordToken }) => {
  const { loading, progress, timestamps } =
    useDownloadCommentsTimestamps(recordToken);
 ```
 `progress` is the variable for `% complete indicator ` as you mentioned

**Comment by lukebp** [comment]
Oh I see now, good point.  There are two options here.

**Option 1**
The code should check the number of comments on the page and only show the % complete indicator if the number of comments is greater than the timestamps page size.  For example, the timestamps page size is currently 100 timestamps.  If the record has more than 100 comments, the % complete indicator would be shown since it will require multiple timestamp requests to fetch all timestamps.  If the record has less than 100 comments, the % complete indicator will not be shown since it will only require one timestamp request to fetch them all.

**Option 2***
We still show the % complete indicator for paginated requests even when all of the timestamps can be fetched in a single request.

What is your opinion on the best way foward?

**Comment by vibros68** [comment]
* I think we shouldn't fetch all comments in 1 request. So the user don't need to wait as long as current to see all the comments. Normally user should see some comments(10-20 for example) and at the time he is reading and scroll down. We load the next comments. The user have done with the above comments and the next comments are shown. This way is good UX. I think.
* About the time ~50s to load 24 comments as my knowledge. It should be a bug on BE. I do not read the code on BE but I think it should be small than 5s. If you agree I can jump into BE code and see what was happen.
* About the % complete indicator solution I think **Option 1** would be better

**Comment by lukebp** [comment]
> About the time ~50s to load 24 comments as my knowledge. It should be a bug on BE.

This is likely something local to your enviroment.  This performance bottleneck is not reproducible on [test-proposals](https://test-proposals.decred.org) or on my local enviroment.

![image](https://user-images.githubusercontent.com/9039877/122684436-fd684480-d1ca-11eb-857e-7833c4b29038.png)

Have you setup the [MySQL](https://github.com/decred/politeia/tree/master/politeiawww#setup-mysql-optional) user database? If not, that might be the issue.  `politeiawww` defaults to using LevelDB which is fine for testing, but may cause performance issues.

**Comment by vibros68** [comment]
```
// Comments requests a record's comments.
type Comments struct {
	Token string `json:"token"`
}

// Timestamps requests the timestamps for the comments of a record.
type Timestamps struct {
	Token      string   `json:"token"`
	CommentIDs []uint32 `json:"commentids"`
}

// Votes returns the comment votes that meet the provided filtering criteria.
type Votes struct {
	Token  string `json:"token"`
	UserID string `json:"userid"`
}
```
This is the struct represents request variable for comments, timestamps and votes api entry. Currently there are no `page` field at all

**Comment by vibros68** [comment]
> Have you setup the MySQL user database? If not, that might be the issue. politeiawww defaults to using LevelDB which is fine for testing, but may cause performance issues.
I am using cockroachdb for piwww and mysql for politeiad

**Comment by lukebp** [comment]
Not sure what is causing your perf issues then.  Don't worry about those for now.  Focus on the original UX fixes.

**Comment by vibros68** [comment]
Yes. But because currently The api always return full data. So no way to calculate the progress of downloading. For example if I do follow **Option 1** above, I must have the number of items per page to decide hide or show the progress. So I suggest to just show the loading wheel at all. And will show the progress after the paging is implemented on BE

**Comment by lukebp** [comment]
The % complete indicator will only be shown for the comment timestamps and vote timetsamps.  There is one timestamps per comment and one timetamp per vote.  The gui already knows the total number of comments and the total number of votes.  Here's an example.

![image](https://user-images.githubusercontent.com/9039877/122787454-f7ca3780-d27a-11eb-8908-e2b7e4feb960.png)

The total number of votes cast is 18,075 votes.  The [page size](https://github.com/decred/politeia/blob/master/politeiawww/api/ticketvote/v1/v1.go#L618-L647) for vote timestamps is 100.  This will require 181 pages to retrieve all the vote timestamps.  

![image](https://user-images.githubusercontent.com/9039877/122785444-044d9080-d279-11eb-9cd7-1137e907b268.png)

The total number of comments is 150.  Its up to the client how many timestamps it retrieves per request, but the [max is 100](https://github.com/decred/politeia/blob/master/politeiawww/api/comments/v1/v1.go#L326-L361).  This is everything you need to show the % complete indicator.
