### ISSUE TITLE
Censored record UX improvement

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2440]
**Record details**
Censored records currently do not display any information about why they were censored.  The gui already has access to this information without needing to send any additional requests, its part of the returned status change metadata, but its not being displayed anywhere.  This should be displayed on the record details page.

- Admin that censored the record
- Reason for censoring the record
- Censored timestamp (like we do for record edits)

**List view**

The list view card for a censored record is currently just a blank card with the author and record token.

![image](https://user-images.githubusercontent.com/9039877/122478868-c9550f80-cf8f-11eb-8786-bec427c11874.png)

This should be made to match the abandoned record UX.  
- Grayed out background color.
- Record status tag displayed in the upper right corner. Make this red for censored records (like we do for the `rejected` vote status. 
- Censored at timestamp (like the `abadoned 2 months ago` timestamp)

There are certain scenerios where the client may want to display both abandoned and censored records in the same list, such as the `ineligible` vote status, and using the same backround color with different record status tag colors will allow it to flow nicely while still being able to differentiate between censored and abandoned.

**Comment by thi4go** [comment]
Working on this

**Comment by thi4go** [comment]
PR #2454 implements most of the changes requested in this issue, expect for the admin that censored that proposal. We don't seem to have that information included on the `StatusChangeMetadata` md. I can open a backend PR that includes this on the md, if we indeed opt to show it. @lukebp

**Comment by lukebp** [comment]
The public key is there.  You'll need to lookup the user by public key in order to display the username.

https://github.com/decred/politeia/blob/master/politeiawww/api/www/v1/v1.go#L731
