### ISSUE TITLE
e2e: Verify user record pagination.

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2443]
Add e2e tests that verify the correct behavior for user record pagination.

This issue is a continuation of #2441.  The e2e tests have not been setup yet to test pagination, which is why this issue is being opened instead of just including the tests in 2441.

**Comment by victorgcramos** [comment]
on it!

**Comment by victorgcramos** [comment]
Waiting for https://github.com/decred/politeia/issues/1443

**Comment by victorgcramos** [comment]
Fixed by https://github.com/decred/politeiagui/pull/2473.
