### ISSUE TITLE
Top sort is not working

### ISSUE THREAD

**Issue by RichardRed0x** [decred/politeiagui#2448]
https://proposals.decred.org/record/3a98861?sort=Top

Seems to be the same as "New" sort.

**Comment by tiagoalvesdulce** [comment]
Fixed. See: https://test-proposals.decred.org/record/89dd08b?scrollToComments=true&sort=Top.

**Comment by lukebp** [comment]
Should be deployed to the mainnet proposals site in the next few days.  Hopefully Monday, depending on dhill's schedule.
