### ISSUE TITLE
Pagination issues on Abandoned tab

### ISSUE THREAD

**Issue by tiagoalvesdulce** [decred/politeiagui#2450]
We are seeing multiple unnecessary requests being fired on this tab. We have to make sure that:

1. List item cards should be the same size so we don't have different behaviors between tabs
2. A page of proposals should be sending at most 4 requests. The first 3 requests are the records batch, comments count, and vote summaries. The last request will only be when the parent RFP name is needed and should be a records batch for the RFP names.

**Comment by lukebp** [comment]
I can't find the exact PR, but 1 has been fixed.  I believe 2 has also been fixed by #2447.  Closing this issue.  Please re-open it if I am mistaken.
