### ISSUE TITLE
Add flat mode explainer

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2458]
**Problem**

The flat mode button looks good, but from a UX perspective new users are unlikely to know what it does.  Flat mode is not a common functionality that people are likely to be familar with.  Comment replies may not be viewable, such as in the example below, so even toggling flat mode on and off is unlikely to provide the user with info about what it does.

![image](https://user-images.githubusercontent.com/9039877/123713456-12cc1700-d83a-11eb-905d-502b311a8129.png)

**Solution**

Add an information icon next to the flat mode button with an explanation of what flat mode does.

![image](https://user-images.githubusercontent.com/9039877/123713520-368f5d00-d83a-11eb-986e-7051787b401b.png)

"Flat mode flattens out the comment hierarchy so that filtering criteria can be applied to both top level comments and comment replies equally.  When flat mode is turned off, filtering criteria is only applied to top level comments."

**Comment by vibros68** [comment]
I am on it
