### ISSUE TITLE
Latest version diff not showing up

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#2464]
I could not manage to see the latest version diff from any proposal. As recorded in the video, clicking on the latest version from the dropdown does not trigger anything.

https://user-images.githubusercontent.com/14864439/123919770-921a3180-d985-11eb-8262-4e17bf828d0a.mov

**Comment by lukebp** [comment]
@tiagoalvesdulce how does this currently work?  Does it display the diff between the current version and the selected version or does it display the diff between the selected version and the `selectedVersion - 1`?

**Comment by tiagoalvesdulce** [comment]
Currently we show the diff between the selected version and selected version - 1.

**Comment by lukebp** [comment]
I think one way to improve this UX would be to do the same thing github does for its diff viewer. 

![image](https://user-images.githubusercontent.com/9039877/123967701-2f706800-d97c-11eb-864b-12510e857013.png)

Using the above proposal as an example, on initial click of `version 1` the diff modal would pop up and show the diff between version 1 and the current version.  The diff modal would have two dropdowns that lets the user choose what version it wants to compare.

**Comment by lukebp** [comment]
I opened #2466 for the UX improvement that I suggested so as to not confuse that with the bug that this issue is reporting.  

This issue is to fix the bug reported by fernando.  When the user selects `version 2`, a diff between `version 2` and `version 1` should be shown, but it does not currently work.

**Comment by lukebp** [comment]
It looks like the gui is formatting this request incorrectly, which is causing the error.  The version is provided as a string when it should be a number.

![image](https://user-images.githubusercontent.com/9039877/126489594-7e12550b-d676-4b48-b8d9-fe78edc82eaa.png)
