### ISSUE TITLE
Improve version diff modal

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#2465]
While the version diff modal content seemed quite tidy, its presentation and sizing were not. Two things stand out most to me:

- There is a significant delay between selecting a version and clicking on the modal. This seems like a bug and many times I ended up clicking multiple times until I actually get the result. Would be great to display a loading of sorts until the content is ready.
- The modal size is tinny and makes it hard to navigate and see the markdown diff content. Especially for desktop screens, space could be better used.

**Comment by lukebp** [comment]
Modal size is not good.

![image](https://user-images.githubusercontent.com/9039877/123966883-6e51ee00-d97b-11eb-8d3a-fe335a070e03.png)

**Comment by victorgcramos** [comment]
On it!
