### ISSUE TITLE
Allow user to select diff versions

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2466]
I think one way to improve the UX of the diff viewer would be to do the same thing github does for its diff viewer. 

![image](https://user-images.githubusercontent.com/9039877/123967701-2f706800-d97c-11eb-864b-12510e857013.png)

On initial click of `version x` the diff viewer would do what it currently does, which is show the diff between the `selectedVersion` and the `selectedVersion - 1`.  The diff modal would have two dropdowns though that are populated with the versions being compared and that let the user choose what versions they want to compare.  This would improve the UX by explicity stating what versions are being compared and by also giving the user more fine grained control.

**Comment by lukebp** [comment]
This has not been included in a proposal so cannot be billed for yet.

**Comment by vibros68** [comment]
I am on it now
