### ISSUE TITLE
Comment text size should be consistent

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2476]
![image](https://user-images.githubusercontent.com/9039877/125957301-919b40e1-2cc5-4781-9b33-92a131da7456.png)

The ability to make certain text in your comment appear bigger than normal should not be allowed.  Syntax like making text bold or italic is fine, but the size of the text should be the same for all comment text.

Example: https://proposals.decred.org/record/ae609f1/comments/15

The gui should ignore markdown sytax that changes the text size.

**Comment by lukebp** [comment]
This particular comment text used the `----` markdown syntax, making the last line a large and bold.  Header syntax (`#`, `##`) should also be ignored as well as any other syntax that changes the text size.

**Comment by victorgcramos** [comment]
on it!
