### ISSUE TITLE
Embed image button UX improvement

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2477]
The embed image button is not very helpful.  I couldn't figure out how to use it to embed an inline image.  I had to resort to dragging and dropping the image.

When you press the button you get `![](https://example.com/your-image.png)`.
When I dragged and dropped the image I got `![valid.png](blob:https://test-proposals.decred.org/7e3a5f28-7424-4bc3-abe2-fa32b73dc753)`.

How does the user know what to fill in when they press the button?

**Comment by lukebp** [comment]
Another quirk that I noticed is that dragging and dropping the file from your file system works fine, but dragging and dropping the file from another browser tab does not work.  Is this expected?

**Comment by lukebp** [comment]
The way I would expect this to work is that clicking the embed image button would bring up the file selector modal.  Selecting a file would insert it to the markdown text at the current location of the cursor.

**Comment by vibros68** [comment]
I am on it
