### ISSUE TITLE
Preview embedded images

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2478]
When you preview the markdown after you embed and image it will only show the image filename, not the image itself.  Is there a way to show the image itself so that the preview reflects what will show on the proposal details page?

Markdown Preview
![image](https://user-images.githubusercontent.com/9039877/126040784-1b85287d-e239-453a-a8db-20235a5e8bf0.png)

Proposal Details
![image](https://user-images.githubusercontent.com/9039877/126040813-276483d3-81f7-4588-8f90-0f4b7594c443.png)

**Comment by victorgcramos** [comment]
I think it is possible. On it!

**Comment by lukebp** [comment]
This bug is reproducable on test-proposals, but appears to be working correctly on master.

**Comment by victorgcramos** [comment]
Update: the CSP is blocking the requests from local data files. Trying to figure out the best solution here so we don't make our platform vulnerable to XSS attacks. See:
<img width="1843" alt="Screen Shot 2021-07-20 at 8 28 42 PM" src="https://user-images.githubusercontent.com/22639213/126408158-5ddb02c9-3c3e-4bc1-a894-f40d1b0194c0.png">

**Comment by victorgcramos** [comment]
### Update 2

1. We can add the `blob:` directive on `image-src` policy, but will it make our platform vulnerable to XSS attacks? If so, how can I reproduce it? Using [this blog post on BruteXSS](https://brutelogic.com.br/blog/file-upload-xss/) as reference and I wasn't able to explore those vulnerabilities.

2. Other solution is to render the image as a `base64` string, but this might hurt the UX. See how it looks like:
![blob-to-base64](https://user-images.githubusercontent.com/22639213/126558198-c633707b-11d8-4436-b0a4-02828e003bb3.png)


Any other thoughts on this one? @degeri @tiagoalvesdulce @lukebp

**Comment by degeri** [comment]
Like we discussed on chat. We can crop the base64 when displaying render to user who is editing. But blob should also be fine, we should use the following CSP `image-src 'self' blob:`

**Comment by tiagoalvesdulce** [comment]
I decided to not go with base64 when implementing this due to poor UX. I would prefer the CSP blob solution.

**Comment by lukebp** [comment]
I agree with tiago.  Rendering base64 makes the problem worse.  Let's go with the CSP solution.

**Comment by victorgcramos** [comment]
Nice, I'll change that. Thanks!

**Comment by lukebp** [comment]
This is still reproducable on test-proposals.  2495 doesn't appear to fix it.

**Comment by lukebp** [comment]
This was still reproducable on test-proposals because the nginx config had not been updated yet.  The CSP policy change in 2495 need to be changed in the nginx config as well.  This is now working as expected.
