### ISSUE TITLE
Long comment lines rendered improperly

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2480]
An unbroken comment line goes off the side of the page.  It is also breaking the page in general.  I'm not able to scroll up and view the proposal.

https://test-proposals.decred.org/record/a680188?scrollToComments=true

https://user-images.githubusercontent.com/9039877/126079339-120eaf78-ac3c-4be1-8240-22553cece64c.mp4

**Comment by victorgcramos** [comment]
on it!

**Comment by lukebp** [comment]
This appears to be a firefox specfic issue.  Chromium renders the comments correctly.

![image](https://user-images.githubusercontent.com/9039877/126383753-7d0fe8ae-b28a-4797-b92f-13407212caa7.png)
