### ISSUE TITLE
e2e: Add new proposal metadata fields.

### ISSUE THREAD

**Issue by amassarwi** [decred/politeiagui#2481]
E2E tests need to updated to support the new proposal metadata fields which are being added 
in #2469.

**Comment by amassarwi** [comment]
Working on it

**Comment by lukebp** [comment]
This is part of #2459.  A feature issue already includes all tests for that feature.  Closing this issue.  Please do not reference this issue in any invoices.

**Comment by lukebp** [comment]
Also, why are these tests not being included in 2469?  New features and the tests for those features should be in the same PR.

**Comment by amassarwi** [comment]
Ok
