### ISSUE TITLE
Serve raw Markdown directly

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#2482]
With #2415 it is possible to obtain raw Markdown via the icon below the proposal, which leads to a URL like https://proposals.decred.org/record/e2d7b7d/raw .

I use this feature (thanks!) for archiving proposals and inspecting them locally, but it is a bit hard to use at the moment.

The new raw pages still require javascript to render and so it is not possible to get the content [directly](https://github.com/decred/politeiagui/pull/2416#issuecomment-872473040) with js turned off or with tools like `curl` or `wget` (for scripting). Also, when I just save the web page, the browser saves the HTML file with the `<noscript>` stub and no proposal text.

Most other pages need some complex server-side rendering setup to work without js, but I think raw Markdown does not need that and could be served directly to resolve the issues above. Then it would work similar to GitHub raw links [like this](https://github.com/decred/politeiagui/raw/62879da8c6869d519a1a1a723e1a88b0c1ed2d19/src/components/Proposal/RawProposal.jsx).

**Comment by lukebp** [comment]
I agree.  @tiagoalvesdulce what is the degree of difficulty in implementing this?

If it is a small item them we can include it in the existing pi proposal.  If it requires larger changes for some reason then we would need to wait to include it in a future proposal.

**Comment by tiagoalvesdulce** [comment]
If I register a route on React, it will require JS. Also, we have to fetch `records/v1/details` and run some javascript to decode the markdown payload. I think this is more of a server side or devops work. The decoding can be done in the server and the markdown served in a different address like github does (`raw.githubusercontent.com/...`)

**Comment by lukebp** [comment]
Ah right, forgot about decoding the base64.  The markdown needs to be served directly from the backend.  Clsoing this issue and replacing it with decred/politeia#1464.
