### ISSUE TITLE
Infinite loading on Proposal Details

### ISSUE THREAD

**Issue by tiagoalvesdulce** [decred/politeiagui#2487]
https://user-images.githubusercontent.com/13955303/126500152-28d3157b-f914-42a3-a603-7b131c2bccf9.mp4

This was introduced on https://github.com/decred/politeiagui/pull/2454. I think the culprit is https://github.com/decred/politeiagui/pull/2454/files#diff-021a1cb7d64dc9caf52a448712a80ea8de3a96146025a8deb514691ea0310eb3R63. To repro: create a new proposal > approve it > you will see the infinite loading. If you go to the vetted proposals page (home) and then go back to the proposal details page, it works.

@thi4go can you take a look at this?

**Comment by thi4go** [comment]
This is being caused by a wrong redirect using the full record token instead of the short. Opening up a fix
