### ISSUE TITLE
Firefox scroll bug

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2490]
There appears to be two scroll bars that show up on firefox that prevents the user from actually scrolling.  This is not present on chromium.

https://user-images.githubusercontent.com/9039877/126556982-854e2b81-e3d3-4ccf-9569-90352b8f3cce.mp4

![image](https://user-images.githubusercontent.com/9039877/126556758-f2c2a41a-ef13-4e08-9b0d-2411bcefcb06.png)

**Comment by victorgcramos** [comment]
This is fixed by https://github.com/decred/pi-ui/pull/353
