### ISSUE TITLE
discussion: migrate from react-mde to another markdown editor

### ISSUE THREAD

**Issue by victorgcramos** [decred/politeiagui#2493]
The currently used Markdown editor [react-mde](https://github.com/andrerpena/react-mde) is no longer maintained, and the repo is now archived. In order to scale the maintainability, we should explore new alternatives to this one.

This issue is opened so we can discuss those alternatives and figure out the best solution for it.

**Comment by lukebp** [comment]
This seems to be the second most popular react markdown editor.

https://github.com/uiwjs/react-md-editor

Demo: https://uiwjs.github.io/react-md-editor/

**Comment by lukebp** [comment]
This is likely going to be a large chunk of work.  This work will need to wait so that it can be included in the next pi proposal.

**Comment by lukebp** [comment]
This issue is being replaced by the #2574 discussion.  Issues should be specific and actionable.  The discussion feature should be used for things that need to be documented or discussed, but do not have actionable work yet.
