### ISSUE TITLE
Add warning to markdown editor

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2496]
When you create a proposal draft the data is saved locally to the user's browser until they submit the proposal.  If something goes wrong with the user's browser or computer, it is not uncommon for the proposal draft to be deleted and unrecoverable.  Issues like these are tricky from a dev standpoint because there are variables specific to the user's local setup that are likely contributing to the issue and make it hard to identify the root cause or if there's even something that can be done about it.

A warning message should be added to the markdown editor says:

"Drafts are saved locally to your browser and are not recoverable if something goes wrong.  We recommend drafting the content offline then using the editor to submit the final version."

**Comment by victorgcramos** [comment]
on it!
