### ISSUE TITLE
Update dark mode toggle switch

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2497]
The dark mode setting currently uses a toggle switch.

![image](https://user-images.githubusercontent.com/9039877/126991225-c19bc84b-2eb8-42bc-a433-d20707a1e7a2.png)

dcrdata has a nice icon for their dark mode.  We should use this icon as well.  It provides a better UX and its good for features to be consistent across the various Decred codebases.

![image](https://user-images.githubusercontent.com/9039877/126991583-8e76c9e2-edc2-490a-9fa8-7d0ef97083b9.png)
![image](https://user-images.githubusercontent.com/9039877/126991594-6c04f4a3-bb1a-4367-8794-f609fed08b20.png)

**Comment by amassarwi** [comment]
Nice suggestion 👍🏽

**Comment by linnutee** [comment]
Mentioning we've just worked out an updated version of for CMS and created the icons based grid. @MariaPleshkova can post here as well after the cms issue. Preferable to keep using this toggle, and add icons in there, as that indicates switching something on off rather than going to another page (as it's near nav + log out). 


<img width="1106" alt="Screenshot 2021-07-27 at 16 48 53" src="https://user-images.githubusercontent.com/17774057/127165473-be6707e9-4053-40a3-b476-619abb4a5829.png">

**Comment by lukebp** [comment]
@linnutee those look good.  Thanks for posting.  Let's go in that direction.

**Comment by lukebp** [comment]
@linnutee where can we get those image assets from?

**Comment by linnutee** [comment]
Figma: https://www.figma.com/file/RuzhkKo9fUjKQLqGbUPjHl/decred-piui-cms?node-id=307%3A738

This one is an example for CMS, though would apply to proposals the same way. 
Just mentioning there's a size change needed. Made the button 52x26px, so it could fit a reasonbly sized 18x18px icon within it.

**Comment by MariaPleshkova** [comment]
@lukebp 
Added an example for Pi to **decred - piui - politeia** Figma file:
https://www.figma.com/file/1pSibJb3COXW39IJJvzxJ8/decred-piui-politeia?node-id=208%3A6124

We changed the toggle view itself and moved the stroke that previously was between Log In and Sigh Up to the space between the toggle and those menu items.
The spacing is 30px between all elements there (toggle - _30px_ - line - _30px_ - Log In - _30 px_ - Sign Up)

![image](https://user-images.githubusercontent.com/8841018/127818243-dbf5dc06-473e-4b96-b596-c3c9e35f19da.png)

Same for tablet (made clickable area bigger though, 102x62px)
![image](https://user-images.githubusercontent.com/8841018/127827324-cc0d5c75-95c3-4247-af75-c59c22d16fdc.png)


And the same for mobile (completely removed the line between items, as they're already quite far from each other):
![image](https://user-images.githubusercontent.com/8841018/127827160-0b44c850-98be-4cab-9fe4-aa3789aa5850.png)

**Comment by lukebp** [comment]
@linnutee @MariaPleshkova it doesn't look like we can access the figma file.

![image](https://user-images.githubusercontent.com/9039877/132859985-bc8d8812-fc85-4d8d-acad-9af9e8f7fa3d.png)

**Comment by MariaPleshkova** [comment]
@lukebp please, try again. Updated the privacy setting

**Comment by lukebp** [comment]
@MariaPleshkova works now.  Thanks.

@vibros68 you can pick this issue up now.

**Comment by vibros68** [comment]
Yes. I am on it
