### ISSUE TITLE
Improve identity error message.

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2516]
The invalid identity error message that is displayed when attempting to authorize a vote is:

![image](https://user-images.githubusercontent.com/9039877/128219876-c7a8684c-8975-4a8a-b293-f481702b10ef.png)

A more helpful error message is the one we display for proposal submissions since it tells the user how to fix it.

![image](https://user-images.githubusercontent.com/9039877/128219971-4b5af6fc-9822-48cd-aba7-fa9aa067452b.png)

We should update the first error message to be more like the second error message.

**Comment by thi4go** [comment]
on this
