### ISSUE TITLE
Admin records page broken

### ISSUE THREAD

**Issue by victorgcramos** [decred/politeiagui#2519]
When you access admin records page you'll notice something like this.

<img width="1558" alt="Screen Shot 2021-08-06 at 4 34 24 PM" src="https://user-images.githubusercontent.com/22639213/128562841-0f036c5c-08ab-454b-90c8-0b9d0f060259.png">

Error details:
<img width="1025" alt="Screen Shot 2021-08-06 at 4 37 01 PM" src="https://user-images.githubusercontent.com/22639213/128562947-298d4e19-268b-411f-83b9-afa617730aee.png">

Edit: it happens when there are no existing records.

**Comment by amass01** [comment]
on it

**Comment by amass01** [comment]
![image](https://user-images.githubusercontent.com/10324528/128784213-2be98ad6-4434-485a-a454-68626a450a82.png)

Not able to reproduce, tested also adding new unreviewed proposal then approved it and
again the empty list looks good.

**Comment by lukebp** [comment]
I was able to reproduce this on test-proposals initially, but clearing browser data fixed it.  You probably just need to clear your browser data or try it in a private window.

**Comment by lukebp** [comment]
Closing this since it's probably not a bug.  If you're still able to reproduce it you can open this back up with more detailed reproduction steps.

**Comment by lukebp** [comment]
I'm not able to reproduce this on test-proposals, but I can locally.  If you're having trouble reproducing it, clear out all the records in your backend and try again.
