### ISSUE TITLE
Improve record attachments error message

### ISSUE THREAD

**Issue by victorgcramos** [decred/politeiagui#2528]
<img width="1112" alt="Screen Shot 2021-08-10 at 3 30 04 PM" src="https://user-images.githubusercontent.com/22639213/128915265-843d7265-8d17-4791-9b8e-c660d07b57fa.png">

From the error message, it's not trivial to understand that the **file type** is invalid.

## How to reproduce it
1. Go to `record/new`
2. Fill all metadata form
3. Drag and drop this gif below into the Markdown Editor
![2518-flat-mode-button](https://user-images.githubusercontent.com/22639213/128915663-880e2766-31c0-41d4-b202-b4b827cc80ba.gif)
> this should happen for every invalid type. Also tested with .pdf files
4. Press the `Submit` button

**Comment by lukebp** [comment]
It looks like the error message is also wrong.  Attachments are included as files, not mdstreams.  The error being returned should be `ErrorCodeFileMIMETypeUnsupported`.

https://github.com/decred/politeia/blob/d2a4ea8f850f84341d7d4882eea96c4821320c97/politeiawww/api/records/v1/v1.go#L38

Is there a bug in the gui error message mappings?
