### ISSUE TITLE
Under review pagination bug

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2530]
This example was taken from test-proposals.  The ticketvote inventory reply is shown below.

![image](https://user-images.githubusercontent.com/9039877/128938667-433bd26d-f5f5-4ecd-977a-3b06cf8078e9.png)

This is how the "Under Review" list view is populated.

https://user-images.githubusercontent.com/9039877/128938870-d077878b-7b77-4120-9f96-d71b0078d51b.mp4

The page size when retreiving proposals is a maximum of 5 proposals per request.  Only 5 proposals are being retreived here, but its using two separate requests to do so despite.  This is incorrect.

It should be seemlessly retrieving a page of proposals (5 proposals) per request.  If there is not a full page of proposals for a particular vote status then it should move to the next vote status until it fills up a full page for the request.  As the user scrolls down, it should continue to do this until it reaches the end of the unauthorized list.  

If the array of tokens in the ticketvote inventory is equal to the inventory page size (20 tokens) then it indicates another inventory page should be retreived.  It should not continue to the next vote status until all proposals have been retreived for the current vote status.

**Comment by vibros68** [comment]
I am on it
