### ISSUE TITLE
Record submission error msg improvement.

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2531]
When you submit a proposal and it results in some type of error, there's no longer any indication that an error occured because of where the error message placement is.  I have to scroll up to see that there was an error.  This is a confusing UX.

![image](https://user-images.githubusercontent.com/9039877/129033424-713f3951-d88e-4511-a464-387768e293e6.png)

![image](https://user-images.githubusercontent.com/9039877/129033635-4aa97318-1dd5-40be-8801-ab3e1565d289.png)

I think the way to improve this is to move the error message banner to below the submit button.

**Comment by thi4go** [comment]
will fix
