### ISSUE TITLE
Expired session bug.

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2538]
If the session expires while the user is editting their proposal, a "Forbidden" error message is displayed.

![image](https://user-images.githubusercontent.com/9039877/129200687-9cc4504d-a352-448e-85bd-a47aa4d45f24.png)

If I refresh the page, the error message goes away, but the submit button is still grayed out.

![image](https://user-images.githubusercontent.com/9039877/129200906-ea29fb95-1c15-481a-98f8-ddd75f8beef4.png)

This UX does not give the user any information on what the problem is or how to correct it.  Shouldn't the login modal be displayed on these errors?

**Comment by victorgcramos** [comment]
on it. I agree with your points.

**Comment by lukebp** [comment]
You can update the max session age to make testing easier.

https://github.com/decred/politeia/blob/master/politeiawww/sessions/sessions.go#L20
