### ISSUE TITLE
Markdown tables are broken

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#2540]
I'm pretty sure it rendered correctly in the [translations proposal](https://proposals.decred.org/record/af9942a) previously, but now it shows:

![tables](https://user-images.githubusercontent.com/24484727/129751001-50d4cda7-9f66-4ca3-a441-f0a40b4e1ca2.png)

I just pasted the code into gist and it renders as a table so I think the syntax is correct.

**Comment by victorgcramos** [comment]
on it!
