### ISSUE TITLE
Make list item formatting consistent.

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2544]
The two images below were taken from [mainnet proposals](https://proposals.decred.org).

![image](https://user-images.githubusercontent.com/9039877/130278754-403de548-565f-457b-9038-163fb54cb90e.png)

![image](https://user-images.githubusercontent.com/9039877/130278839-3711035e-f002-4079-93fc-c761558aea86.png)

There are some issues with the abandoned proposal:

1. It is missing the proposal version (version 1).
2. It displays the abandoned timestamp in place of the edited timestamp.

The abandoned timestamp placement was probably done that way because of how censored proposals are displayed.

![image](https://user-images.githubusercontent.com/9039877/130279386-72967740-0930-4780-abb8-b339377a08f7.png)

We should be consistent with the formatting of these list items.  We can do this by:

1. Displaying the edited timestamp and the proposal version in the same place for all public, abandoned, and censored proposals.
2. Displaying the censored/abandoned timestamp in the same place as the `vote ended` timestamp, i.e. underneath the tag in the top right corner.

**Comment by thi4go** [comment]
on this
