### ISSUE TITLE
Bad error message on proposal edit

### ISSUE THREAD

**Issue by tiagoalvesdulce** [decred/politeiagui#2546]
When editing a RFP proposal, if I keep the start date older than the actual date, the GUI lets me submit the proposal but shows a bad error message.

Error message:
<img width="1083" alt="Screen Shot 2021-08-23 at 10 28 17" src="https://user-images.githubusercontent.com/13955303/130624858-3996a75a-9be2-4840-a0e9-15f0293119c1.png">

Error on www:
<img width="726" alt="Screen Shot 2021-08-23 at 10 28 29" src="https://user-images.githubusercontent.com/13955303/130625242-eda69dfe-a804-4dea-bb35-64becab016b3.png">

**Comment by amass01** [comment]
will address

**Comment by lukebp** [comment]
The original issue is slightly inaccurate. RFP's do not have start/end dates and a user error will returned if the user attempts to submit and RFP with start/end dates.  There are, however, two bugs being reported here:

1. The pi plugin error messages are not being displayed correctly.
2. The gui is not validating the start/end dates on proposal edit.
