### ISSUE TITLE
Comments view all navigation bug

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2551]
![image](https://user-images.githubusercontent.com/9039877/130989044-a06bcdff-aaf8-4aa7-bbf5-d55726a2aa29.png)

The `View all` comments button takes you back to the proposal details page.

https://proposals.decred.org/record/58d9f46

The expected behavior is for it to take to back to the comments section of the proposal details page.

https://proposals.decred.org/record/58d9f46?scrollToComments=true

**Comment by vibros68** [comment]
I am on it
