### ISSUE TITLE
2FA error flow

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2556]
If you input the wrong 2FA code the 2FA modal is closed out and the error message is displayed on the login screen.  The use must click the login button to re-attempt the 2FA code.  A better UX, and one that @victorgcramos has already implemented on the login modal in #2548, is to display the error message on the 2FA modal instead of the login screen so that the user does not have to click the login button again when re-inputing the 2FA code.

**Comment by victorgcramos** [comment]
Roger that

**Comment by victorgcramos** [comment]
I think it's closed by #2548.

**Comment by lukebp** [comment]
This has flickering that needs to be fixed.  The username/password modal gets rendered on error that causes flickering.


https://user-images.githubusercontent.com/9039877/134420062-1d1ffa55-bebb-4a85-9dda-d8e05d9605b7.mp4

**Comment by victorgcramos** [comment]
okay, I'll include both e2e and this fix on the same PR. Sounds good?

**Comment by lukebp** [comment]
Get the bug fixed before you do anything else so that we can continue with the release.

**Comment by victorgcramos** [comment]
sure! The screen flickering can only be noticed on firefox and that's why I thought it was fixed. Working on it!

**Comment by lukebp** [comment]
Good to know.  Maybe when we test PRs we should start adding what browser we tested it with.  I'll start adding that to my review comments.
