### ISSUE TITLE
research: add e2e tests to the build pipeline.

### ISSUE THREAD

**Issue by amass01** [decred/politeiagui#2565]
We would like to add the e2e tests to our build pipeline to make sure PRs
aren't breaking them.

**Comment by lukebp** [comment]
Issues needs to be specific and actionable.  Does this issue meet that criteria? If not, please close it.

**Comment by amass01** [comment]
I see we just enabled discussions in this repo, I guess this could be converted to a discussion then ?

**Comment by amass01** [comment]
A new discussion crated, closing.
