### ISSUE TITLE
Use full length token for dcrdata link

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2569]
The dcrdata voting charts link currently uses the shortened token, but it needs to use the full length token.

https://proposals.decred.org/record/58d9f46

Example:
https://dcrdata.decred.org/proposal/58d9f46 - this is broken
https://dcrdata.decred.org/proposal/58d9f4664777775d - this works

dcrdata button
![image](https://user-images.githubusercontent.com/9039877/132858741-2e8d027c-9d43-42fb-830b-24dcc674ce09.png)

**Comment by amass01** [comment]
can fix
