### ISSUE TITLE
Under Review tab infinite loading for empty inventory

### ISSUE THREAD

**Issue by victorgcramos** [decred/politeiagui#2602]
Introduced by #2552.

This is very minor and can't be noticed on test-proposals since we won't have an **empty inventory** because approved proposals are never deleted. However, it's still a bug and may be noticed if we use the `useProposalsBatch` on other multi-status tabs in the future.

![2552-under-review-empty-lists](https://user-images.githubusercontent.com/22639213/134536710-05f1245f-7502-4c16-a145-62fb4a0f45e3.gif)

Works for when you have at least one approved proposal, and stops loading after a page refresh.

### E2E Test Cases

I wrote down some E2E tests in case you don't want to clean your local inventory:

`teste2e/cypress/e2e/proposal/list.js`
```javascript
it("should switch tabs and show empty message when list is empty", () => {
  cy.middleware("ticketvote.inventory", {
    authorized: 0,
    started: 0,
    unauthorized: 0,
    approved: 0,
    rejected: 0,
    ineligible: 0
  });
  cy.middleware("records.records");

  cy.visit(`/`);
  cy.wait("@ticketvote.inventory");
  cy.findByTestId("help-message").should("be.visible");
  cy.scrollTo("bottom");
  // switch to another tab
  cy.findByTestId("tab-1").click();
  // no approved proposals
  cy.assertListLengthByTestId("record-title", 0);
  // back to empty list tab
  cy.findByTestId("tab-0").click();
  // wait to see if no requests are done, since inventory is fully fetched
  cy.wait(1000);
  cy.findByTestId("help-message").should("be.visible");
});
```

Add the `data-testid="help-message"` on `src/components/HelpMessage/HelpMessage.jsx`
```javascript
  // ...
  return (
    <div
      className={classNames("justify-center", styles.container)}
      data-testid="help-message">
    // ...
    </div>
  );
```

### Tested on:
-  Brave Version 1.29.77 Chromium: 93.0.4577.63 (Official Build) (x86_64)
- Chrome Version 94.0.4606.54 (Official Build) (x86_64) (Cypress controlled environment)

**Comment by lukebp** [comment]
Good catch.  We need to fix this for the release.
