### ISSUE TITLE
Bug: Start Runoff Vote fails in list view.

### ISSUE THREAD

**Issue by amass01** [decred/politeiagui#2616]
When clicking start run off vote on a RFP from the **list** view, I hit the following error:

![image](https://user-images.githubusercontent.com/10324528/135097871-c31d945c-2074-40c6-a348-038b2f2a324b.png)

It works as expected from the **details** view though.

**Comment by vibros68** [comment]
After make a RFP. I can not see the `run off vote` button on the **list** view. Only see on the detail view

**Comment by lukebp** [comment]
@vibros68 I'm seeing the same thing.  This is a bug.  The `Start Runoff Vote` button should be displayed on both the list view and the proposal details view.

Also, a quick tip.  The `pictl rfptest` command is helpful when setting up and testing the RFP workflow.

Let me know if you run into any issues or have any questions.
