### ISSUE TITLE
International date format for start and end dates

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#2634]
Proposal start and end dates use the `M/D/Y` format that takes extra time to disambiguate, e.g. "am I looking at Aug 9 or Sep 8"?

![pi-date-format](https://user-images.githubusercontent.com/24484727/137020727-5d4a2456-0d4b-4ea8-8f9c-fb3e761d255e.png)

It might be common in some regions, but on the global scale it is the [least used](https://en.wikipedia.org/wiki/Date_format_by_country) format after `DMY` and `YMD`.

Let's change it to either `2021-09-08` or the more user-friendly `08 Sep 2021` used in other Pi timestamps.

**Comment by lukebp** [comment]
Let's use the `08 Sep 2021` format.  It's easy to read for everyone.
