### ISSUE TITLE
e2e: Mock structure coordination checklist.

### ISSUE THREAD

**Issue by victorgcramos** [decred/politeiagui#2642]
#2624 introduced a new approach of mocking politeiagui's test data. This is required for running tests consistently without having your local environment configured for the tests.

The idea behind tests is to have a **defined input + expected output**, but it's hard to define and persist the input among all dev envs when our backend uses a timestamped storage, hence, either we create the conditions on tests run-time, or we create a structure that ensures the correct data. And, of course, the second is the best solution for our case.

> let's avoid the old famous "works on my env" 😁 

This issue is used for tracking the testing upgrade process.

****

### Proposal

- [x] List (#2624)
- [x] Detail (#2643)
- [x] Create (#2644)
- [x] Edit (#2645)
- [ ] Form Errors (#2706)

### Comments

- [x] Author Updates (#2707)
- [x] Comments (#2708)
- [ ] Comments Votes

### Admin

- [ ] Account
- [x] Comments (#2732)
- [x] Proposals (#2731)

### User

- [ ] Login
- [ ] 2FA
- [ ] Register

****

Once we move the tests and all support files to the new structure, we can deprecate the old ones.

****

PS: currently the user layer on politeia plugin architecture is under development (https://github.com/decred/politeia/pull/1552), so we will wait until it becomes complete to mock user and ~www~ http routes.

**Comment by amass01** [comment]
🚀

**Comment by tiagoalvesdulce** [comment]
🚀 👍

**Comment by victorgcramos** [comment]
User e2e tests will be implemented on the new plugin architecture.

Closing this.
