### ISSUE TITLE
e2e: Proposal Details mock structure.

### ISSUE THREAD

**Issue by victorgcramos** [decred/politeiagui#2643]
Part of #2642.

Proposal Details tests are still using the online api approach. We need to migrate it to the new mock structure introduced by (#2624).

We currently don't need new test suites, the main focus here is to first migrate and then code more tests using this new structure.

## Tips and Tricks

- Only mock requests related to Proposal Details page
- Run only details test file: `yarn cy:run -- --spec "cypress/e2e/proposal/detail.js"`
- Setup the API environment for all possible routes reached by the tests suite using a `beforeEach` statement
- Check on politeiawww's logs to check if all requests were mocked properly
- Use `proposal/list.js` tests as reference

**Comment by vibros68** [comment]
I am on it

**Comment by vibros68** [comment]
I am waiting for [#2692](https://github.com/decred/politeiagui/pull/2692) be merged because there are some function are reused in there
