### ISSUE TITLE
e2e: Proposal Create mock structure.

### ISSUE THREAD

**Issue by victorgcramos** [decred/politeiagui#2644]
Part of #2642.

Proposal Create tests are still using the online api approach. We need to migrate it to the new mock structure introduced by (#2624).

We currently don't need new test suites, the main focus here is to first migrate and then code more tests using this new structure.

## Tips and Tricks

- Only mock requests related to Proposal Create (`record/new`) page
- Run only `create` test file: `yarn cy:run -- --spec "cypress/e2e/proposal/create.js"`
- Setup the API environment for all possible routes reached by the tests suite using a `beforeEach` statement
- Check on politeiawww's logs to check if all requests were mocked properly
- Use `proposal/list.js` tests as reference

**Comment by vibros68** [comment]
I am on it
