### ISSUE TITLE
Make proposal details title a link.

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2649]
Clicking the proposal title on the proposal details page should navigate the user back to the base proposal details page.

For example, if the user is looking through a comment thread:

https://proposals.decred.org/record/c1f5b5c/comments/3

Clicking on the proposal title should navigate them back to:

https://proposals.decred.org/record/c1f5b5c

This behavior is used by sites like reddit.

**Comment by vibros68** [comment]
I am on it
