### ISSUE TITLE
List view re-ordering bug.

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2654]
This bug was discovered on test-proposals.decred.org and can be reproduced there right now as well.  I was using firefox.

1. Navigate to the "Approved" list view.  The proposals are ordered correctly.
2. Navigate to the "Vote on Me" proposal details back.
3. Click your "Back" browser button to go back to the list views.
4. The gui is re-ordering the proposals for some reason and displaying them in the incorrect order now.  The "Vote on Me" proposal has been moved down in the list when it shouldn't have been.

https://user-images.githubusercontent.com/9039877/142009501-324bbad7-d951-4ef4-927b-21b075c431fe.mp4

**Comment by victorgcramos** [comment]
on it!

**Comment by lukebp** [comment]
@tiagoalvesdulce do we know what PR introduced this bug?
