### ISSUE TITLE
Incorrect 'Go Back' button behavior.

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2655]
When you select the 'Go Back' button on a proposal details page, it takes you back to the "Under Discussion" tab of the home page, regardless of where you came from.  Here are some examples:

- When viewing unvetted proposals, I want to go back to the unvetted proposal list, not the home page.
- When viewing proposals in a list such as "Approved", I want to go back to the list that I came from, not the home page.

Previously, the "Go Back" button behavior would match the same behavior as the browser "Back" button.  This caused UX issues when navigating comment threads, so it was updated in #2638 to the current behavior.  This new behavior causes is own set of UX issues.

I think the correct behavior for the "Go Back" button is to go back to the previous page when ignorning all URL params and record sub-routes.  For example, if a user follows this navigation sequence:

1. https://test-proposals.decred.org/?tab=approved
2. https://test-proposals.decred.org/record/a6a5084
3. https://test-proposals.decred.org/record/a6a5084/comments/1
4. Go Back

This should take them back to step 1, not step 2.

Another example:

1. https://test-proposals.decred.org/?tab=approved
2. https://test-proposals.decred.org/record/a6a5084
3. https://test-proposals.decred.org/record/a6a5084?scrollToComments=true
4. Go Back

Again, this should take them back to step 1, not step 2.

**Comment by victorgcramos** [comment]
on it!
