### ISSUE TITLE
Incorrect identity error on modal.

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2656]
The identity error is not being displayed correctly when the error is encountered on the billing status modal.

![image](https://user-images.githubusercontent.com/9039877/142034287-37cbb12d-a9e9-4426-83ad-d0330da4a112.png)

**Comment by tiagoalvesdulce** [comment]
This is the error I'm seeing on my end:

<img width="653" alt="Screen Shot 2021-11-16 at 15 23 18" src="https://user-images.githubusercontent.com/13955303/142043406-1885e4bb-bf75-4448-9635-911b2493f6d4.png">

**Comment by lukebp** [comment]
@tiagoalvesdulce should this be the global identity error that we added?

https://github.com/decred/politeiagui/pull/2623#issuecomment-965882480

**Comment by lukebp** [comment]
How did you reproduce the error?  The error I posted was from a private window where the identity did not exist at all.

**Comment by tiagoalvesdulce** [comment]
hmm, I ran `pictl userkeyupdate` and tried to set the billing status.

**Comment by lukebp** [comment]
@tiagoalvesdulce so that's a different identity error (wrong user identity vs no user identity).  Both should result in the global user error though that was added in 2623 and that tells the user how to fix the problem.

**Comment by victorgcramos** [comment]
I could reproduce it. On it! 🧑‍🏭

**Comment by lukebp** [comment]
This bug was a result of #2623 failing to consider this case.
