### ISSUE TITLE
Fix RFP proposal and billing status.

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2657]
RFP proposals do not bill against the treasury and, therefor, do not have a billing status.  This was not accounted for in the original billing status and proposal status implemenations.  decred/politeia#1576 and decred/politeia#1577 fix this issue on the backend.  Two things must be updated on the frontend to reflect these changes:

- RFP proposals should not have the "Set Billing Status" button displayed for them.  This does not include RFP submissions since submissions do bill against the treasury and do have a billing status.
- An `approved` proposal status needs to be added and an `Approved` tag needs to be displayed for RFP proposals.  `missing` is currently displayed.

![image](https://user-images.githubusercontent.com/9039877/142221938-3f597e33-dbdf-4849-be76-e6950849f2a0.png)

**Comment by victorgcramos** [comment]
On it!

**Comment by lukebp** [comment]
@victorgcramos do we know what PR introduced this bug?  2609?

**Comment by victorgcramos** [comment]
I think so.

**Comment by lukebp** [comment]
This bug was a result of #2609 not considering this case.
