### ISSUE TITLE
Set billing status button bug.

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2669]
1. Load the "Approved" list view
2. Login as an admin
3. Go back to the "Approved" list view.  The "Set Billing Status" button is not shown for active proposals (bug).
4. Click on an active proposal.  The gui crashes (bug).

https://user-images.githubusercontent.com/9039877/142897493-24a8f3ec-c973-4a9c-b2c4-0edaf60f90e3.mp4

**Comment by lukebp** [comment]
@victorgcramos do we know what PR introduced this bug?

**Comment by victorgcramos** [comment]
I think the initial implementation did not cover this case. Actually, the billing statuses were only fetched together with records batch fetch. I'd say #2629 "introduced" it.

**Comment by lukebp** [comment]
Right, this bug is a result of 2629 failing to consider this case.
