### ISSUE TITLE
Show published date again

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#2675]
Published date is an important piece of info I often look at. It was shown on the old UI:

![pi-pubdate-1](https://user-images.githubusercontent.com/24484727/143304365-43dec0bf-81eb-481d-b06f-5f8926991ade.png)

but missing from the new UI:

![pi-pubdate-2](https://user-images.githubusercontent.com/24484727/143304383-ab01afc0-66ff-4358-ba74-d272ef855777.png)

I can get this info from dcrdata:

![pi-pubdate-3](https://user-images.githubusercontent.com/24484727/143304426-e985b9bf-e400-4a53-98d5-ebef6d54ac53.png)

But miss having it directly on Pi when surfing around and researching stuff.

**Comment by lukebp** [comment]
This was suppose to be fixed back in June on #2430.

@tiagoalvesdulce @victorgcramos what PR broke this and why are we having to fix the same exact issue, multiple times within months of each other?

**Comment by lukebp** [comment]
Introduced by #2454 .  Let's make sure to add e2e tests for the fix this time.

**Comment by victorgcramos** [comment]
Also, as discussed on Matrix, we should include the timestamps also for mobile.

**Comment by victorgcramos** [comment]
On it!
