### ISSUE TITLE
Show reason for censored comments

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#2686]
I'd like to see the reason why a comment was censored. It is already present in the comments bundle (it says "Duplicate comment" - nice!).

![pi-comment-censored](https://user-images.githubusercontent.com/24484727/144685253-5d4f8666-2823-46aa-a5fc-f53ca7d593ad.png)

**Comment by lukebp** [comment]
I'd like to hear input from the politeiagui devs on the suggested UI for this.  Should we go with the same UI as the proposal status change messages?

**Comment by tiagoalvesdulce** [comment]
I think we could add a `See reason` link and open a modal with the content. This way we don't crowd the UI.

**Comment by amass01** [comment]
> I think we could add a `See reason` link and open a modal with the content. This way we don't crowd the UI.

Nice idea, I would make it an expandable section with an arrow, collapsed by default, what do you think ? @tiagoalvesdulce

**Comment by xaur** [comment]
Seeing reason without extra clicks is faster and is subject to page text search. Is there a risk of UI clutter?

**Comment by amass01** [comment]
@xaur I agree, maybe we should first try showing it next to `Censored by moderators` text

**Comment by amass01** [comment]
I'll give it a try
