### ISSUE TITLE
 Unstable order of data in Proposal Bundle download

### ISSUE THREAD

**Issue by amass01** [decred/politeiagui#2691]
Originally reported by @xaur on https://github.com/decred/politeia/issues/1595, but the it's a gui task:

> I noticed a diff in two `Proposal Bundle` downloads for [this proposal](https://proposals.decred.org/record/427e1d4) made on different days.
> 
> In my first download the `.record.files` field is like `["proposalmetadata.json", "index.md"]`, but in the second it was reversed.
> 
> This is not technically a bug. My use case here is just diffing the downloads to see how they evolve over time. Consider this testing - it is convenient when response diffs are minimal. Other things I can image are: removing avoidable variance in responses may facilitate caching, and possibly harden against probing techniques (just theorizing here).
> 
> I guess this belongs to the backend but please move to the GUI repo if I am wrong.

**Comment by amass01** [comment]
@xaur @lukebp 

I think this one is a waste of time, I tried to download the bundle of two different proposals on two 
different browsers multiple times and didn't notice any difference in the files structure.

**Comment by lukebp** [comment]
Is there any code on the backend that would prevent a deterministic ordering of the files?

**Comment by amass01** [comment]
Good question, will check

**Comment by xaur** [comment]
I can search if I still have those differing downloads if that helps. I think understanding unexpected behavior is not a waste of time but it's up to you ofc :)

Some guesses on reproducing. I caught the difference by comparing bundles downloaded on different days (1), each bundle capturing more comments than the previous one (2). So it might be possible to trigger the ordering change if you "touch" a proposal in some way (like leave a comment), or "shake up" its memory (like by restarting the server holding/building those bundles).

**Comment by amass01** [comment]
> Is there any code on the backend that would prevent a deterministic ordering of the files?

I think I found the code in the backend that could be causing that:
https://github.com/decred/politeia/blob/master/politeiad/backendv2/tstorebe/tstore/record.go#L649-L658

We will need to iterate over these maps deterministically to ensure order is consistent. 

I'm closing this issue, and reopening the backend one.
