### ISSUE TITLE
We need to create a reset identity during additional failures

### ISSUE THREAD

**Issue by marcopeereboom** [decred/politeiagui#270]
There are some corner cases where the identity may be lost but you need it to sign up. We probably need to expand the dbutil tool to reset certain fields to handle these corner cases.

**Comment by sndurkin** [comment]
This has been implemented in `politeiawww_dbutil` in https://github.com/decred/politeia/commit/ab2eaee225e22d1dc71001555e2b44d0ae3579e6.
