### ISSUE TITLE
[plugin-architecture] Use variables on breakpoints

### ISSUE THREAD

**Issue by tiagoalvesdulce** [decred/politeiagui#2752]
Investigate ways to use variables on our breakpoints. [We can't use CSS variables](https://stackoverflow.com/questions/40722882/css-native-variables-not-working-in-media-queries).

Alternatives:
- Use [custom media queries](https://www.w3.org/TR/mediaqueries-5/#custom-mq) - depends on PostCSS
- Use [postcss breakpoints](https://www.npmjs.com/package/postcss-breakpoints) - depends on PostCSS

**Comment by tiagoalvesdulce** [comment]
* Use [CSS Environment Variables](https://developer.mozilla.org/en-US/docs/Web/CSS/env). [Can I use?](https://caniuse.com/css-env-function)

**Comment by tiagoalvesdulce** [comment]
@victorgcramos what's your opinion?

**Comment by victorgcramos** [comment]
Sounds good! I'd go for CSS Env vars. IMO it's a cleaner solution

**Comment by tiagoalvesdulce** [comment]
Closed by https://github.com/decred/politeiagui/pull/2849
