### ISSUE TITLE
Give UI feedback after Starting Vote succeed

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#276]
Maybe call `/activeVotes` when starting vote succeeds so the UI will update which votes are currently active.

**Comment by vctt94** [comment]
I tried doing that on #262, but I do not like how the UX is. Because after finishing spinning until get start vote response, It starts spinning again until fetch the activeVotes, but we can try that.

**Comment by fernandoabolafio** [comment]
@vctt94 I've opened a PR on that already. See how you like it #277 we can add more changes on it.
