### ISSUE TITLE
[plugin-architecture] External URL error on router navigation

### ISSUE THREAD

**Issue by victorgcramos** [decred/politeiagui#2767]
`window.history.pushState` does not allow external domain urls, and it breaks the app logging the following error when you pass an external domain to `router.navigateTo` method.

```log
router.js:82 Uncaught DOMException: Failed to execute 'pushState' on 'History': A history state object with URL 'https://google.com/' cannot be created in a document with origin 'https://localhost:3000' and URL 'https://localhost:3000/'
```

Example:
```javascript
<button onClick={() => router.navigateTo("https://google.com")}>
  Navigate!
</button>
```

**Comment by tiagoalvesdulce** [comment]
I agree it should not break the app. But to navigate to external URLs `window` methods should be used instead.
