### ISSUE TITLE
Proposal date bugs.

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2770]
1. The start date picker defaults to the ealiest allowed start date, which can be in the past.  It should default to the current date.

![image](https://user-images.githubusercontent.com/9039877/170058803-8975239f-e773-4ba9-9afc-90c1557fb881.png)

2. The error message is not human readable.  These should be converted to human readable dates.

![image](https://user-images.githubusercontent.com/9039877/170058580-fe5e9a5b-fde1-42ae-b50d-d504c838c813.png)

**Comment by lukebp** [comment]
Let me add a third bug to this.

3.  When I select the min allowed start date in the date picker and max allowed end date in th date picker, I get an error.  The gui should only allow dates that will not cause an error.

**Comment by victorgcramos** [comment]
On it!

**Comment by lukebp** [comment]
Requires decred/politeia#1637
