### ISSUE TITLE
[plugin-architecture] Fetching duplicate comments counts on Home

### ISSUE THREAD

**Issue by victorgcramos** [decred/politeiagui#2807]
Introduced by 3ad405e37741401c039aabe34bc447567c8e8c6e

While navigating on Home page, I noticed that the list always fetch the first token from the batch. From what I could see, the token is never removed from the "queue".

<img width="837" alt="Screen Shot 2022-07-06 at 5 04 34 PM" src="https://user-images.githubusercontent.com/22639213/177633665-3fc52a90-ff59-46d9-9cfd-7b17314d2dc2.png">
<img width="839" alt="Screen Shot 2022-07-06 at 5 04 56 PM" src="https://user-images.githubusercontent.com/22639213/177633709-229ae033-e9c0-42d6-879c-ff8f1dabf5f3.png">

**Comment by tiagoalvesdulce** [comment]
Can't repro
