### ISSUE TITLE
[plugin-architecture] Warning being triggered by one of the Dropdown classnames

### ISSUE THREAD

**Issue by tiagoalvesdulce** [decred/politeiagui#2809]
<img width="754" alt="Screen Shot 2022-07-12 at 10 57 40" src="https://user-images.githubusercontent.com/13955303/178507691-229c9ecd-1206-40df-91e9-0cfd64562f75.png">

**Comment by victorgcramos** [comment]
Couldn't repro... Running latest master ([107daa9](https://github.com/decred/politeiagui/commit/107daa9db5bc89d43f50f7bb16125b5c461c53a3))

**Comment by tiagoalvesdulce** [comment]
Closing this. Probably caused by old pi-ui
