### ISSUE TITLE
[plugin-architecture] Voting proposals missing padding

### ISSUE THREAD

**Issue by victorgcramos** [decred/politeiagui#2825]
The 2 voting proposal cards should have some spacing between them, just like unauthorized proposals do.

<img width="914" alt="Screen Shot 2022-07-21 at 12 14 33 PM" src="https://user-images.githubusercontent.com/22639213/180250195-f6a03465-24f4-4c13-8656-20bcfcf2f21f.png">

**Comment by MohsinMalik2** [comment]
Hey there,
I'm a Frontend Developer and I think I can solve this issue according to the given instructions.

**Comment by tiagoalvesdulce** [comment]
@MohsinMalik2 please notice that the code for this is inside the `plugins-structure` folder because we are doing a refactor to the politeiagui architecture.

**Comment by victorgcramos** [comment]
Any updates on this one?
