### ISSUE TITLE
Navigating pages doesn't pull in the current session

### ISSUE THREAD

**Issue by sndurkin** [decred/politeiagui#286]
If you open 2 Politeia tabs and log in within the first tab, when you navigate through Politeia on the second one, you should now be logged in because your browser has a session.

**Comment by vctt94** [comment]
This behavior is because of CSRF deactivated when in localhost.

If you login at https://test-proposals.decred.org/ the session works fine.

**Comment by sndurkin** [comment]
It doesn't work on test-proposals.decred.org either. Try the following steps:

1. Open 2 Politeia tabs.
2. Log in on the first tab.
3. On the second tab, without refreshing the page, navigate somewhere (e.g. click the Politeia logo to navigate to the list of active proposals).

**Comment by vctt94** [comment]
I see, thanks for clarifying
