### ISSUE TITLE
Ensure the user knows to verify email links with the same browser

### ISSUE THREAD

**Issue by sndurkin** [decred/politeiagui#295]
The user needs to open verification links sent via email with the same browser that was used to generate them, because the UI signs them with the identity. The user needs to be aware of this for each of these cases (e.g. new user registration, etc).

**Comment by fernandoabolafio** [comment]
I will work on it.

**Comment by rrecuero** [comment]
Hi everyone. I have been following decred for quite a while, I am a big fan. I found this Medium post about contributing to Decred(https://medium.com/decred/how-to-get-hired-as-a-decred-contractor-e1435842df10).

I am going to have some free time the following days. Can I knock this one and the other tickets labeled as first issues?

**Comment by tiagoalvesdulce** [comment]
Hey @rrecuero, I've already reviewed 2 of your PRs, thank you for them! Feel free to work on issues, just make sure to leave a comment saying that you will work on that to prevent duplicate work. You might also want to [join us on Slack](https://slack.decred.org/). We discuss stuff related to politeia on the #politeia channel and you can ask for help there if you need.

**Comment by rrecuero** [comment]
Thank you @tiagoalvesdulce. I requested access to the Decred Slack. I'll do that. I'll grab this one

**Comment by sndurkin** [comment]
I don't think #410 completely addresses the issue. We need to ensure that users aren't going to have complaints about generating a key and then having to generate a new one next time they log in.

I was thinking we could show a warning before the identity is generated, explaining that it's tied to their current browser, so if they're using a private/incognito browsing session, it won't be persisted next time they log in. That way, they have the option of switching to another browser/window to perform the action.

CCing @fernandoabolafio @rrecuero

**Comment by sndurkin** [comment]
FYI @rrecuero, I'll work on what I mentioned, as I already have a PR open for some signup related fixes.
