### ISSUE TITLE
Store data is not being cleaned on logout

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#307]
There are some artifacts being left in the store after logout. 
Steps to reproduce are:
-> Login 
-> Logout
-> Create a new user 
The signup succeeds message shows the email of the previous logged in account.
![may-07-2018 10-26-33](https://user-images.githubusercontent.com/14864439/39704337-6235118a-51e1-11e8-8822-79e3bb1d2e9a.gif)

**Comment by tiagoalvesdulce** [comment]
I can work on this if you are not already @fernandoabolafio

**Comment by fernandoabolafio** [comment]
@tiagoalvesdulce  I will submit a PR on it right now. Would be nice if you review it afterward.
