### ISSUE TITLE
Create username cache

### ISSUE THREAD

**Issue by sndurkin** [decred/politeiagui#348]
Comments returned by www won't have the username populated, because in proposals with a lot of comments, the username would be duplicate information. It will provide a separate request to fetch usernames by user id, which the UI will use when the proposal details is loaded and request usernames for all user ids it doesn't know about. It will then cache them so it doesn't have to make duplicate requests. The cache will only live while the user stays on Politeia; refreshing the browser or navigating away will wipe it away.

Proposal lists will still have the username sent, so the UI can cache those by user id as they're received.

**Comment by xaur** [comment]
Looks like overoptimization. Do usernames consume so much data compared to proposal and comment texts?

**Comment by xaur** [comment]
Do you mean fetching by GUI from backend (I agree it is costly) or fetching by one backend layer from another?

From what I follow the "last" layer of backend does not serve usernames to the GUI and the solution is to add ways for the GUI to fetch and cache them. I was wondering why the last layer cannot have/cache all the necessary data and serve in one response, removing the need for further roundtrips and opening the door to full server side rendering for no-js clients.

**Comment by sndurkin** [comment]
Yeah, I mean fetching from one backend layer from another. Usernames (and even users) is a concept that we don't want to put into the `politeiad` layer, so they have to be added on by `politeiawww` before the reply is sent to the client.

**Comment by xaur** [comment]
Sounds reasonable to not have them in d, have them added by www and sent to client. This is how I imagined it should work. But this issue says they won't be sent to client by the www and that the client will need an extra request to fetch them. Sorry I'm missing it :S

_P.S. I'm unquiring merely as a curious external observer, since the idea of extra fetches catched my eye. I will perfectly understand if having a chat with me drains too much of your time, just let me know_

**Comment by sndurkin** [comment]
Sorry about that, I think I confused you by saying they have to be added on by www before the reply is sent to the client. That's one solution, but in this case we're not doing that because it will likely be too expensive for the server.

So, what we're doing instead is letting the client cache usernames by their id. When the client receives a set of comments for a proposal, each one will have a user id populated. It will check for usernames and populate them on the comments and re-render. For any usernames it doesn't have, it will fetch them from the server. So each request for a proposal detail will be followed by a request for usernames, but each of those requests will fetch fewer and fewer usernames as the user browses through proposals.

**Comment by xaur** [comment]
Makese sense, thanks for clarification.
