### ISSUE TITLE
Move usernames cache into store subscription

### ISSUE THREAD

**Issue by sndurkin** [decred/politeiagui#364]
> Use the store subscription (https://github.com/decred/politeiagui/blob/master/src/App.js#L18) to detect changes on unvetted/vetted response and caching the values there? So we can create a module like handleCacheUsernamesFromProposals. It would keep selectors cleaner.

> I would recommend you creating a module (such as lib/cache_usernames.js) the you can export the variable globalUsernamesById from there and all needed handlers functions. This way we keep all the related code to caching grouped together.

@fernandoabolafio

**Comment by rrecuero** [comment]
I could work on this @sndurkin. Any more details?

**Comment by sndurkin** [comment]
Actually you should ask @fernandoabolafio for more info, he suggested to do this.

**Comment by fernandoabolafio** [comment]
I've been thinking about this and I think it doesn't need to use store subscription. Instead, we could add handlers to the relevant actions (onFetchUnvetted, onFetchVetted, onFetchProposal) to cache the usernames using the redux store. 
My truly/only concern here is that now we use a global constant and execute the caching from the selectors which should be ideally pure functions. 

@rrecuero this is the code I am talking about:
https://github.com/decred/politeiagui/blob/master/src/selectors/app.js#L83

**Comment by fernandoabolafio** [comment]
moved to #677
