### ISSUE TITLE
Testing - next steps

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#376]
- Write unit testing for selectors and reducers
- Write component testing for key components to make sure they behave correctly.
 Examples of components to be tested are:
   - Header alert: make sure it will be rendered when either paywall is missing or/and the user needs to generate a new identity.
   - ThingLink: make sure it renders the correct content, given different situations (censored proposal, just created proposal, proposal on voting, proposal with finished voting, etc)
   - Buttons triggering key actions (submit proposal, submit comment, approve/censor proposal) make sure they are all blocked when there is a missing verification (paywall/identity).

**Comment by thi4go** [comment]
I can write some more tests, I'll work on this @fernandoabolafio 👍
