### ISSUE TITLE
Internal server error needs to be handled gracefully

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#379]
Steps to reproduce: 
 - Shut down `politeiawww`
 - Go to `https://localhost:3000` or wherever `politeiagui` is running on your machine
![screen shot 2018-06-19 at 12 21 11 pm](https://user-images.githubusercontent.com/14864439/41606950-45493b86-73bb-11e8-9c3a-7f31544e1fbc.png)

**Comment by rrecuero** [comment]
I'll grab this
