### ISSUE TITLE
Comment box & SAVE button not disabled on non-verified account.

### ISSUE THREAD

**Issue by gravityz3r0** [decred/politeiagui#383]
Step to reproduce:

1. Create a new politea account.
2. Do not verify your account. The following error pops up:
"Action Needed : You cannot currently submit proposals or comments, please visit your account page to correct this problem."
3. Open any proposal. Notice that the comment box is still active.
4. Enter any comment and click "SAVE". The click will be accepted, but no comment is actually posted (which worked as intended).

Suggestion : Greying out the whole comment box and/or "SAVE" button to prevent any input of comment to make the user experience more consistent.

**Comment by fernandoabolafio** [comment]
Thanks for reporting @gravityz3r0! However It was closed on https://github.com/decred/politeiagui/pull/382. We should have this update on the live website in the next few hours.
