### ISSUE TITLE
Censorship token should be clearly labelled

### ISSUE THREAD

**Issue by RichardRed0x** [decred/politeiagui#397]
It's not clear where to find the censorship token for a newly submitted proposal. I tried the token under the title in the token search but it said no proposal found (guessing there's a lag on that?). After inspecting th download it seems that string is my token after all. This should be clearly labelled for users.

**Comment by sndurkin** [comment]
There is no lag for the search, can you post which token it was?

**Comment by tiagoalvesdulce** [comment]
Closing this now that https://github.com/decred/politeiagui/pull/400 is in.
