### ISSUE TITLE
Hide "Payment received" message after navigating away from account page

### ISSUE THREAD

**Issue by sndurkin** [decred/politeiagui#399]
The "Payment received" message should be hidden after the user navigates away from the account page. Currently, it's persisted until the user refreshes the browser.

**Comment by rrecuero** [comment]
I'll grab this

**Comment by rrecuero** [comment]
@sndurkin Is this still happening? Can you give more details to repro it if so?. Looking at the code <Paywall> is only rendered in the account page. When I go to any other page it disappears for me.

**Comment by sndurkin** [comment]
@rrecuero yes, here are the steps to reproduce:

1. Create a new user, go to the account page and click "Pay with faucet".
2. Wait until you see the "Payment received" message.
3. Navigate to another page.
4. Navigate back to the account page.

Expected behavior: You should no longer see the "Payment received" message.
