### ISSUE TITLE
Yes/No and vote bar layout changes

### ISSUE THREAD

**Issue by sumiflow** [decred/politeiagui#413]
In the proposed layout below I swapped the order so that "Yes" comes before "No".  This makes more sense to me since I imagine the green area filling up the darker area from left to right.  Also modified smaller shaded bar area sizes to be more representative of their actual %.  Feel free to disagree.

![pi](https://user-images.githubusercontent.com/5420838/42205235-7893212e-7e69-11e8-810f-59e69cf1ddfa.jpg)

**Comment by marcopeereboom** [comment]
We really want this @fernandoabolafio

**Comment by fernandoabolafio** [comment]
Thanks for the suggestions @sumiflow. I will change that.
