### ISSUE TITLE
[ux/ui] Add option to draft proposal

### ISSUE THREAD

**Issue by marcopeereboom** [decred/politeiagui#420]
I really think one needs to be able to draft a proposal without risking losing work. Step one is to be able to somehow save a draft in the GUI. Secondly, I think we may need to do some sort of "autosave" every minute or so.

This information should be saved locally in order to not leak information.

**Comment by tiagoalvesdulce** [comment]
We are kind of doing it already. Right now we save proposal content on `sessionStorage`, a simple solution would be saving it on `localStorage` instead. The downside is that the user won't be able to save multiple drafts.

**Comment by rrecuero** [comment]
I could work on this if that is fine with you @tiagoalvesdulce

**Comment by tiagoalvesdulce** [comment]
Sorry for the late reply @rrecuero I didn't receive a notification from github, ping me on Slack in the future, it's easier to find me there 😄 Feel free to work on this. I was discussing it with @sndurkin and I think we should add a button to the `proposals/new` page to save the proposal on drafts and show those drafts in the My Proposals list route with a good distinction between proposals and drafts.

**Comment by sndurkin** [comment]
@rrecuero, here's a detailed writeup of what @tiagoalvesdulce and I came up with. This is going to be a somewhat big PR.

Submit Proposal page:

* Shorten the width of the Submit button to something reasonable and left-align it
* Add another button to the right of the Submit button called "Save as draft"
* When "Save as draft" is clicked, it will save the existing title, description and files in localStorage with a unique id and the current date as the "date saved"
* The existing autosave feature will be preserved, with the proposal data getting saved in sessionStorage if the user hasn't already saved it as a draft or submitted it

User Proposals page:

* Display 2 radio options: "Submitted" and "Drafts"
* When "Submitted" is selected, display all the proposals sent by the server (as they are currently)
* When "Drafts" is selected, display a list of drafts from localStorage, each of which has a title and a "date saved", ordered by date saved descending
* Clicking one of the draft titles opens the Submit Proposal page with the title, description and files pre-populated

**Comment by rrecuero** [comment]
thank you @sndurkin @tiagoalvesdulce. I'll work on it this weekend and send a PR.

Thanks for the details
