### ISSUE TITLE
Forbidden when signing up

### ISSUE THREAD

**Issue by Erovyr101** [decred/politeiagui#434]
I get a forbidden error when signing up as soon as I submit the information. (I also get that error for "resend verification" and "reset password") This could be caused by a past account for test proposals for which registration never fully completed. 

But if it's an old account I don't believe the system should give that kind of error because it could leak information about my email address being used for an account already.

Other informations: I tried mutiples usernames and passwords to be sure it wasn't content related.

![image](https://user-images.githubusercontent.com/17142561/42611378-d01ba41a-8563-11e8-9208-1c5101a9e29c.png)

**Comment by vctt94** [comment]
Which browser is that? Can you try erasing your cookies and see if it works?

**Comment by Erovyr101** [comment]
Firefox 61.0.1 (64-bit)
Removing cookies has no effect
Tried disabling AV just in case it was a random blocked resource or script, no effect either.

**Comment by vctt94** [comment]
Can you hit f12 and see what do you have at Storage-> Cookies?

![example](https://user-images.githubusercontent.com/15069783/42631692-55829a76-85b1-11e8-9fa8-450d65deb523.png)

**Comment by Erovyr101** [comment]
I get the same issue with chrome  67.0.3396.99
The only thing I haven't tried is a different email address

![image](https://user-images.githubusercontent.com/17142561/42631876-75f9f702-85a9-11e8-870b-7177172a5879.png)

**Comment by vctt94** [comment]
Try deleting the cookies from this tab, right click the URL and hit `Delete All`. Then hit f5 and see if it generates again these cookies.

The problem is not with your email, it is generating two `_gorilla_csrf` cookies, which is messing the requests. 

If it generates these two cookies again, then it is buggy

**Comment by Erovyr101** [comment]
Yes,  that's what I did previously,  it does regenerates both cookies,  I also have the same behavior in chrome:

![image](https://user-images.githubusercontent.com/17142561/42632415-1816fd5e-85ab-11e8-9706-d504cdbf0152.png)

**Comment by Erovyr101** [comment]
If I delete only the /api/v1  one,  it doesn't come back after a reload.  If I delete both or the /api one,  they both come back

**Comment by vctt94** [comment]
Can you go to the network tab now, at the beginning of politeia `https://proposals.decred.org/`, hit f5 and see what requests are being made?

![example](https://user-images.githubusercontent.com/15069783/42632840-e9f311ec-85b4-11e8-8ff4-d4f130440871.png)

**Comment by Erovyr101** [comment]
Oh ..  if I delete the cookies and go to https://proposals.decred.org/  only the /api cookie gets created. It would appear,   the issue only occurs when  you use the signup url directly

![image](https://user-images.githubusercontent.com/17142561/42633043-37c1c2e0-85ad-11e8-87e4-d37f0e310216.png)
![image](https://user-images.githubusercontent.com/17142561/42633124-7ba0aae4-85ad-11e8-8ab4-f059b0c0d23b.png)

**Comment by vctt94** [comment]
Yeah, it is true. Now I can reproduce that bug. Thanks for your help @Erovyr101

**Comment by Erovyr101** [comment]
No problem !  I was able to register with the single cookie.
