### ISSUE TITLE
improve no-js landing page

### ISSUE THREAD

**Issue by behindtext** [decred/politeiagui#435]
the existing landing page that says you need to enable js is pretty rough. tune this up so it looks better and is more easily read.

**Comment by tiagoalvesdulce** [comment]
<img width="1040" alt="screen shot 2018-07-12 at 13 07 49" src="https://user-images.githubusercontent.com/13955303/42645531-a9e49dee-85d4-11e8-961b-3067f2fc1d80.png">
Is it OK?

**Comment by behindtext** [comment]
looks a lot better
