### ISSUE TITLE
create new account: "before you signup" modal

### ISSUE THREAD

**Issue by behindtext** [decred/politeiagui#436]
when creating a new account, you fill in all 4 fields and then there is a "before you sign up" div with info about how pi accounts and the signup process works. this would look better in a modal, imo.

**Comment by sndurkin** [comment]
The only issue I see with displaying it in a modal is where do we display server errors? If we display them in the modal, it won't be consistent with displaying client-side validation errors. If we display them in the form, it's a little weird to draw the user's attention to a modal and then back to the form.

If we stick with this concept where the identity is tied to a single browser, what we really need is a video that we force users to watch before signing up which explains how it works. This would eliminate the need to explain the identity concept in multiple places in the app, such as this "before you signup" info box.

**Comment by justinsantoro** [comment]
I can get this video done if needed. If someone creates an issue [here](https://github.com/raedahgroup/video-production/issues) and provides an outline of how it should be explained, I can quickly write up a script and push it to the front of the production line.

**Comment by marcopeereboom** [comment]
This has been addressed.
