### ISSUE TITLE
Hash user's password before sending to server

### ISSUE THREAD

**Issue by sndurkin** [decred/politeiagui#443]
We should hash the user's password during signup/login/change password before sending it to the server:

*  https://www.npmjs.com/package/bcrypt
* use technique 2

**Comment by rrecuero** [comment]
I can take this too

**Comment by rrecuero** [comment]
I'll work on this one as well

**Comment by rrecuero** [comment]
I have been working on this one but I think this is much better done server side. To use the compare functionality from bcrypt on the frontend we would need to return the hashed password to the client.

Thoughts @sndurkin?

**Comment by rrecuero** [comment]
Probably better that someone else takes this

**Comment by marcopeereboom** [comment]
In debug mode, we dump HTTP traffic so we will log passwords. This is simply unacceptable. 

The options we have are:

1. Scrub passwords from logs
2. Hash the password before transmission

I have looked at this and there are not many palatable options. 

Option 1 Is very error prone and is therefore right out the window. Option 2. Is essentially the same as a cleartext passwords but at least admins can't read it. I, therefore, suggest we go with option 2. How about SHA3 as the hashing algorithm?

This can be implemented in the GUI independently from the CLI tools so we should go ahead and do it.

**Comment by fernandoabolafio** [comment]
I will work on it. The lib suggested by @sndurkin can handle this job. I will take a carefull look on what algorithm it uses for Hashim tho.

**Comment by lukebp** [comment]
@fernandoabolafio here's the go snippet I used in the CLI if you want to verify the output.

```
// digest returns the hex encoded SHA3-256 of a string.
func digest(s string) string {
	h := sha3.New256()
	h.Write([]byte(s))
	return hex.EncodeToString(h.Sum(nil))
}


fmt.Println(digest("password"))
// c0067d4af4e87f00dbac63b6156828237059172d1bbeac67427345d6a9fda484
```
