### ISSUE TITLE
Layout broken on signup

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#450]
Accessing the singup route directly causes the layout to broke:
https://proposals.decred.org/user/signup
![screen shot 2018-07-13 at 10 48 00 am](https://user-images.githubusercontent.com/14864439/42694953-5e2a0b26-868a-11e8-91d2-2a8d29621abc.png)

**Comment by thi4go** [comment]
I'll fix this !

**Comment by tiagoalvesdulce** [comment]
Oh, sorry @thi4go, I didn't see it before opening #451. It was kind of related to my yesterday's PR and I knew what to change in order to fix it.

**Comment by thi4go** [comment]
No problem ! Nice that it's fixed already  :)
