### ISSUE TITLE
Superscript doesn't seem to work

### ISSUE THREAD

**Issue by jholdstock** [decred/politeiagui#453]
I copied the example of superscript from the "formatting help" link. It did not work as expected - see attached screenshot:

![whut](https://user-images.githubusercontent.com/6762864/42700980-3a436a58-86bd-11e8-831d-2c67b452206f.png)

**Comment by fernandoabolafio** [comment]
Thanks for reporting it @jholdstock! This superscript instruction will be removed from the "formatting help" since our current markdown implementation doesn't support that.
