### ISSUE TITLE
Comment Editor content overlapping

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#456]
The editor's header is collapsing when the parent width is too small:
![screen shot 2018-07-14 at 12 23 06 pm](https://user-images.githubusercontent.com/14864439/42725825-d086a676-8760-11e8-9c8b-a3154d797bb4.png)

**update:** screen sizes affected are smaller than 1024x768

**Comment by rrecuero** [comment]
I'll take this
