### ISSUE TITLE
[Paywall] Paywall keeps updating after user logout

### ISSUE THREAD

**Issue by vctt94** [decred/politeiagui#458]
Steps to reproduce

- Login with a new user that has not paid the paywall
- Pay the paywall with faucet
- Logout - on this point `UPDATE_USER_PAYWALL_STATUS` will still happen and it should not.

**Comment by rrecuero** [comment]
I think my fix for https://github.com/decred/politeiagui/issues/399 may fix this one as well

**Comment by sndurkin** [comment]
@vctt94 can you retest against master now that #399 has been merged?

**Comment by thi4go** [comment]
Hey @sndurkin, just tested it and the bug persists. I'll be working on this issue.

**Comment by sndurkin** [comment]
Sounds good @thi4go, thanks.

**Comment by sndurkin** [comment]
Closing as paywall is about to be removed in favor of the notification system.
