### ISSUE TITLE
Submitting proposal with jpg attached doesn't show error

### ISSUE THREAD

**Issue by sndurkin** [decred/politeiagui#472]
Steps to reproduce:

1. Go to the Submit Proposal page.

2. Populate the name and description.

3. Attach a jpg image, like this:

   ![1](https://user-images.githubusercontent.com/1452379/42983224-8999d952-8bb3-11e8-8829-ec67506eb3ae.jpg)

4. Click the Submit button.

Expected: Instead of attaching the image, an error should be displayed because it's not a supported mime type.
Actual: Submit button gets disabled, but there's no error. Submit button is re-enabled after removing attachment.

**Comment by thi4go** [comment]
I'll try to fix this one.

@sndurkin , valid image formats are .png only?

**Comment by sndurkin** [comment]
@thi4go valid formats are sent via the `/v1/policy` call. There are currently only about 4 valid formats. I don't know why jpg isn't one of them yet, I'm sure it will be added in the future.

**Comment by thi4go** [comment]
Thanks @sndurkin !
