### ISSUE TITLE
Hovering over the proposal relative date should show the absolute date

### ISSUE THREAD

**Issue by sndurkin** [decred/politeiagui#492]
Hovering over this relative date under each proposal should show the absolute date in a tooltip or something, so the user can see when exactly it was submitted:

![image](https://user-images.githubusercontent.com/1452379/43468410-e19323a0-94b1-11e8-9ab5-8a0552508939.png)

**Comment by tiagoalvesdulce** [comment]
Should be done for notifications as well.
