### ISSUE TITLE
Unable to Upload SVG files for proposals.

### ISSUE THREAD

**Issue by degeri** [decred/politeiagui#500]
How to replicate the issue.
1. Login as any user to polieria and get proposal credits
2. Go to "https://test-proposals.decred.org/proposals/new" .
3. Try to select any SVG file and hit "submit" its giving the error:
"The MIME type detected for example.svg did not match the provided MIME type. MIME type: text/xml; charset=utf-8"

![svg](https://user-images.githubusercontent.com/41839293/43686275-4a5b626c-98e0-11e8-892d-82be2554e985.png)

**Comment by tiagoalvesdulce** [comment]
@sndurkin @marcopeereboom I think there was a discussion on Slack about supporting SVG files some months ago. What was decided?
