### ISSUE TITLE
Form content backup for editing proposals and comments

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#547]
Right now only the content for new proposals is being saved in the session storage so if the user navigates away from the "New Proposal route", the content he has typed so far will be preserved.

We also need to add this functionality for:
1  - Editing a submitted proposals
2 - Editing a draft proposal
3 - Comments

Regarding 1 and 2, I think would be nice to have an option "reset changes" which remove the changes which are only stored in the session storage but aren't saved yet. (By saved I mean: saved as a draft or as a submitted proposal)

**Comment by marcopeereboom** [comment]
Things have changed significantly and I think this has been addressed. Create new issue if that is not the case.
