### ISSUE TITLE
Create visual separation for proposals

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#553]
Proposals are currently all "glued" together inside the same parent visual component, they should be decoupled individually inside its own visual container. 

**Note:** It may need some tweaks on the snew-classic-ui repository.

I managed to provide a visual preview of how it should be:

**Current UI:**
![screen shot 2018-09-04 at 3 29 24 pm](https://user-images.githubusercontent.com/14864439/45050332-62247580-b057-11e8-906a-d68aa4d8910e.png)

**Wanted UI:**
![screen shot 2018-09-04 at 3 28 56 pm](https://user-images.githubusercontent.com/14864439/45050349-6ea8ce00-b057-11e8-989d-97ecbc4117e6.png)

**Comment by marcopeereboom** [comment]
I like it
