### ISSUE TITLE
Usernames turns to ID on comments 

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#561]
- Go to a proposal page
- Scroll to comments and vote up/down on some comment
- Refresh the page
- Scroll to comments, you should see the user id instead of the username
- Vote up/down on one of those comments: the username shows up again

![sep-05-2018 11-56-19](https://user-images.githubusercontent.com/14864439/45101968-0283a400-b103-11e8-9508-1504ab095194.gif)

**Comment by thi4go** [comment]
Hey @fernandoabolafio , I tried reproducing this error, but couldn't. Tested it in the default proposal with different comments/accounts and the bug didn't occur.

Am I missing some step to reproduce it correctly?

**Comment by tiagoalvesdulce** [comment]
Fixed on https://github.com/decred/politeiagui/pull/574
