### ISSUE TITLE
[voting] display voting stats

### ISSUE THREAD

**Issue by marcopeereboom** [decred/politeiagui#579]
We need to display vote stats in the gui when a vote is active. It'd be nice to show what block the vote ends and some sort of visual on how many days/hours (blocks?) are left in the vote.

**Comment by victorgcramos** [comment]
Working on this issue!

**Comment by marcopeereboom** [comment]
What is your slack handle?

**Comment by victorgcramos** [comment]
victorguedes

**Comment by victorgcramos** [comment]
#592 #
