### ISSUE TITLE
proposal credits: auto-update status

### ISSUE THREAD

**Issue by behindtext** [decred/politeiagui#586]
the registration paywall works nicely in that it updates the status of the payment over time, but the proposal credit payment div does not. you have to manually hit the refresh button versus it episodically polling for payment status in the background.

updates to the payment status should be automated and poll episodically in the background, e.g. every 60 seconds. it should show 0, 1 and 2 confirmations, as the notifications arrive.

**Comment by thi4go** [comment]
Finishing this up !
