### ISSUE TITLE
Improve visual identity

### ISSUE THREAD

**Issue by tiagoalvesdulce** [decred/politeiagui#593]
@saender has made a pretty good job putting together some [logo/symbols assets of politeia](https://github.com/decred/dcrdesign/issues/40). We should adapt pgui to match his design requirements (update the colors, logos, etc). It also includes updating our current loading component. Decrediton is currently using [this gif](https://github.com/decred/decrediton/blob/master/app/style/icons/politeia-loading.gif) and we should use it as well.

**Comment by camus-code** [comment]
Working on this now
