### ISSUE TITLE
Replace buttons loading icon

### ISSUE THREAD

**Issue by tiagoalvesdulce** [decred/politeiagui#599]
Replace the loading icon on buttons as soon as we get a negative version of [politeia loading gif](https://github.com/decred/politeiagui/blob/master/src/style/politeia-loading.gif).

**Comment by kyleFirethought** [comment]
👍

**Comment by kyleFirethought** [comment]
![politeia_inv](https://user-images.githubusercontent.com/7825971/45645715-425e6a00-bab9-11e8-80e8-1e684f27f59f.gif)
![politeia_sprite](https://user-images.githubusercontent.com/7825971/45645716-42f70080-bab9-11e8-8784-b812426b9d30.gif)
How are these for size? let me know of any changes you require?

**Comment by tiagoalvesdulce** [comment]
Looks good @kyleFirethought, thank you! @victorgcramos will be working on this issue and will let you know if he needs anything else.

**Comment by kyleFirethought** [comment]
No worries, keep me posted. 👍

**Comment by kyleFirethought** [comment]
@victorgcramos 

![politeia_inv_256](https://user-images.githubusercontent.com/7825971/45948515-39f1bc00-bff0-11e8-98ae-c3650d9238ae.gif)
![politeia_60](https://user-images.githubusercontent.com/7825971/45948517-3a8a5280-bff0-11e8-9c2f-523c1bde99b8.gif)
![politeia_256](https://user-images.githubusercontent.com/7825971/45948518-3a8a5280-bff0-11e8-8c9e-4fc42a924243.gif)
![politeia_inv_60](https://user-images.githubusercontent.com/7825971/45948519-3a8a5280-bff0-11e8-9a7e-5df8965516fd.gif)

60x60 is the decrediton standard and pretty safe when it comes to anti-aliasing.  at 20x20 things fall apart (slightly) 

Let me know if these fit the bill? 

- Kyle

**Comment by kyleFirethought** [comment]
Also @victorgcramos @tiagoalvesdulce poke your head around here: https://github.com/decred/dcrdesign/issues/35

Certainly a few icons (pending_review) for use in the Pi GUI.  Ie: Proposal, Checkmark, User Profile, ect.

**Comment by victorgcramos** [comment]
Nice! I'll check that out! Thanks!
