### ISSUE TITLE
Improve onboarding flow

### ISSUE THREAD

**Issue by tiagoalvesdulce** [decred/politeiagui#607]
We want to show the user a "Welcome! Not sure what Politeia is? Want to read more about it?" message (or something like this) and two options "Sure, show me more" and "No, I know how Politeia works" and then follow to the onboarding text. This can be implemented as a "first step" in the onboarding modal to make the implementation easier. We should also reword the "Read more" link in the sidebar that opens the onboarding modal to something like "Open onboarding modal to read more" or something similar. Note that when clicking on this link in the sidebar, the "first step" saying Welcome ... should not be presented.

**Comment by camus-code** [comment]
Working on this now

**Comment by s-ben** [comment]
Proposed copy:

"Politeia will send you a link to verify your email address. **You must open this link in the same browser.** After verifying your email, Politeia will create your Politeia “identity”, which consists of a public/private cryptographic key pair and browser cookie. This is necessary to verify your identity and allow submission of proposals, commenting, voting, and other Politeia functions. After completing the signup process, you can export your identity (public/private keys) to another browser at any time."
