### ISSUE TITLE
Spacing issue on "Before you sign up..." info box (Chrome)

### ISSUE THREAD

**Issue by s-ben** [decred/politeiagui#612]
There is no margin on the right side of the "Before you sign up..." info box that shows after you create a new account.

https://localhost:3000/user/signup

Chrome (the browser that my localhost automatically starts up, even if I'm using another browser (Brave))
![image](https://user-images.githubusercontent.com/1634777/45786468-68088200-bc25-11e8-9a81-c68772425c24.png)

The spacing does appear to look OK in Firefox, though left-indenting generally looks weird IMHO.

Firefox
![image](https://user-images.githubusercontent.com/1634777/45786577-f0872280-bc25-11e8-8806-6e6fe99cefd3.png)

**Comment by tiagoalvesdulce** [comment]
@s-ben you are in an out-dated politeiagui version. Can you verify if it happens in the up-to-date pgui as well?

**Comment by s-ben** [comment]
@tiagoalvesdulce , I believe (though not 100% sure) that I'm using the latest version. Just tried it again and I appeared fine, until I resized the screen and made it smaller. Then I'm seeing what looks like a problem with text wrapping, or some CSS issue. Do you get this when you narrow the screen size?

![image](https://user-images.githubusercontent.com/1634777/45792481-b8420d00-bc42-11e8-85f2-03c49824601c.png)

**Comment by s-ben** [comment]
Yeah, I presume most people will be looking at Politeia with screens not resized down.

**Comment by camus-code** [comment]
Working on this!
