### ISSUE TITLE
Opening "manage credits" modal before paying registration leads to an error

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#616]
The endpoint `/api/v1/proposals/paywall` requires the user to have paid the registration paywall. We should not be hitting this endpoint before the paywall confirmation.

See the error below:
<img width="777" alt="screen shot 2018-09-21 at 10 01 33 am" src="https://user-images.githubusercontent.com/14864439/45882853-c77da380-bd85-11e8-9b11-dcc2682c428b.png">

**Comment by camus-code** [comment]
Working on this now
