### ISSUE TITLE
[proposal credits] Proposal Credits modal needs to open smoothier

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#618]
When you open the "manage credits" modal, it opens in an "abrupt" way. We need to make it smoother 
by adding a loading indicator while the content is still loading.

![sep-21-2018 14-34-38](https://user-images.githubusercontent.com/14864439/45896944-13434380-bdac-11e8-9f5d-2b3f991d9642.gif)

**Comment by camus-code** [comment]
I'll work on this!

**Comment by fernandoabolafio** [comment]
updated and better described on https://github.com/decred/politeiagui/issues/921
