### ISSUE TITLE
[logout] Add visual indicator that session has ended

### ISSUE THREAD

**Issue by marcopeereboom** [decred/politeiagui#623]
After a session expires the GUI does not provide feedback and it only becomes obvious after reloading the site. We need some sort of indicator that the session is about to expire or has expired.

**Comment by fernandoabolafio** [comment]
The session cookie is `httpOnly` for security reasons. The GUI code cannot access its values thus its impossible to indicate what if the session has expired or is about to expire. I suggest we add the session expiration time within the user's info in the route `api/v1/users/me`.
