### ISSUE TITLE
Malformed links redirecting to proposals/:id page

### ISSUE THREAD

**Issue by tiagoalvesdulce** [decred/politeiagui#633]
Links without `http://` or `https://` are being treated as a politeiagui route.

Go to https://test-proposals.decred.org/proposals/0873814acca0322986c94dd7408c54dbab17815bbed64b938780514a811ee2f9 and click the first comment to reproduce.

**Comment by victorgcramos** [comment]
Worked on that and fixed. Check it out! 😁
