### ISSUE TITLE
[Proposal Credits] Explicit display what the purchase status is

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#646]
Instead of displaying a loading spinner for unconfirmed transactions or a check for the confirmed ones, I think it would be better to explicit show what the status is. Spinners usually indicate that there is an ongoing request waiting for the reply.
Maybe also consider displaying the confirmations number (e.g.: 2/3)

**Example:**
![screen shot 2018-10-02 at 9 08 39 am](https://user-images.githubusercontent.com/14864439/46347871-6f675c80-c623-11e8-9e94-e516a190ea93.png)

**Comment by camus-code** [comment]
Working on this now
