### ISSUE TITLE
Malformed links still working on right click and External Link warning bypass

### ISSUE THREAD

**Issue by degeri** [decred/politeiagui#654]
So https://github.com/decred/politeiagui/pull/642 works perfectly when the user gives a "left mouse" click. 

But the URL still seems to point to "/proposals/[inputtext]"  and if a user gives a "right click" and open new tab then it still takes them to the problem URL. 

To reproduce go to URL:
https://test-proposals.decred.org/proposals/45316e5425a426a9a25f4145db92239029d446051dceae3d5ccac8bee1612519

1.

RIGHT click on my comment "test" and open in new tab the URL "https://test-proposals.decred.org/proposals/propppp" 
2.
This might also be a way around the "External Link Warning" that we implemented.  (though we hope anyone right clicking on a link and opening it is smart enough to understand what they are doing)
3.
Also if we create a link with the following code 

POC1:
\![clickmenowarning]\(htt://google.com) 
POC2:
\![ClickMeNoWarning2]\(f:ggggrr) 
POC3:
\![ClickMeNoWarning3]\(bitcoin:notanaddress)  --> this would openup in some clients. 

and give a normal left click it seems to bypass the "Warning message" and directly takes the user to the link

For a permanent fix I would suggest that the URL be "FORMED" only when the user loads the "Modal" object. Thus preventing this issue all together. 

![image](https://user-images.githubusercontent.com/41839293/46485013-815e2080-c818-11e8-8282-6451846bd035.png)

**Comment by tiagoalvesdulce** [comment]
@victorgcramos you might want to solve this in your next PR as well.

**Comment by victorgcramos** [comment]
Sure!

**Comment by victorgcramos** [comment]
Fixed! Please check it out!
