### ISSUE TITLE
[Mainnet] Not giving feedback on the purchase of proposal credits

### ISSUE THREAD

**Issue by tiagoalvesdulce** [decred/politeiagui#658]
It works nice on testnet, but in mainnet nothing happens when the DCR is sent to the address provided.

**Comment by marcopeereboom** [comment]
This needs to have a visual for the user. People will freak out if there is no feedback.

**Comment by marcopeereboom** [comment]
I also noted that after the credit became available that the counter did not auto update. I had to refresh the website to see my credit. This must be fixed as well.
