### ISSUE TITLE
Userid on comment's author

### ISSUE THREAD

**Issue by tiagoalvesdulce** [decred/politeiagui#665]
<img width="530" alt="screen shot 2018-10-08 at 10 37 35" src="https://user-images.githubusercontent.com/13955303/46612644-873d5580-cae7-11e8-8766-d89a08b31b22.png">

To reproduce:
Login as admin > submit a proposal > approve it (you will be redirected to its route) > comment on it.

**Comment by camus-code** [comment]
Working on it

**Comment by tiagoalvesdulce** [comment]
Closing because it will be solved on https://github.com/decred/politeia/issues/514

**Comment by tiagoalvesdulce** [comment]
Reopening, it should be fixed on the GUI.
