### ISSUE TITLE
[UI/UX] Make modal transitions smoother

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#687]
The modal transitions (open/close) needs to be smoother to provide a better UX.
In this [link](https://tympanus.net/Development/ModalWindowEffects/) there are a few examples of nice and smoother trasitions.

**Comment by camus-code** [comment]
Picking this one up

**Comment by camus-code** [comment]
Not working on this anymore. Free for anyone else to pick up

**Comment by fernandoabolafio** [comment]
Done on https://github.com/tiagoalvesdulce/pi-ui. The replacement of components has already started for politeiagui v2.
