### ISSUE TITLE
Improve instructions for how a user can demonstrate censorship of their proposal

### ISSUE THREAD

**Issue by RichardRed0x** [decred/politeiagui#688]
We should have a page somewhere that walks through this step by step, including steps like downloading the proposal bundle and how to demonstrate to others that a proposal was submitted.

**Comment by RichardRed0x** [comment]
Making a comment on the PR, but I don't think this should be closed yet.

**Comment by xaur** [comment]
How about a page on dcrdocs instead? (And generally moving all Pi docs from politeiagui to dcrdocs as suggested in #947)

**Comment by xaur** [comment]
Opened an issue in dcrdocs: https://github.com/decred/dcrdocs/issues/847

**Comment by marcopeereboom** [comment]
Seems fixed in doco.
