### ISSUE TITLE
Long link messes up with external domain warning modal

### ISSUE THREAD

**Issue by tiagoalvesdulce** [decred/politeiagui#695]
To reproduce it, create a comment with:

![Something][test]
[test]: https://www.google.com.br/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=&url=https%3A%2F%2Fwww.foxsports.com.br%2Fblogs%2Fview%2F380912-uribe-faz-dois-flamengo-aplica-3-a-0-no-fluminense-e-encosta-no-palmeiras&psig=AOvVaw2zBCiphAYfWwv_GpxxptpL&ust=1539718845069065

**Comment by victorgcramos** [comment]
Let me take that!
