### ISSUE TITLE
[UI/UX] Allow paste for identity import

### ISSUE THREAD

**Issue by davecgh** [decred/politeiagui#698]
The only way to import an identity currently is by importing a file.  Ideally, the dialog would allow you to directly paste the identity as an alternative to requiring a file.

This is desirable because many security conscious users have specialized tools dedicated to storing this type of information encrypted, and, thus, it would be ideal to allow the user to paste it directly instead of first having to create a file to upload.

**Comment by camus-code** [comment]
I'll pick this one up
