### ISSUE TITLE
Account page link doesn't provide the user with more info

### ISSUE THREAD

**Issue by sndurkin** [decred/politeiagui#710]
Before the user has finished registering, the Submit page shows this error:

![image](https://user-images.githubusercontent.com/1452379/47018377-9db86200-d122-11e8-88de-5a3ae68a25aa.png)

This is a confusing message, because clicking on the link to open the Account Page doesn't provide a way to buy proposal credits because I haven't paid the registration fee yet.

**Comment by tiagoalvesdulce** [comment]
This route should be blocked if the registration fee is not paid and the "Submit Proposal" on the sidebar should be disabled.

I think the message should be rephrased to: `To submit a proposal, you must purchase a proposal credit, click here to access the proposal credits manager`, where `click here` opens the proposal credits manager modal.
