### ISSUE TITLE
Proposal guidelines should be easily accessible from the Submit page

### ISSUE THREAD

**Issue by sndurkin** [decred/politeiagui#711]
I see that there are proposal guidelines on the introduction modal, which is accessible from the "Learn more about Politeia" link. But those guidelines would be better if they were accessible directly from the Submit page.

**Comment by camus-code** [comment]
Mistakenly referenced this issue in my last PR. Picking up this one now though

**Comment by camus-code** [comment]
Actually #726 will indeed close this. Just reissued my PR
