### ISSUE TITLE
User registration payment not showing in payment history.

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#716]
A user registration payment will not appear in the payment history even after it has received the required number of confirmations.  A refresh fixes it.

<img width="777" alt="screen shot 2018-10-16 at 8 53 08 am" src="https://user-images.githubusercontent.com/9039877/47028924-5f2da200-d138-11e8-8dcb-ad4ad402c8b5.png">

**Comment by thi4go** [comment]
I'll get this one as well

**Comment by thi4go** [comment]
Hey @lukebp @fernandoabolafio

How do you guys think the register fee payment data should look on our table? cause currently it stands as:

![image](https://user-images.githubusercontent.com/2729122/47054977-68942a00-d18b-11e8-8a58-750ed6f18297.png)

so the "DCR per credit" column might be misleading. we can maybe change to "DCR amount", and on "#" we'd put something like "registration fee" or "paywall fee".

is that ok?

**Comment by fernandoabolafio** [comment]
hey @thi4go sorry for the delay on responding to you. Did you have any progress on it? I think we can have the following columns set:

| type | amount (DCR) | credit or fee price (DCR) | transaction | status | Date |
| - | - | - | - | - | - | 
| credits | 0.2 | 0.1 |  xyzxyzxyz | confirmed | 12/05/18 |
| registration fee | 0.1  |  0.1 | xfaxfaxfa | confirmed | 11/05/18 |

How do you like it?
