### ISSUE TITLE
Finished Voting proposal tab is paginating even with low proposal count

### ISSUE THREAD

**Issue by thi4go** [decred/politeiagui#718]
![image](https://user-images.githubusercontent.com/2729122/47031155-b1c18b00-d145-11e8-952e-65799a5e283b.png)

As the title says, the Load More button is being prompt even with a low proposal count. In the image case, there's 4 finished proposals, and instead of showing them, we are paginating.

**Comment by victorgcramos** [comment]
Let me take this one!

**Comment by victorgcramos** [comment]
Hi, I couldn't replicate this error. Can someone check this?

**Comment by thi4go** [comment]
@victorgcramos thanks!!

Appears that this is happening only locally on my env. Will try to reproduce it again in another env and see the steps to it.

**Comment by tiagoalvesdulce** [comment]
@thi4go is this still happening?

**Comment by thi4go** [comment]
I really don't know if it's just here, but ive rebuilt everything and it's still happening against master. Now I have 5 finished voting proposals, it shows 1 properly and paginates the remaining 4 in the Load more button.

Can you check if you are getting this error, @tiagoalvesdulce ?

**Comment by tiagoalvesdulce** [comment]
I know what's happening. You probably have more than 20 proposals loaded in other tabs. The pagination is done in all proposals disregarding their status. I agree it is weird but is the expected behavior by now. We're planning to improve it in the future.
