### ISSUE TITLE
Add GitHub link on /proposals/ page.

### ISSUE THREAD

**Issue by dajohi** [decred/politeiagui#719]
A link to the GitHub repo on the /proposals/ page may be handy.

- Use target=_blank and rel="noopener noreferrer"
- Make sure people know it what they are clicking before they click.

https://github.com/decred-proposals/mainnet/tree/master/%s/1
https://github.com/decred-proposals/testnet3/tree/master/%s/1

**Comment by victorgcramos** [comment]
I can take a look at this!
