### ISSUE TITLE
Sometimes UUIDs are shown instead of usernames

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#723]
Proposal: https://proposals.decred.org/proposals/c68bb790ba0843980bb9695de4628995e75e0d1f36c992951db49eca7b3b4bcd

I'm not logged in, local storage is disabled, seeing this:

![guids-not-usernames](https://user-images.githubusercontent.com/24484727/47049509-0e946400-d18d-11e8-8a8a-b992efdec09a.png)

If I then click that UUID I see the username: https://proposals.decred.org/user/88e2567c-dc60-45f8-953d-e13885ad9a73

**Comment by fernandoabolafio** [comment]
thanks for reporting @xaur! I am not able to reproduce it, neither on proposals.decred.org or on my local setup. Are you able to reproduce it every time access that route or it happened just once?

**Comment by xaur** [comment]
@fernandoabolafio every time. Using an older ESR Firefox. Any logs I can provide?

**Comment by fernandoabolafio** [comment]
@xaur would be nice if you could provide a screenshot of your network console while you're loading the page. I want to figure if all the expected requests are being made.

**Comment by fernandoabolafio** [comment]
Just to register it from our slack discussion: the reason why this is happening is that the request to `/usernames` is failing due the fact cookies are disabled, hence CSRF is failing.
