### ISSUE TITLE
Feature request: Notifications

### ISSUE THREAD

**Issue by davecgh** [decred/politeiagui#728]
I would like to see the ability to opt in to various notifications.  Ones that come to mind:

- New proposals
- New vote starting
- Comments on your own proposals
- Replies to your own comments

**Comment by xaur** [comment]
* Comments on selected proposal ("Watch this prop" feature)
* New versions of a proposal

**Comment by xaur** [comment]
* Vote authorized by author
* Proposal expired

**Comment by marcopeereboom** [comment]
There is a slew of mail notifications that have been implemented. If we missed something please create a new issue with the missing bits.
