### ISSUE TITLE
Design and visual enhancement of proposals web portal.

### ISSUE THREAD

**Issue by denyszayets** [decred/politeiagui#729]
Are there any plans for enhancing/redesigning user interface for Politeia proposals? https://proposals.decred.org/

This doesn't have to be implemented immediately, but we can definitely start working on it. Current Politeia web page design is pretty much bare bones. Creating the same UI design as the new explorer, for example, would be beneficial to all users and Decred Project in general. @raedah and his team did great work in enhancing dcrdata design.

Thoughts? Thanks

**Comment by fernandoabolafio** [comment]
hey @denyszayets! The Pi website design indeed needs some love. However, we need ppl who have knowledge of design and can work close to developers. It may even be a topic for a PI proposal as it requires more contractors to come on board and participate in the website redesign.

**Comment by denyszayets** [comment]
Hi Fernando, that's what I've been doing since I joined Decred Team. @raedah and hist team worked with me on DCRDATA redesign for example.

**Comment by fernandoabolafio** [comment]
oh cool @denyszayets! Sorry my misinformation. I've not been following the other projects lately. I would love to have a designer working closer to Politeiagui.
Politeiagui has a huge dependency on the (snew-classic-u)i[(https://github.com/decred/snew-classic-ui) repo now; whichi is lib of components forked from the reddit old design. I see it as a good oportunity to redesign their components and create a new UI lib to integrate into PGUI later.

**Comment by denyszayets** [comment]
No worries, we grew fast! I'll open a group chat so we can talk.

**Comment by fernandoabolafio** [comment]
@tiagoalvesdulce may want to join this discussion too

**Comment by tiagoalvesdulce** [comment]
This discussion moved to https://github.com/decred/dcrdesign/issues/77
