### ISSUE TITLE
[UI/UX] Session expired dialog does not work properly

### ISSUE THREAD

**Issue by davecgh** [decred/politeiagui#730]
As can be seen in the following image, the dialog for session expired neither provides links for the text nor the username/password forms if the intention is for it to be inline.

![image](https://user-images.githubusercontent.com/2115102/47065640-51643500-d1a9-11e8-97d7-d6394ca8a666.png)

Also, I don't think there should not be a create account link when your session expired.  You already have one at that point.

**Comment by fernandoabolafio** [comment]
@davecgh what browser (and version) you saw that? 
I am not able to reproduce it on Chrome or Firefox.

**Comment by davecgh** [comment]
Firefox Quantum 62.0.3 64-bit

**Comment by RichardRed0x** [comment]
Happened to me too using Brave browser.
