### ISSUE TITLE
Feature Request: RSS feeds

### ISSUE THREAD

**Issue by jzbz** [decred/politeiagui#733]
Ideally Politeia would have RSS feeds for proposals, that way we could use the Matrix RSS bot to announce them on all our real time chat platforms.

**Comment by fernandoabolafio** [comment]
@jzbz I believe this issue is a duplicated of https://github.com/decred/politeiagui/issues/717. Hence I am closing it.

**Comment by fernandoabolafio** [comment]
I will actually keep this issue open and close the other one as I think it the issue is better described here.

**Comment by jzbz** [comment]
> What are the limitations of RSS to Matrix integration?

It's pretty basic, however if we fork the RSS bot we could make it fancier.

**Comment by xaur** [comment]
Watching a stream of props and comments in a Matrix room may greatly help Politeia admins.

**Comment by camus-code** [comment]
Though I believe it's possible to achieve this now, I think it's best we wait until #839 is resolved. Once we're able to generate server side HTML, implementing RSS feeds should be rather straightforward

**Comment by xaur** [comment]
I think you mean to wait for [839 in the politeia repo](https://github.com/decred/politeia/issues/839).

**Comment by camus-code** [comment]
thanks for the catch @xaur 

I've updated my original comment

**Comment by lukebp** [comment]
I've added this to the politeia feature request thread.  I support this feature request and will be including it in a future pi proposal.

https://github.com/decred/politeia/discussions/1502#discussioncomment-1312918
