### ISSUE TITLE
[UI/UX] The second tab get messed up on logout

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#746]
Steps to reproduce:

1- Login
2- Open two tabs on the Public Proposals page
3- Logout in the first tab
4- Go to the second tab, the public proposals are gone

I believe this is happening because we're clearing all the API cache on logout. If that's the case, we need to evaluate which chunks of data must persist after logout (e.g public proposals).

**Comment by camus-code** [comment]
Picking this one up
