### ISSUE TITLE
[UI/UX] Login via expiration modal results in no proposals

### ISSUE THREAD

**Issue by davecgh** [decred/politeiagui#756]
When logging back in via the expiration modal, the redirect shows 0 for all categories.  Refreshing the page manually resolves it.

**Comment by thi4go** [comment]
I'll work on this

**Comment by fernandoabolafio** [comment]
@thi4go, this seems to not be an issue since: https://github.com/decred/politeiagui/pull/742 was merged. I am closing it.

**Comment by davecgh** [comment]
This happened after that was merged.

**Comment by fernandoabolafio** [comment]
@davecgh  no code has been deployed into production since Pi release. So unless you're testing it locally you wouldn't see it reflected on your end.

**Comment by davecgh** [comment]
Hmmm ok.  Well I noticed that the expiration modal actually provided login information now, whereas, per my previous issues (#730 and #731), it was not doing so and was fixed by #742.

**Comment by fernandoabolafio** [comment]
Yeah, that behavior was inconsistent. You may be able to see or not the login form. 
It should all be okay in the next deployment though. Both of your issues are listed in the next PiGUI milestone. You can track what we're missing for the next deploy here:

https://github.com/decred/politeiagui/milestone/2
