### ISSUE TITLE
External link warning is difficult to read

### ISSUE THREAD

**Issue by sndurkin** [decred/politeiagui#770]
This is the current external link warning modal:

![image](https://user-images.githubusercontent.com/1452379/47337655-deeccc80-d662-11e8-990c-b08c8d7b8984.png)

I have a couple problems with it:

* It's difficult to read due to the center-aligned text. Left-aligned text is easier to read because every new line starts at the same place. In other words, the user's eyes don't have to jump to a different spot for every new line.

* The red text grabs the user's attention, but in a bad way because the text is meant to be read in context. For example, the words "do not" are highlighted in red but the user doesn't immediately know what not to do without reading the rest of the sentence, making the red text just distracting.

* The domain doesn't really need to be on a separate line as it's a subset of the full link; that section of link text could just be highlighted red.

Here is/was Facebook's external link warning, to show an alternative approach:

![image](https://user-images.githubusercontent.com/1452379/47337808-908bfd80-d663-11e8-892c-6090599018ff.png)

Some minor UX things to note in Facebook's example:

* A warning icon which experienced users can use to quickly identify the page they're looking at.
* A user-friendly warning message ("Please be careful"), in contrast to Politeia's "External Link Warning" title, which seems to just describe what it is.
* Buttons which use action verbs as text instead of Yes/No (more info: https://hackernoon.com/let-the-action-buttons-in-the-dialog-box-scream-its-outcome-b319c5efc698)

**Comment by sndurkin** [comment]
@degeri Yeah, I like the inline highlighting in that example.

**Comment by camus-code** [comment]
Working on this!
