### ISSUE TITLE
Privacy policy on separate page

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#771]
Separate page is the common practice I observe on the web. It makes the policy much more accessible (can be static page without js requirement). Should be linked from the footer.

**Comment by camus-code** [comment]
Not working on this anymore. Free for anyone else to pick up @xaur

**Comment by marcopeereboom** [comment]
@RichardRed0x can you write some copy for this?

**Comment by xaur** [comment]
Politeia admin knowledge is required, only admins know what user data is collected, how it is stored, processed, etc.

**Comment by marcopeereboom** [comment]
pubkeys, email, IP address and payment information is all that is silently recorded. Everything else lives in the backend that is there for all to see. One can easily set up a pseudo-anonymous account using tor that would hide more things. We will add email-less signups in the future.

**Comment by RichardRed0x** [comment]
Here's a small update to the current copy: 

> The proposals.decred.org database stores your account email address, user-name, cryptographic identity public key(s), IP addresses and payment transaction details - and associates this data with all of your proposals, comments and up/down votes. Your email address will be kept private and will not be shared with any third parties. In the interests of transparency, data associating your public key with content contributions will be published openly in the Decred-proposals [repository](https://github.com/decred-proposals/mainnet/).

Is there anything else it should cover?

**Comment by marcopeereboom** [comment]
I think this covers it all. Just need someone to wire it up.

**Comment by xaur** [comment]
@RichardRed0x looks right. Two nits: 1) "username", 2) I suggest to type out the address of decred-proposals repository instead of a link.

**Comment by marcopeereboom** [comment]
@camus-code can you wire this up?

**Comment by camus-code** [comment]
Yeah definitely @marcopeereboom. Finishing up my open PR’s / issues then I’ll wire this up.

**Comment by camus-code** [comment]
@RichardRed0x are you around? I'm wondering about the copy for the privacy policy when in CMS mode. Would you mind updating it for that as well whenever you get a chance?

**Comment by marcopeereboom** [comment]
Think it is about the same.

**Comment by camus-code** [comment]
Ok thanks @marcopeereboom. Just wanted to make sure there wasn't anything else we wanted to add

**Comment by RichardRed0x** [comment]
As @xaur pointed out user-name was wrong in the original copy. I'm not sure what is meant by " I suggest to type out the address of decred-proposals repository instead of a link".

**Comment by xaur** [comment]
@RichardRed0x I mean to use

```
... will be published openly in the Decred-proposals repository: https://github.com/decred-proposals/mainnet
```

instead of

```
... will be published openly in the Decred-proposals [repository](https://github.com/decred-proposals/mainnet).
```

Minor issue though.
