### ISSUE TITLE
Make header scrollable

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#773]
I just realized on GitHub and Reddit the header is scrollable. It makes a lot of sense since I don't really need the header all the time, but I need the space to read text.

**Comment by fernandoabolafio** [comment]
In order to make the header scrollable, the website navigation needs to be taken into consideration. For instance, If a user is going through a long list of comments, he needs a way to scroll all the way up.

**Comment by xaur** [comment]
Desktop users have Home button for decades, I see all modern trends to reduce view port as harmful. Same for obstructing the view port with "Jump to top" buttons -- I never use them.

The optimization for the "scroll up" use case, which not everybody needs, comes at the cost of hurting the "reading comments" use case, which everybody needs.
