### ISSUE TITLE
Populate footer

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#774]
Empty footer looks weird. Some candidate links to be included in the footer:

* About
* Terms of Service
* Privacy Policy
* GitHub source code (politeia, politeiagui)
* Report a bug (link to github issues)
* Git tag or revision that is currently deployed
  * this is convenient for testing but has a possible security risk, needs discussion
* Link to #proposals chat room
* Link to r/decred
* Link to decred.org

**Comment by tiagoalvesdulce** [comment]
Footer was removed on https://github.com/decred/politeiagui/milestone/2 but those links should be added in the future.

**Comment by marcopeereboom** [comment]
Footer is gone.
