### ISSUE TITLE
[UI/UX] The "Download Comments Bundle" link is not present without self comment

### ISSUE THREAD

**Issue by davecgh** [decred/politeiagui#784]
As the title indicates, the link to download comments bundle, which includes all comments, is not present if you have not commented on a proposal.  Since the bundle is for all comments, and not only your own, it seems like the display trigger should be the existence of *any* comment (e.g. >=1 comments) as opposed to a comment of your own.

**Comment by thi4go** [comment]
Fixed! PR 785
