### ISSUE TITLE
[User details] Invalid ID leads to unhandled error

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#798]
Access the User Details page with some invalid Id like:
`https://<hostname>/user/thisIsAnInvalidId`

While it should be handled gracefully and display a proper error, it is displaying a meaningless error:

<img width="1265" alt="screen shot 2018-10-26 at 12 06 18 pm" src="https://user-images.githubusercontent.com/14864439/47575073-94e04100-d917-11e8-99d7-6bf34718ee06.png">

Ideally, I think we should have a regex to match the ID in the URL and if the request fails, display the error properly.

**Comment by thi4go** [comment]
I'll take care of this bug
