### ISSUE TITLE
move nojs.css to /static/css

### ISSUE THREAD

**Issue by dajohi** [decred/politeiagui#800]

**Comment by dajohi** [comment]
so cache-control is applied.

**Comment by fernandoabolafio** [comment]
@dajohi can you provide more about what you want to be done here?

**Comment by tiagoalvesdulce** [comment]
`nojs.css` is already being cached
<img width="1111" alt="Screen_Shot_2020-01-31_at_12_13_18" src="https://user-images.githubusercontent.com/13955303/73550379-43c8d200-4423-11ea-9e4e-891490154739.png">
