### ISSUE TITLE
See on GitHub does not link to latest version

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#801]
1. I open https://proposals.decred.org/
2. Scroll to "Decred Open Source Research"
3. Click "See on GitHub"

It takes me to

https://github.com/decred-proposals/mainnet/tree/master/c68bb790ba0843980bb9695de4628995e75e0d1f36c992951db49eca7b3b4bcd/1

and in the payload dir I find the document for version 1, while there is also

https://github.com/decred-proposals/mainnet/tree/master/c68bb790ba0843980bb9695de4628995e75e0d1f36c992951db49eca7b3b4bcd/2

I think it should link to the latest version.

**Comment by tiagoalvesdulce** [comment]
Fixed on https://github.com/decred/politeiagui/pull/808

**Comment by xaur** [comment]
@tiagoalvesdulce it still sends to v1, is the fix deployed?

Also, the fix in #808 was to send the user one level up, to the list of all versions. This is better than sending to v1 but requires from some knowledge of the directory structure from the user to navigate.
