### ISSUE TITLE
Move logo to the left

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#807]
It currently shows centered, which is pretty uncommon.

**Comment by tiagoalvesdulce** [comment]
Hey @xaur, can you show us a screenshot? It's left aligned here, see:

<img width="1280" alt="screen shot 2018-10-29 at 11 14 49" src="https://user-images.githubusercontent.com/13955303/47655550-fd276080-db6b-11e8-9347-ce7a82f9cef7.png">

**Comment by xaur** [comment]
Sure

![politeia-logo-center](https://user-images.githubusercontent.com/24484727/47666002-6faf3500-db9a-11e8-8a88-c0dbbaeef9c2.png)
