### ISSUE TITLE
[identity] Bugs with identity management

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#809]
Steps:
 1. Go to the account page and download the identity
 2. Delete the identity from the browser
 3. Refresh the browser:

**Bug 1**: the field active identity is still showing some (incorrect) value. This field should just be blank or display something like "missing identity".

 4. Import the identity you've just downloaded, the result should be successful.
 5. Navigate away from the account page by clicking on the Politeia logo:

**Bug 2:** the alert banner will show up saying there is a problem with the identity. Which was just fixed.

**Comment by camus-code** [comment]
Working on this!
