### ISSUE TITLE
Show proposal quorum requirement on UI

### ISSUE THREAD

**Issue by RichardRed0x** [decred/politeiagui#810]
The quorum requirement for proposal votes is set at 20%, which will usually be around 8,192 votes but varies slightly depending on the ticket pool size when voting opens. It would be nice to show this on the UI, so that people can easily see how close proposals are to reaching the quorum requirement.

**Comment by fernandoabolafio** [comment]
depends on https://github.com/decred/politeia/issues/564

**Comment by s-ben** [comment]
Is the quorum subject to change? 

Just added an Issue to dcrdocs actually to add quorum and Yes vote threshold to Pi page,
https://github.com/decred/dcrdocs/issues/666

**Comment by RichardRed0x** [comment]
I would say the 20/60 quorum/approval thresholds are subject to change, but would probably be changed through a Pi proposal unless they turn out to be badly wrong.
