### ISSUE TITLE
receive and verify bundle after proposal submission

### ISSUE THREAD

**Issue by behindtext** [decred/politeiagui#82]
the censorship token amounts to a signature from a particular pi instance confirming that a proposal submission has been received. instead of having users lookup their proposal by id or censorship token to check its status, the user should be prompted to download a "proposal bundle", which would contain all the censorship data, along with the file(s) that make up the proposal.

beyond prompting the user to download a proposal bundle, there needs to be a simple tool that users can run to verify a censorship token is valid. this is important not only for the user being censored, but also other users who wish to verify the proposal in question was indeed censored.

**Comment by sndurkin** [comment]
> instead of having users lookup their proposal by id or censorship token to check its status

Users will still need to access Politeia to check on a proposal's status.


> the user should be prompted to download a "proposal bundle"

@go1dfish, is this something the UI can do without any server involvement, or will the bundle have to be hosted by the server for a period of time?

**Comment by tiagoalvesdulce** [comment]
Working on it
