### ISSUE TITLE
Login form on modal is really slow when on proposals route

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#829]
Being logged out, do the following steps:
- Go to a Proposal route which has received a reasonable amount of comments (5+)
- Click to vote up/down: the Login modal will show up
- Type the login credentials:
The typing is really slow while it should be fluid.

The main reason is that the state changes caused by the form typing are causing the entire proposal component to re-render.

**Comment by tiagoalvesdulce** [comment]
Solving this will require a big refactor, let's wait until the definition of using `snew-classic-ui` or not after the redesign (https://github.com/decred/dcrdesign/issues/77).

**Comment by fernandoabolafio** [comment]
Accomplished with the redesigned version.
