### ISSUE TITLE
Use international date format and time zone

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#834]
When you hover proposal timestamp, a tooltip shows US-specific date and time format. I suggest a global audit of all places where date/time is displayed to ensure:

* Date and time formats are international, I suggest `YYYY-MM-DD HH:mm`
* Time zone is UTC

**Comment by sndurkin** [comment]
Also, whichever TZ is used, it should be displayed to the user. So `YYYY-MM-DD HH:mm Z` or whatever.

**Comment by xaur** [comment]
`UTC` is better for end users than `Z`.

**Comment by sndurkin** [comment]
I'm just saying that regardless of whether it's displayed in UTC or another TZ, that TZ should be displayed to the user so that they don't have to guess which one the date is in. `Z`/`z` is usually the format letter for the timezone abbreviation.

**Comment by sndurkin** [comment]
@xaur, I made a small change in decred/snew-classic-ui#23 which displays this:

![image](https://user-images.githubusercontent.com/1452379/48564139-d71bf300-e8c3-11e8-9e6d-160be83682fe.png)

**Comment by xaur** [comment]
Pretty good, the only nit is iirc the GMT is deprecated in favor of UTC.

**Comment by sndurkin** [comment]
Yeah, I'm not sure why Chrome is displaying "GMT"; the function is called `toUTCString()`.
