### ISSUE TITLE
Flashing page redraw after page load

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#837]
When I reload https://proposals.decred.org/ with Ctrl+F5 I observe this:

1. blank page while assets are loading
1. some UI appears: header, sidebar and proposal filter tabs
   * tab headers show all 0 counters, body is empty
   * Log In button changes weirdly (yes, I have the nasty web fonts disabled, please do not abuse _fonts_ for _icons_)
1. proposal filter tabs disappear
1. rotating loader icon appears
1. full UI appears

Looks like this does not happen on individual proposal page.

See screenshots below:

![1](https://user-images.githubusercontent.com/24484727/47923052-5830be80-deb0-11e8-872f-b0edce4ed8e2.png)
![2](https://user-images.githubusercontent.com/24484727/47923053-5830be80-deb0-11e8-9195-9724a15d1457.png)
![3](https://user-images.githubusercontent.com/24484727/47923054-5830be80-deb0-11e8-95cc-c4289d47439f.png)
![4](https://user-images.githubusercontent.com/24484727/47923055-5830be80-deb0-11e8-973a-1dd76fbc25c6.png)
![5](https://user-images.githubusercontent.com/24484727/47923056-58c95500-deb0-11e8-8b03-af5fa297e38b.png)

**Comment by fernandoabolafio** [comment]
@xaur I believe this is a non-issue anymore due to the latest changes in the way proposals are being loaded. Please, refer to the testnet website to verify this as we haven't pushed it to production yet. I am closing it for now, feel free to re-open if you think something has been missed here.
