### ISSUE TITLE
Text overflows the Before you sign up box

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#838]
When I was signing up on Oct 26 I noticed this when resizing the browser window to be more narrow:

![20181026-signup-overflow](https://user-images.githubusercontent.com/24484727/47923369-20764680-deb1-11e8-80b0-f0f1d8449a0d.png)

**Comment by camus-code** [comment]
I think this is a duplicate of #612 but still a problem nonetheless

Working on a fix now

**Comment by tiagoalvesdulce** [comment]
Duplicate of https://github.com/decred/politeiagui/issues/612
