### ISSUE TITLE
Top banners with explicit account status

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#840]
Once I have sent payment tx and visited the site again nothing prompted me to download my identity. This led me to the following.

There should be a narrow (16-20 px) banner spanning full width on top until the account is fully active.

1. yellow banner saying that email needs to be verified, cannot dismiss
2. yellow banner saying that DCR fee must be paid, cannot dismiss
3. yellow banner forcing the user to download identity, cannot dismiss
   *  must dismiss automatically after the user finishes the download and acknowledges "I have backed up my identity"
4. green banner saying that account is ready, can dismiss

**Comment by tiagoalvesdulce** [comment]
This should be discussed on https://github.com/decred/dcrdesign/issues/77.

**Comment by marcopeereboom** [comment]
Part of redesign. Create new one once the new design goes live if not satisfactory.
