### ISSUE TITLE
Hide sidebar on narrow screens

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#843]
Side bar could yield to content when the screen is narrow.

![narrow-screen](https://user-images.githubusercontent.com/24484727/47924992-f9ba0f00-deb4-11e8-8470-d25a310e39a9.png)

**Comment by xaur** [comment]
@brunobraga95 stacking would be an improvement in terms of space. But still sub-optimal. If About is placed before content, you have to scroll one screen just to read something. If About is placed after content, it may be a long way to scroll in props with long discussions.

I think best is to have About or Help in the separate page. Once you learn the system you don't need it anymore.

**Comment by brunobraga95** [comment]
Good point, I will work on it.

**Comment by tiagoalvesdulce** [comment]
This is related to https://github.com/decred/politeiagui/issues/162 and will be discussed on https://github.com/decred/dcrdesign/issues/77

**Comment by xaur** [comment]
Moving sidebar to own About page is an instant win for mobile UX where screen space is precious, check [this screenshot](https://matrix.to/#/!VFRvyndKpzcLrVslQD:decred.org/$15505849541971VGIGJ:decred.org).
