### ISSUE TITLE
Disallow to upvote and downvote own comments

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#845]
It is confusing and arguably a bit harmful that upvoting own comments is neither automatic nor disabled:

* confusing because Politeia UX is very similar to Reddit UX and it fires up my Reddit neurons all the time
* harmful because it leads to comment score distortion as some authors upvote their comments while others don't, as demonstrated [here](https://github.com/RichardRed0x/pi-research/blob/master/data/comments-and-updown-votes/pi-users-comments-votes.csv)

There are two ways to remove user confusion and score distortion:

1. Upvote own comments by default
   * removes confusion by reducing UX difference with Reddit
   * allows to un-upvote and even downvote own comment later
   * cannot retroactively add upvotes in closed proposals
   * even for open proposals, cannot add upvotes on behalf of users (requires a signed message)
   * adjusting comment score in closed proposals will be an ugly hack
1. Do not upvote own comments _and_ do not allow it
   * less confusing than current behavior because it gives no choice
   * a bit more confusing for heavy Reddit users
   * if upvoting own comments is not allowed, so should be downvoting
   * bonus: slightly less data saved in the Git repo
   * adjusting comment score might be less ugly

Is downvoting own comments useful? I can imagine a use case: if I realize tomorrow that my comment is junk I can remove my upvote and add a downvote. However, I don't really expect anyone to use this feature, and besides comment voting is locked when proposal is voted or abandoned, so the window to change your mind is limited.

Considering multiple discussions I suggest to go with option 2:

* disable own upvotes and downvotes on future comments (reject them without saving to Git)
* recalculate score of existing comments to not account for self votes
* if possible, remove self votes from Git

Discussions:

* [2018-10-18](https://matrix.to/#/!VFRvyndKpzcLrVslQD:decred.org/$153988953632992GOYKc:decred.org)
* [2019-03-02](https://matrix.to/#/!lbzTjhzNbIaDbuAxkS:decred.org/$155154354314212PIYmG:decred.org)
* [2019-03-04](https://www.reddit.com/r/decred/comments/axe15w/is_it_ok_to_upvote_your_own_comments_on_politeia/)
* [2019-03-19](https://matrix.to/#/!MIGqWXfLFBwhipPKYL:decred.org/$155298458732381rqQPi:decred.org): it's a failing of the UI. 5 people agree it should not be possible.

**Comment by tiagoalvesdulce** [comment]
@marcopeereboom

**Comment by xaur** [comment]
Previous discussion: https://matrix.to/#/!VFRvyndKpzcLrVslQD:decred.org/$153988953632992GOYKc:decred.org

**Comment by xaur** [comment]
@tiagoalvesdulce what do you mean by "1 based"?

**Comment by tiagoalvesdulce** [comment]
@xaur start from 1 instead of 0.

**Comment by xaur** [comment]
Sorry I don't understand how it changes anything. Does it mean the score is 1 after I post a new comment? Can I still upvote it to 2 or downvote to 0?

**Comment by tiagoalvesdulce** [comment]
No, my proposal is that we prevent the user from voting on his own comments and start them from 1 (basically, the user automatically upvotes his own comment but he can't downvote or upvote one more time) @xaur

**Comment by marcopeereboom** [comment]
Sorry I disagree with the sentiment here. Clicking upvote on your own comment is not a huge ask from the user. And to give the counter argument, I find it confusing that reddit upvotes my comments.

Another reason to leave the behavior alone is that the starting at 0 has been encoded and used for a while now. If we change all new comments are skewed comparatively speaking.

**Comment by xaur** [comment]
This confuses some users, lowers productivity for those who care to upvote themselves, and skew the score for those who does not. All effects are not critical, but I'm for removing any weird stuff. Let's see if we get more reports for this.

Agreed to keep 0-based score because 1-based is a confusing way to implement the fix.

**Comment by xaur** [comment]
> And to give the counter argument, I find it confusing that reddit upvotes my comments.

Counter counter argument: Politeia GUI is based on Reddit. Reddit upvotes own comments by default. Most Reddit users _do not_ remove those default upvotes and are fine with them.

Related to decred/dcrdesign#77

**Comment by marcopeereboom** [comment]
This has been debated endlessly and we are not going to change this.

**Comment by xaur** [comment]
Last time the debate settled on some consensus that it should be disabled. Do we need a proposal for this?

**Comment by marcopeereboom** [comment]
From a code perspective, there is no way I'll implement this. This adds a ton of complexity and memory pressure to cache individual user votes for a single up/down vote count. If a single up/down vote matters we have much bigger problems. This is a theoretical issue that requires a lot of code.

If you feel strongly about this you should do a proposal and make sure you have someone willing to write acceptable code for it.

**Comment by xaur** [comment]
I imagine the minimum version of this feature as a check like `if user == comment.author then send error "Upvoting own comments is not allowed"`. A more advanced implementation is to also exclude own upvotes from score calculation.

How does this add memory pressure to cache individual user votes?
