### ISSUE TITLE
History of username changes

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#847]
This feature has two motivating factors:

1. Add transparency to prevent username abuse
1. Allow to add human-friendly username-based URLs like `/user/bob`

### Background.

I see it is possible to change username. It has a good use case of people negotiating and yielding usernames to each other. For example, if I call myself `wachsman` without knowing such a company exists, and then a company with such name shows up and makes a proposal, it is cool that I can voluntarily (or not, if admins can do it by force) yield this username to them to avoid confusion for everyone.

At the same time, games are possible here if malicious actors capture (squat) usernames via signup or username change.

People can also try to escape the bad reputation they earned by just changing username without paying for new account, since other people are unlikely to remember their UUID. This reason also complicates adding a username-based human friendly account URL like `/user/bob`.

To address both issues, I suggest to add an ability to know which accounts used which usernames in the past, and vice versa.

1. Record all username changes so it is possible to query all past usernames for an account ID and all account IDs for a username
1. Add a path like `/user/bob` that shows account page for the account currently holding that username. If >1 accounts ever held this username, also show an info block listing the accounts and links to their IDs.
1. Change the page for account ID (e.g. `/user/uuu-uuu-iii-ddd`) so that if it ever held >1 usernames, list them all.

**Comment by camus-code** [comment]
Working on #871 which depends on this so I'll pick this one up as well

**Comment by camus-code** [comment]
Actually #871 is standalone but I'm still working on this regardless

**Comment by xaur** [comment]
I think #871 is about the history of user public keys (identities), while this is about usernames. But still they are related.

**Comment by camus-code** [comment]
@xaur yeah I misread it when I first picked it up lol. Nevertheless that one is almost finished so I'll be working on this issue over the weekend

**Comment by fernandoabolafio** [comment]
@camus-code this PR requires work in the backend. We currently don't have the list of username changes available.

**Comment by camus-code** [comment]
@fernandoabolafio Yeah I'm realizing that now, my mistake. Should I file an issue on politeia for it?

**Comment by xaur** [comment]
Fair criticism @lukebp. Agreed this can be put on hold until the problem becomes real.

What about human friendly paths to user page?

**Comment by lukebp** [comment]
I believe the issue with using usernames in the url path is that changing the username will then break any external links to the user's profile page.

**Comment by xaur** [comment]
Right. GitHub and Discord are examples of systems where username is possible. They add a numeric code to the name that doesn't change, e.g. in Discord it is `username#9395`, and in GitHub it is `<28719273+username@users.noreply.github.com>`.

**Comment by fernandoabolafio** [comment]
> This also seems like a pre-optimization to me. IMO something like this should only be added after it has proven to be a problem.

I agree with @lukebp here. It doesn't seem to be a real issue yet. Even if does prove to be an issue we need the backend work first. So it is definitely not a GUI issue right now. If you want, you can move the discussion over the politeia repository.
