### ISSUE TITLE
Human firendly Under Maintenance page

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#865]
During server update, proposals.decred.org opened but the data (proposals) did not load and the body showed scary "500 Internal Server Error".

A human friendly page would be nice, e.g. "Under maintenance. Please check back later. Estimated completion time 2018-11-07 18:50 UTC".

**Comment by marcopeereboom** [comment]
Dup #1124

**Comment by xaur** [comment]
Technically 1124 is a dup of this ;)
