### ISSUE TITLE
Fetch user proposals using the UserProposals endpoint

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#875]
decred/politeia#586 and decred/politeia#587 need to be incorporated into the GUI.

The user details page uses the `UserDetails` route to fetch a user's proposals.  This is no longer possible due to decred/politeia#586.  The GUI should use the `UserProposals` route to fetch user proposals.

**Comment by brunobraga95** [comment]
I will work on this

**Comment by fernandoabolafio** [comment]
Hey @brunobraga95. This is already done on #876. You can leave your review If you want.
