### ISSUE TITLE
Distinguish proposal author's comments

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#877]
It would be useful to have a label on comments posted by proposal author. Similar to Reddit's `[S]` label, which stands for "submitter".

I suggest adding `author` label after the username. Alternatively, slightly change the background of the comment box using a calm color like pale light blue.

In any case it must be quite noticeable.

**Comment by xaur** [comment]
@fernandoabolafio wow this was so fast. Is there a preview screenshot or deployment available?

**Comment by tiagoalvesdulce** [comment]
<img width="468" alt="screen shot 2018-11-13 at 14 39 53" src="https://user-images.githubusercontent.com/13955303/48428376-0874b180-e752-11e8-9498-b5241a1f4eed.png">
