### ISSUE TITLE
Markdown preview isn't working

### ISSUE THREAD

**Issue by sndurkin** [decred/politeiagui#88]
The markdown preview area doesn't seem to be working.

Steps to reproduce:

1. Navigate to the new proposal page in Chrome.
2. Type `# Test` in the markdown editor.

Expected to see a header "Test" in the markdown preview area, but nothing is shown and there are no JS errors in the console.

**Comment by go1dfish** [comment]
Markdown preview is now a mode in the editor (far left button) but we can switch this back to a real-time mirror

**Comment by sndurkin** [comment]
Yeah, I think having a real-time preview would be useful, especially for users who aren't familiar with markdown formatting.

**Comment by fernandoabolafio** [comment]
It can be closed since #128 got merged
