### ISSUE TITLE
User should be required to answer the 5 questions (What, Why, How, Who, When) on the new proposal form.

### ISSUE THREAD

**Issue by zubairzia0** [decred/politeiagui#888]
**Motivation**:
There have been a few Pi proposals that have come in without any adherence formatting guidelines. Currently we have proposal guidelines available, however, it may benefit stakeholders if we can enforce formatting via the form. 

**Current state**:
In the current submit a proposal page we have the following form format. 

![image](https://user-images.githubusercontent.com/23157945/48434494-d65e5200-e747-11e8-9235-3336ea3cc007.png)

**Issue**:
Since we have a few basic formatting requirements it would be better if we make it mandatory to answer the 5 questions (What, Why, How, Who, When).

**Proposed solution(s):**
In my mind we can either have boxes which must be filled, or have the form detect key words with specific formating. An example of what it could look like. (Keep in mind these are very crude examples))

![image](https://user-images.githubusercontent.com/23157945/48435040-681a8f00-e749-11e8-8272-722f5ee6ecee.png)

or 

![image](https://user-images.githubusercontent.com/23157945/48435522-b714f400-e74a-11e8-9cab-6d9ff86573a1.png)

**Comment by tiagoalvesdulce** [comment]
Hey @zubairzia0, thanks for opening this issue. I think it should be discussed on https://github.com/decred/dcrdesign/issues/77.

**Comment by xaur** [comment]
I don't like this idea for:

* it does not really protect from malformed proposals
  * people can just enter junk to skip the fields, it's easy to please almost any validation with low effort
* 5 rich editors make the UI look bloated
* 5 editors make the UX complicated:
  * need to tab between them
  * cannot copy-paste a single document from my editor (_and back_)
* more complexity into editor or backend
  * need to merge 5 texts into one => not hard
  * need to deconstruct one text into 5 editors => hard, may not always be possible, incompatible with some existing data

However, the general idea of motivating authors to better format their proposals is worthwhile. I suggest instead:

* leave one editor
* pre-fill it with the 5 headings (`# What ... # Why ...` etc)
* continue thinking how to deal with low quality proposals that pass vetting

**Comment by RichardRed0x** [comment]
I also don't think imposing this structure on all proposals is a good idea. I agree with @xaur about this kind of structure not always being a good thing, and like the idea of pre-populating headings within a single body box.

Another point is that these headings won't be relevant to every proposal, for example policy type proposals probably wouldn't fit well into this structure.

**Comment by tiagoalvesdulce** [comment]
I agree with @xaur and @RichardRed0x, multiple rich editors make the UI bloated and we already have a link to `Learn How to Format your Proposal`. I'd say we should keep thinking about how to deal with low-quality proposals that pass vetting because imposing this structure on all proposals isn't a good idea.
