### ISSUE TITLE
Split "Finished voting" tab into "Approved" and "Rejected" tabs

### ISSUE THREAD

**Issue by RichardRed0x** [decred/politeiagui#904]
If a user wants to see "finished proposals" I think they're usually going to be looking specifically for approved proposals (to see how they're doing) or maybe rejected proposals (to see what's not being approved). Therefore I think it would make sense to split the finished proposals into these tabs. The system should already know whether each proposal is approved/rejected because the criteria and results are stored.

**Comment by tiagoalvesdulce** [comment]
Hey @RichardRed0x, what about proposals that don't reach quorum? Should we create a separate tab for them as well?
