### ISSUE TITLE
Comment is truncated when narrowing window

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#910]
Comment permalink: https://proposals.decred.org/proposals/fa38a3593d9a3f6cb2478a24c25114f5097c572f6dadf24c78bb521ed10992a4/comments/8

As I make browser window more narrow, the tail of the comment gets truncated.

Width 1232, all ok:

![truncated-comment-1-width-1232](https://user-images.githubusercontent.com/24484727/48799066-23b96100-ecfe-11e8-9e15-19ba5e79b4d3.png)

Witdh 1083, all ok:

![truncated-comment-2-width-1083](https://user-images.githubusercontent.com/24484727/48799084-2e73f600-ecfe-11e8-8ad9-60fd7e69cc34.png)

Width 1073, one line truncated:

![truncated-comment-3-width-1073](https://user-images.githubusercontent.com/24484727/48799106-35026d80-ecfe-11e8-9a92-814e97ae2c1f.png)

Width 1025, more truncated:

![truncated-comment-4-width-1025](https://user-images.githubusercontent.com/24484727/48799116-3df33f00-ecfe-11e8-8999-8c7b73b9af14.png)

**Comment by camus-code** [comment]
What browser were you using when this happened @xaur ? I'm having trouble reproducing it on my end

**Comment by sndurkin** [comment]
I was not able to reproduce either, please reopen with more detailed steps if this is still an issue.

**Comment by xaur** [comment]
Sorry for me lagging. Cannot reproduce on the same configuration that I discovered it on. Seems it was fixed somewhere. Thanks.
