### ISSUE TITLE
Comment permalink shows proposal images but not text

### ISSUE THREAD

**Issue by RichardRed0x** [decred/politeiagui#926]
Example: https://proposals.decred.org/proposals/e78bc28631d0e682912e3ece25944481bf978b906ea44b1ed36470c0f48b27fc/comments/4

The page does not show other comments or the body text of the proposal, seems like it should also not be showing any images associated with the proposal.

**Comment by victorgcramos** [comment]
I think the proposal text is being collapsed. If you click the arrow button, it shows the full body.
For me, it looks a little confused, so maybe we can show a message telling the user that the text is collapsed, and that it's possible to see the whole text by clicking on this button.

![captura de tela 2018-11-29 as 02 02 24](https://user-images.githubusercontent.com/22639213/49198570-e185c480-f37a-11e8-8109-6e2458d95df1.png)

**Comment by tiagoalvesdulce** [comment]
The images shouldn't be shown if the content is not expanded.
About collapsing, [Reddit does the same](https://www.reddit.com/r/decred/comments/a1bsv8/what_to_expect_from_the_ditto_partnership/eap18zb/).

**Comment by camus-code** [comment]
Picked this one up
