### ISSUE TITLE
Proposal cards' visual design improvement+indicating proposal vote success/failure

### ISSUE THREAD

**Issue by MariaPleshkova** [decred/politeiagui#946]
**Preview:** https://xd.adobe.com/view/1df61c35-62f4-4600-4cd9-b5851cf059c2-6bc7/
**Specs:** https://xd.adobe.com/spec/a64cd534-6bb6-4b26-7c60-baacff54913b-d07d/

Some proposal cards design improvements. Now they're in better relation to Decrediton (previous designs #821 ). Also showed different proposal states there as well. 4 cards with 4 different states (active, finished (success/failure) and abandoned). So partly this issue connects to #611 

Progress bar illustrates progress towards quorum. An empty area (behind green/red) represent the total amount of votes needed to pass the quorum. Both yes and no votes are divided between the length of the bar atm.
When quorum is passed, yes/no votes are divided between the full length of the bar.
Also once the quorum is completed, small gray vertical line appears. And when the mouse is over it, 60% stroke appears.

P.s. there'll be an icon for the censorship token later. Will be provided soon.

**Comment by fernandoabolafio** [comment]
@MariaPleshkova thanks for this work! The Proposal cards redesign looks nice! 
I have a few comments/questinons: 
 1. As per the discussion I had with @sndurkin on [this thread](https://github.com/decred/politeiagui/pull/942) the proposal token may not be needed in the proposal information as it appears in the URL once the user clicks the proposal. Or it could show up only when accessing the proposal details and not in the proposal list. What do you think? 

2. From the preview you provided, the empty area "represents the total amount of votes needed to pass the quorum." How can one know the number of votes missing to pass the quorum? (e.g num of votes / percentage). Maybe hovering the empty area?

3. This work doesn't contemplate the design for the proposals which haven't started the voting yet. Which can be:
 - Author has not yet authorized the start of voting
 - Waiting for administrator approval to start voting

4. From the current website design we also have a **permalink** button in the bottom of proposals cards which also leads to the proposal's route. Was it omitted by purpose?

**Comment by MariaPleshkova** [comment]
@fernandoabolafio thank you!

1. I'd suggest then to remove the proposal tokens from these proposal cards 
Example: https://xd.adobe.com/spec/a64cd534-6bb6-4b26-7c60-baacff54913b-d07d/
But keep them on the page of the full proposal (proposal details). I've already redesigned some Pi screens, so will provide them soon.

2. By writing this I was just trying to explain how proposal bar should work. Users are able to see the number of votes here 
![image](https://user-images.githubusercontent.com/8841018/50164319-6f5a2d00-02f3-11e9-8868-f696bbe4b0ed.png)

3. Hm, I didn't see such flows. I'll check, thanks

4. Yeah, I thought there's no need in this word, because it leads to the same page as if we clicked on the title (proposal details). So we can only just leave permalink sign in comments

**Comment by fernandoabolafio** [comment]
@MariaPleshkova sounds good, thanks for clarifying!
About 3, this is how it currently looks in the app:
<img width="921" alt="screen shot 2018-12-18 at 2 03 58 pm" src="https://user-images.githubusercontent.com/14864439/50166255-d238cd80-02cd-11e9-968b-961c391bfe83.png">

**Comment by sndurkin** [comment]
@fernandoabolafio it might be a good idea to also show the options available to administrators at the different states, since those buttons are displayed within the proposal cards as well IIRC.

**Comment by MariaPleshkova** [comment]
Got it, thanks @fernandoabolafio @sndurkin . I'll do that.

**Comment by MariaPleshkova** [comment]
@fernandoabolafio 
_"Notice that the authors and admin actions can appear all together when the proposal author is also an admin."_
As far as I understood, when an admin is also an author all 4 buttons buttons appear not at the same time. At first author's actions appear, like authorize voting to start/abandon, and after choosing "authorize" 2 new admin's actions will appear ( start vote/revoke). No?

**Comment by fernandoabolafio** [comment]
Pretty much @MariaPleshkova . The only thing is that the Start Vote is an admin action and the Revoke is an author action. Anyways it shouldn't affect the design. 
So yeah, in summary, the actions are:
 - Proposal just published
     - Authorize voting to start (author)
     - Abandon (admin)
- Proposal voting authorized to start:
     - Revoke voting authorization (author)
     - Start Vote (admin)

**Comment by linnutee** [comment]
Brief comments and instructions to this. I'm not sure whether the progress bar mechanic was completely understood, so did this illustrated example: https://xd.adobe.com/view/064fb338-f487-4719-7994-86b58169796e-707e/?fullscreen&hints=off

100% length cap of the bar = 20% quorum. Until that’s reached the bar is growing. When it’s reached/passed the votes are just divided between the 100% length of the bar. It’s an iteration from the Consensus voting progress bar mechanic (which was a bit more elaborate/too complex for this) https://github.com/decred/hardforkdemo/issues/136

Also I recon the "60% yes" should likely be hidden until the progress bar has reached 100% length or passed the quorum, because it's obsolete until that. As well maybe only display it on hovering the progress bar.  

And would consider adding a tooltip to this "3320/8192" what displays on hover “x votes needed for quorum” or "Quorum has been reached"

**Comment by MariaPleshkova** [comment]
New states of proposal cards ( + admin's/author's views)
Specs: https://xd.adobe.com/spec/a64cd534-6bb6-4b26-7c60-baacff54913b-d07d/
Preview: https://xd.adobe.com/view/1df61c35-62f4-4600-4cd9-b5851cf059c2-6bc7/
![image](https://user-images.githubusercontent.com/8841018/50681773-bcd9d800-101d-11e9-8419-7adda28626ab.png)


According "60% yes" Tanel's right. It appers only on hovering. I suggest to show this little stroke (gray vertical line between 60% and pointer) as soon as the progress bar reached 100% length or passed the quorum. And then to show 60% on hovering this stroke. This way users can see that something should appear there.
![image](https://user-images.githubusercontent.com/8841018/50682296-71c0c480-101f-11e9-8922-1df862b2aa90.png)


Also added a small tooltip to the number of votes 
![image](https://user-images.githubusercontent.com/8841018/50682264-5655b980-101f-11e9-9d14-5628aa9728dc.png)

**Comment by MariaPleshkova** [comment]
Decided to change yellow text and icon color ("waiting for approval") to a darker one #cfa03f, but left its border color as it is now.
Specs: https://xd.adobe.com/spec/a64cd534-6bb6-4b26-7c60-baacff54913b-d07d/
Preview: https://xd.adobe.com/view/1df61c35-62f4-4600-4cd9-b5851cf059c2-6bc7/

**Comment by fernandoabolafio** [comment]
Latest specs can be grabbed from https://github.com/decred/dcrdesign/issues/159
