### ISSUE TITLE
Don't redirect to logout page on session expiration

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#953]
Per jy-p on Slack:

"something i find very annoying about pi's frontend is that when you get logged out after a period of inactivity, it sends all the open pages to the logged out page

e.g. i have N proposal pages open for reading, then i have to explicitly revisit those pages after a login expires and is auto-logged out"

**Comment by thi4go** [comment]
I'll work on this!

**Comment by fernandoabolafio** [comment]
@thi4go none of the tabs should be redirected to the logout page if the user is in a public route. Do you still want to work on it? 

This is also related to https://github.com/decred/politeiagui/issues/1031.
