### ISSUE TITLE
External Link Warning modal needs to keep domain names within bounds 

### ISSUE THREAD

**Issue by degeri** [decred/politeiagui#959]
Right now if a user inputs URL 

https://unusuallylongdomainnamexyzsomethingsomethingzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz.com/test.html 

the domain name is going out of the modal bounds. 

Check in this link:
https://test-proposals.decred.org/proposals/61b7dfda2af52cc3e54ea5117b479463f82d8ab88fd5d9f92beca24ca0bb8e5f

![image](https://user-images.githubusercontent.com/41839293/50601054-12f13300-0ed9-11e9-92d8-581982eb0ec3.png)

**Comment by camus-code** [comment]
I'll pick this one up since I worked on this code last
