### ISSUE TITLE
External Link Warning modal should auto close on certain situations.

### ISSUE THREAD

**Issue by degeri** [decred/politeiagui#960]
External Link Warning modal should auto close:

1.
When "backbutton" is pressed on the browser.

2.
When user clicks outside the modal instead of on "Cancel" or "Proceed". 

See the video below for both behaviors. 

[Screencast 2019-01-02.mp4.zip](https://github.com/decred/politeiagui/files/2721334/Screencast.2019-01-02.mp4.zip)

**Comment by camus-code** [comment]
Working on this!
