### ISSUE TITLE
Token recreation UX

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#964]
Feedback from @snr01 in [chat](https://matrix.to/#/!MIGqWXfLFBwhipPKYL:decred.org/$15462859034716ajGaw:decred.org):

> Fyi: one of the main reasons I prefer this channel to discussing on Pi itself is that it's a pain to recreate tokens between mobile, home PC, work PC, etc... I would make the extra effort for a comment I felt was very meaningful though.

**Comment by fernandoabolafio** [comment]
The token recreation UX goes around lots of privacy/security discussions and requires a lot of backend work. Hence, I don't think this is a GUI issue right now, we can revisit this later.
