### ISSUE TITLE
Test site version diff viewer issues

### ISSUE THREAD

**Issue by RichardRed0x** [decred/politeiagui#966]
I have been testing edits on [this proposal](https://test-proposals.decred.org/proposals/e1d3ce96d53d969b88d4d84a662adda85cd9bf84903d415edb96b41c2b5b60ec). I noticed some of the edits are not reflected in the diff displayed in the version modal. Here are a few examples:
- version 2: only shows the first edit, I removed the Treasury Balance line and date from the top in this edit too (you can see in version 3 they are gone, but they're still shown in version 2)
- version 7: Edited the Baeond link to change Futurepunk to Futurefunk - the word and the rest of the link text disappeared in the version's modal window.
- version 8: Edited "pre-proposal on reddit" link, the word I edited (reddit) and everything after it has disappeared from the modal window.

**Comment by RichardRed0x** [comment]
Looks like there are issues with the version viewer whenever I edit a title (#, ## etc.) and the text for a link, but editing link URL works fine.

**Comment by victorgcramos** [comment]
I can work on that!

**Comment by victorgcramos** [comment]
I couldn't replicate those errors... It looks good to me! Version 2 is not showing the Treasury balance as you said. Could you check it again to see if the error persists? @RichardRed0x

**Comment by victorgcramos** [comment]
@fernandoabolafio gave me a north on this issue. Looks like I need to reenable the comments from #971 in order to test this. I can now work on that! Thanks to y'all!
