### ISSUE TITLE
Build is failing silently

### ISSUE THREAD

**Issue by jholdstock** [decred/politeiagui#982]
The build is currently failing but travis is reporting success because the build script is incorrectly exiting with exit code 0.

The failure:

```
$ react-scripts build
Creating an optimized production build...
Failed to compile.
Failed to minify the code from this file: 
     ./node_modules/query-string/index.js:8 ```

**Comment by fernandoabolafio** [comment]
closed on https://github.com/decred/politeiagui/pull/985
