### ISSUE TITLE
Politeia design improvements

### ISSUE THREAD

**Issue by MariaPleshkova** [decred/politeiagui#989]
Tweaked up current Pi UI design to a bit more consistent and improved quality levels.
Below you can find main redesigned pages:
**Preview:** https://xd.adobe.com/view/16d02845-4b7e-452f-78dd-045a5755729b-60e1/
**Specs:** https://xd.adobe.com/spec/dfc7f02f-3c2f-42ba-4b24-77824309bc20-a9f6/

**Comment by fernandoabolafio** [comment]
Latest specs can be grabbed from https://github.com/decred/dcrdesign/issues/159
